// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_profiles.sql

package store

import (
	"context"
	"database/sql"
)

const createAgentProfile = `-- name: CreateAgentProfile :one
INSERT INTO agent_profiles (id, name, role, description, project_id, avatar, config)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, role, description, project_id, avatar, config, created_at, updated_at
`

type CreateAgentProfileParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Role        string         `json:"role"`
	Description string         `json:"description"`
	ProjectID   sql.NullString `json:"project_id"`
	Avatar      string         `json:"avatar"`
	Config      string         `json:"config"`
}

func (q *Queries) CreateAgentProfile(ctx context.Context, arg CreateAgentProfileParams) (AgentProfile, error) {
	row := q.db.QueryRowContext(ctx, createAgentProfile,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.Description,
		arg.ProjectID,
		arg.Avatar,
		arg.Config,
	)
	var i AgentProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Description,
		&i.ProjectID,
		&i.Avatar,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgentProfile = `-- name: DeleteAgentProfile :exec
DELETE FROM agent_profiles WHERE id = ?
`

func (q *Queries) DeleteAgentProfile(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAgentProfile, id)
	return err
}

const getAgentProfile = `-- name: GetAgentProfile :one
SELECT id, name, role, description, project_id, avatar, config, created_at, updated_at FROM agent_profiles WHERE id = ?
`

func (q *Queries) GetAgentProfile(ctx context.Context, id string) (AgentProfile, error) {
	row := q.db.QueryRowContext(ctx, getAgentProfile, id)
	var i AgentProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Description,
		&i.ProjectID,
		&i.Avatar,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentProfiles = `-- name: ListAgentProfiles :many
SELECT id, name, role, description, project_id, avatar, config, created_at, updated_at FROM agent_profiles ORDER BY name ASC
`

func (q *Queries) ListAgentProfiles(ctx context.Context) ([]AgentProfile, error) {
	rows, err := q.db.QueryContext(ctx, listAgentProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentProfile{}
	for rows.Next() {
		var i AgentProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Description,
			&i.ProjectID,
			&i.Avatar,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentProfile = `-- name: UpdateAgentProfile :one
UPDATE agent_profiles
SET name = ?, role = ?, description = ?, project_id = ?, avatar = ?, config = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
RETURNING id, name, role, description, project_id, avatar, config, created_at, updated_at
`

type UpdateAgentProfileParams struct {
	Name        string         `json:"name"`
	Role        string         `json:"role"`
	Description string         `json:"description"`
	ProjectID   sql.NullString `json:"project_id"`
	Avatar      string         `json:"avatar"`
	Config      string         `json:"config"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateAgentProfile(ctx context.Context, arg UpdateAgentProfileParams) (AgentProfile, error) {
	row := q.db.QueryRowContext(ctx, updateAgentProfile,
		arg.Name,
		arg.Role,
		arg.Description,
		arg.ProjectID,
		arg.Avatar,
		arg.Config,
		arg.ID,
	)
	var i AgentProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Description,
		&i.ProjectID,
		&i.Avatar,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
