// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assistant.sql

package store

import (
	"context"
	"database/sql"
)

const countAssistantJournalUnseen = `-- name: CountAssistantJournalUnseen :one
SELECT COUNT(*) FROM assistant_journal
WHERE json_extract(seen_by, '$.' || ?1) IS NULL
`

// How many entries this surface has never been shown. The rail's notch reads
// it once per connection; the journal pushes keep it current after that.
func (q *Queries) CountAssistantJournalUnseen(ctx context.Context, surface sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAssistantJournalUnseen, surface)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssistantChannel = `-- name: CreateAssistantChannel :one
INSERT INTO channels (id, name, kind) VALUES (?, ?, 'assistant') RETURNING id, name, project_id, created_at, kind
`

type CreateAssistantChannelParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreateAssistantChannel(ctx context.Context, arg CreateAssistantChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createAssistantChannel, arg.ID, arg.Name)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.CreatedAt,
		&i.Kind,
	)
	return i, err
}

const deleteAssistantFollow = `-- name: DeleteAssistantFollow :exec
DELETE FROM assistant_follows WHERE session_id = ?
`

func (q *Queries) DeleteAssistantFollow(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteAssistantFollow, sessionID)
	return err
}

const getAssistantChannel = `-- name: GetAssistantChannel :one
SELECT id, name, project_id, created_at, kind FROM channels WHERE kind = 'assistant' ORDER BY created_at ASC, id ASC LIMIT 1
`

// The conversation, found without the state row. The oldest wins: if a second
// one was ever created, the first is the one the history is in.
func (q *Queries) GetAssistantChannel(ctx context.Context) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getAssistantChannel)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.CreatedAt,
		&i.Kind,
	)
	return i, err
}

const getAssistantFollow = `-- name: GetAssistantFollow :one
SELECT session_id, since, briefed, source FROM assistant_follows WHERE session_id = ?
`

func (q *Queries) GetAssistantFollow(ctx context.Context, sessionID string) (AssistantFollow, error) {
	row := q.db.QueryRowContext(ctx, getAssistantFollow, sessionID)
	var i AssistantFollow
	err := row.Scan(
		&i.SessionID,
		&i.Since,
		&i.Briefed,
		&i.Source,
	)
	return i, err
}

const getAssistantState = `-- name: GetAssistantState :one

SELECT id, channel_id, model, last_heartbeat_at, last_digest_at, surface_marks, created_at, updated_at FROM assistant_state WHERE id = 1
`

// The assistant's state, journal, follow list and conversation channel.
// See docs/assistant.md and migration 056.
//
// Keep this file ASCII. sqlc expands `SELECT *` by byte offset, so one
// multi-byte character shifts those offsets and corrupts the generated code
// for LATER queries.
func (q *Queries) GetAssistantState(ctx context.Context) (AssistantState, error) {
	row := q.db.QueryRowContext(ctx, getAssistantState)
	var i AssistantState
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Model,
		&i.LastHeartbeatAt,
		&i.LastDigestAt,
		&i.SurfaceMarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAssistantJournalEntry = `-- name: InsertAssistantJournalEntry :one
INSERT INTO assistant_journal (at, kind, session_id, project_id, summary, payload, untrusted, notable)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, at, kind, session_id, project_id, summary, payload, untrusted, notable, seen_by, created_at
`

type InsertAssistantJournalEntryParams struct {
	At        string `json:"at"`
	Kind      string `json:"kind"`
	SessionID string `json:"session_id"`
	ProjectID string `json:"project_id"`
	Summary   string `json:"summary"`
	Payload   string `json:"payload"`
	Untrusted int64  `json:"untrusted"`
	Notable   int64  `json:"notable"`
}

func (q *Queries) InsertAssistantJournalEntry(ctx context.Context, arg InsertAssistantJournalEntryParams) (AssistantJournal, error) {
	row := q.db.QueryRowContext(ctx, insertAssistantJournalEntry,
		arg.At,
		arg.Kind,
		arg.SessionID,
		arg.ProjectID,
		arg.Summary,
		arg.Payload,
		arg.Untrusted,
		arg.Notable,
	)
	var i AssistantJournal
	err := row.Scan(
		&i.ID,
		&i.At,
		&i.Kind,
		&i.SessionID,
		&i.ProjectID,
		&i.Summary,
		&i.Payload,
		&i.Untrusted,
		&i.Notable,
		&i.SeenBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertAssistantMessage = `-- name: InsertAssistantMessage :one
INSERT INTO messages (id, channel_id, sender_type, sender_id, sender_name, content, message_type, metadata, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, channel_id, sender_type, sender_id, sender_name, content, message_type, metadata, created_at
`

type InsertAssistantMessageParams struct {
	ID          string `json:"id"`
	ChannelID   string `json:"channel_id"`
	SenderType  string `json:"sender_type"`
	SenderID    string `json:"sender_id"`
	SenderName  string `json:"sender_name"`
	Content     string `json:"content"`
	MessageType string `json:"message_type"`
	Metadata    string `json:"metadata"`
	CreatedAt   string `json:"created_at"`
}

// One message of the conversation.
//
// Its own insert rather than InsertMessage because created_at is passed IN.
// The table's default stamps milliseconds, and an ask and its reply can land
// in the same millisecond -- at which point the only tiebreak left is the
// uuid, and the two read back in no order at all. A fixed-width nanosecond
// stamp sorts lexicographically, which for this column is the only kind of
// sorting there is. Nothing else writes to an assistant channel, so the
// sharper format is consistent within the timeline that reads it.
func (q *Queries) InsertAssistantMessage(ctx context.Context, arg InsertAssistantMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, insertAssistantMessage,
		arg.ID,
		arg.ChannelID,
		arg.SenderType,
		arg.SenderID,
		arg.SenderName,
		arg.Content,
		arg.MessageType,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.SenderType,
		&i.SenderID,
		&i.SenderName,
		&i.Content,
		&i.MessageType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAssistantFollows = `-- name: ListAssistantFollows :many
SELECT session_id, since, briefed, source FROM assistant_follows ORDER BY since ASC
`

func (q *Queries) ListAssistantFollows(ctx context.Context) ([]AssistantFollow, error) {
	rows, err := q.db.QueryContext(ctx, listAssistantFollows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistantFollow{}
	for rows.Next() {
		var i AssistantFollow
		if err := rows.Scan(
			&i.SessionID,
			&i.Since,
			&i.Briefed,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistantJournalSince = `-- name: ListAssistantJournalSince :many
SELECT id, at, kind, session_id, project_id, summary, payload, untrusted, notable, seen_by, created_at FROM assistant_journal
WHERE at >= ?1
ORDER BY at DESC, id DESC
LIMIT ?2
`

type ListAssistantJournalSinceParams struct {
	Since string `json:"since"`
	Lim   int64  `json:"lim"`
}

func (q *Queries) ListAssistantJournalSince(ctx context.Context, arg ListAssistantJournalSinceParams) ([]AssistantJournal, error) {
	rows, err := q.db.QueryContext(ctx, listAssistantJournalSince, arg.Since, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistantJournal{}
	for rows.Next() {
		var i AssistantJournal
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Kind,
			&i.SessionID,
			&i.ProjectID,
			&i.Summary,
			&i.Payload,
			&i.Untrusted,
			&i.Notable,
			&i.SeenBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistantJournalUnseen = `-- name: ListAssistantJournalUnseen :many
SELECT id, at, kind, session_id, project_id, summary, payload, untrusted, notable, seen_by, created_at FROM assistant_journal
WHERE json_extract(seen_by, '$.' || ?1) IS NULL
ORDER BY at DESC, id DESC
LIMIT ?2
`

type ListAssistantJournalUnseenParams struct {
	Surface sql.NullString `json:"surface"`
	Lim     int64          `json:"lim"`
}

func (q *Queries) ListAssistantJournalUnseen(ctx context.Context, arg ListAssistantJournalUnseenParams) ([]AssistantJournal, error) {
	rows, err := q.db.QueryContext(ctx, listAssistantJournalUnseen, arg.Surface, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistantJournal{}
	for rows.Next() {
		var i AssistantJournal
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Kind,
			&i.SessionID,
			&i.ProjectID,
			&i.Summary,
			&i.Payload,
			&i.Untrusted,
			&i.Notable,
			&i.SeenBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistantMessagesBefore = `-- name: ListAssistantMessagesBefore :many
SELECT id, channel_id, sender_type, sender_id, sender_name, content, message_type, metadata, created_at FROM messages
WHERE channel_id = ?1
  AND (?2 = '' OR (created_at, id) < (?2, ?3))
ORDER BY created_at DESC, id DESC
LIMIT ?4
`

type ListAssistantMessagesBeforeParams struct {
	ChannelID string      `json:"channel_id"`
	BeforeAt  interface{} `json:"before_at"`
	BeforeID  string      `json:"before_id"`
	Lim       int64       `json:"lim"`
}

// One page of the conversation, newest first. An empty `before` starts at the
// newest message; otherwise it is a created_at cursor.
//
// rowid breaks the tie, not id. messages.created_at has millisecond precision
// and a message's id is a uuid, so two turns written in the same millisecond --
// an ask and a mirrored reply -- would come back in uuid order, which is to say
// in no order. rowid is insertion order, which is the order they were said in.
func (q *Queries) ListAssistantMessagesBefore(ctx context.Context, arg ListAssistantMessagesBeforeParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listAssistantMessagesBefore,
		arg.ChannelID,
		arg.BeforeAt,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.SenderType,
			&i.SenderID,
			&i.SenderName,
			&i.Content,
			&i.MessageType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistantMessagesSince = `-- name: ListAssistantMessagesSince :many
SELECT id, channel_id, sender_type, sender_id, sender_name, content, message_type, metadata, created_at FROM messages
WHERE channel_id = ?1 AND created_at > ?2
ORDER BY created_at ASC, id ASC
LIMIT ?3
`

type ListAssistantMessagesSinceParams struct {
	ChannelID string `json:"channel_id"`
	Since     string `json:"since"`
	Lim       int64  `json:"lim"`
}

// What has been said in the conversation since a surface last looked, oldest
// first: this is read to be pasted into a preamble or a strip, in order.
func (q *Queries) ListAssistantMessagesSince(ctx context.Context, arg ListAssistantMessagesSinceParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listAssistantMessagesSince, arg.ChannelID, arg.Since, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.SenderType,
			&i.SenderID,
			&i.SenderName,
			&i.Content,
			&i.MessageType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionOutcomeBaseline = `-- name: ListSessionOutcomeBaseline :many
SELECT id, worktree_merged, archived_at FROM sessions
`

type ListSessionOutcomeBaselineRow struct {
	ID             string         `json:"id"`
	WorktreeMerged int64          `json:"worktree_merged"`
	ArchivedAt     sql.NullString `json:"archived_at"`
}

// The session.state observer's baseline: what every session's two outcome
// facts already were before the observer started watching. A push is a whole
// snapshot, not a transition, so without this the first push for a session
// archived last month reads as news -- and on the first boot with the
// assistant on, that was one entry per archived session ever.
func (q *Queries) ListSessionOutcomeBaseline(ctx context.Context) ([]ListSessionOutcomeBaselineRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionOutcomeBaseline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionOutcomeBaselineRow{}
	for rows.Next() {
		var i ListSessionOutcomeBaselineRow
		if err := rows.Scan(&i.ID, &i.WorktreeMerged, &i.ArchivedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAssistantJournalSeenThrough = `-- name: MarkAssistantJournalSeenThrough :exec
UPDATE assistant_journal
SET seen_by = json_set(seen_by, '$.' || ?1, ?2)
WHERE json_extract(seen_by, '$.' || ?1) IS NULL
  AND (at < ?3
       OR (at = ?3 AND id <= ?4))
`

type MarkAssistantJournalSeenThroughParams struct {
	Surface   sql.NullString `json:"surface"`
	At        interface{}    `json:"at"`
	ThroughAt string         `json:"through_at"`
	ThroughID int64          `json:"through_id"`
}

// Stamps everything this surface has now been shown, THROUGH the newest row it
// was handed.
//
// Through a boundary rather than row by row, because a look is bounded and the
// journal is not: stamping only the rows returned left a backlog larger than
// one page unseen, so the next look answered with the next fifty OLDER entries
// and announced last week as news. The boundary is the newest row of the look,
// so what it means is "you are caught up to here" -- which is the only reading
// that is monotonic in time.
//
// Already-stamped rows are left alone: a second surface's mark must not be
// rewritten, and re-stamping the whole history on every look would be an
// UPDATE over the table.
func (q *Queries) MarkAssistantJournalSeenThrough(ctx context.Context, arg MarkAssistantJournalSeenThroughParams) error {
	_, err := q.db.ExecContext(ctx, markAssistantJournalSeenThrough,
		arg.Surface,
		arg.At,
		arg.ThroughAt,
		arg.ThroughID,
	)
	return err
}

const setAssistantChannel = `-- name: SetAssistantChannel :exec
INSERT INTO assistant_state (id, channel_id, created_at, updated_at)
VALUES (1, ?1, ?2, ?2)
ON CONFLICT(id) DO UPDATE SET
  channel_id = excluded.channel_id,
  updated_at = excluded.updated_at
`

type SetAssistantChannelParams struct {
	ChannelID string `json:"channel_id"`
	Now       string `json:"now"`
}

func (q *Queries) SetAssistantChannel(ctx context.Context, arg SetAssistantChannelParams) error {
	_, err := q.db.ExecContext(ctx, setAssistantChannel, arg.ChannelID, arg.Now)
	return err
}

const setAssistantFollowBriefed = `-- name: SetAssistantFollowBriefed :exec
UPDATE assistant_follows SET briefed = ? WHERE session_id = ?
`

type SetAssistantFollowBriefedParams struct {
	Briefed   int64  `json:"briefed"`
	SessionID string `json:"session_id"`
}

func (q *Queries) SetAssistantFollowBriefed(ctx context.Context, arg SetAssistantFollowBriefedParams) error {
	_, err := q.db.ExecContext(ctx, setAssistantFollowBriefed, arg.Briefed, arg.SessionID)
	return err
}

const setAssistantModel = `-- name: SetAssistantModel :exec
INSERT INTO assistant_state (id, model, created_at, updated_at)
VALUES (1, ?1, ?2, ?2)
ON CONFLICT(id) DO UPDATE SET
  model = excluded.model,
  updated_at = excluded.updated_at
`

type SetAssistantModelParams struct {
	Model string `json:"model"`
	Now   string `json:"now"`
}

func (q *Queries) SetAssistantModel(ctx context.Context, arg SetAssistantModelParams) error {
	_, err := q.db.ExecContext(ctx, setAssistantModel, arg.Model, arg.Now)
	return err
}

const setAssistantSurfaceMark = `-- name: SetAssistantSurfaceMark :exec
INSERT INTO assistant_state (id, surface_marks, created_at, updated_at)
VALUES (1, json_set('{}', '$.' || ?1, ?2), ?3, ?3)
ON CONFLICT(id) DO UPDATE SET
  surface_marks = json_set(assistant_state.surface_marks, '$.' || ?1, ?2),
  updated_at = excluded.updated_at
`

type SetAssistantSurfaceMarkParams struct {
	Surface sql.NullString `json:"surface"`
	At      interface{}    `json:"at"`
	Now     string         `json:"now"`
}

// Records that a surface has looked. json_set on the existing object rather
// than a rewrite, so two surfaces cannot overwrite each other's mark.
//
// The DO UPDATE clause uses ?1/?2 rather than sqlc.arg(): sqlc does NOT rewrite
// a named parameter inside an upsert's DO UPDATE, it copies the text through,
// and `sqlc.arg(surface)` reaching SQLite is a runtime error in a statement
// whose failure this code only logs. The numbers are the same parameters the
// VALUES clause names.
func (q *Queries) SetAssistantSurfaceMark(ctx context.Context, arg SetAssistantSurfaceMarkParams) error {
	_, err := q.db.ExecContext(ctx, setAssistantSurfaceMark, arg.Surface, arg.At, arg.Now)
	return err
}

const upsertAssistantFollow = `-- name: UpsertAssistantFollow :exec
INSERT INTO assistant_follows (session_id, since, briefed, source)
VALUES (?, ?, 0, ?)
ON CONFLICT(session_id) DO UPDATE SET source = excluded.source
`

type UpsertAssistantFollowParams struct {
	SessionID string `json:"session_id"`
	Since     string `json:"since"`
	Source    string `json:"source"`
}

func (q *Queries) UpsertAssistantFollow(ctx context.Context, arg UpsertAssistantFollowParams) error {
	_, err := q.db.ExecContext(ctx, upsertAssistantFollow, arg.SessionID, arg.Since, arg.Source)
	return err
}
