// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assistant.sql

package store

import (
	"context"
	"database/sql"
)

const countAssistantJournalSince = `-- name: CountAssistantJournalSince :one
SELECT COUNT(*) FROM assistant_journal
WHERE at >= ?1 AND kind != 'heartbeat'
`

// The heartbeat's gate: has anything happened since the last beat.
//
// The assistant's OWN heartbeat entries are excluded, and that exclusion is
// what makes the gate able to close: a tick journals its verdict and stamps
// the mark in the same second, so counting its own row would leave every
// later tick with one entry to triage and a Haiku call to pay for it. The
// lower boundary is inclusive, as the digest's is, on the same reasoning --
// triaging one entry twice costs a tick, dropping one loses news.
func (q *Queries) CountAssistantJournalSince(ctx context.Context, since string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAssistantJournalSince, since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAssistantJournalUnseen = `-- name: CountAssistantJournalUnseen :one
SELECT COUNT(*) FROM assistant_journal
WHERE json_extract(seen_by, '$.' || ?1) IS NULL
  AND kind != 'heartbeat'
`

// How many entries this surface has never been shown. The rail's notch reads
// it once per connection; the journal pushes keep it current after that.
//
// Same exclusion, and here it is the load-bearing one: a badge is a claim on
// attention, so a heartbeat that ticks every fifteen minutes would put a
// permanent notch on the assistant's row and teach the operator to ignore it.
func (q *Queries) CountAssistantJournalUnseen(ctx context.Context, surface sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAssistantJournalUnseen, surface)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPolicySessionsCreatedSince = `-- name: CountPolicySessionsCreatedSince :one
SELECT COUNT(*) FROM assistant_journal
WHERE kind = 'session_created'
  AND at >= ?1
  AND json_extract(payload, '$.policyId') = ?2
`

type CountPolicySessionsCreatedSinceParams struct {
	Since    string `json:"since"`
	PolicyID string `json:"policy_id"`
}

// A policy's day budget: how many sessions this standing instruction has
// created since a stamp.
//
// Counted in SQL rather than by paging the journal into Go, and that is the
// point rather than an optimisation. The page was 2000 rows over a fourteen-day
// window and FAILED CLOSED when it filled, so a machine busy enough to journal
// 143 entries a day would have refused every budgeted verb from then on, with
// one log line to explain it -- and the day-summary compaction that would have
// bounded the window is not built. A count has no page to fill.
//
// The payload path is '$.policyId', which is `payloadPolicyID` in
// internal/assistant: the key is spelled in both places, so a rename is two
// edits or a budget that counts nothing.
func (q *Queries) CountPolicySessionsCreatedSince(ctx context.Context, arg CountPolicySessionsCreatedSinceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPolicySessionsCreatedSince, arg.Since, arg.PolicyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssistantChannel = `-- name: CreateAssistantChannel :one
INSERT INTO channels (id, name, kind) VALUES (?, ?, 'assistant') RETURNING id, name, project_id, created_at, kind
`

type CreateAssistantChannelParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreateAssistantChannel(ctx context.Context, arg CreateAssistantChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createAssistantChannel, arg.ID, arg.Name)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.CreatedAt,
		&i.Kind,
	)
	return i, err
}

const decideAssistantProposal = `-- name: DecideAssistantProposal :execrows
UPDATE assistant_proposals
SET status = ?1,
    decided_at = ?2,
    decided_via = ?3,
    outcome = ?4
WHERE id = ?5 AND status = 'open'
`

type DecideAssistantProposalParams struct {
	Status     string `json:"status"`
	DecidedAt  string `json:"decided_at"`
	DecidedVia string `json:"decided_via"`
	Outcome    string `json:"outcome"`
	ID         string `json:"id"`
}

// The decision. Guarded on status = 'open' so two surfaces cannot both decide
// one proposal: the second write touches nothing, and the caller re-reads the
// row it did not change.
//
// It answers how many rows it changed, so the caller does not have to assume
// the guard matched. Zero means somebody else settled this proposal first,
// which is a different thing from the write failing -- and after an action has
// already been performed, the difference is worth a log line that says which.
func (q *Queries) DecideAssistantProposal(ctx context.Context, arg DecideAssistantProposalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, decideAssistantProposal,
		arg.Status,
		arg.DecidedAt,
		arg.DecidedVia,
		arg.Outcome,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAssistantFollow = `-- name: DeleteAssistantFollow :exec
DELETE FROM assistant_follows WHERE session_id = ?
`

func (q *Queries) DeleteAssistantFollow(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteAssistantFollow, sessionID)
	return err
}

const deleteAssistantPolicy = `-- name: DeleteAssistantPolicy :exec
DELETE FROM assistant_policies WHERE id = ?
`

func (q *Queries) DeleteAssistantPolicy(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAssistantPolicy, id)
	return err
}

const expireAssistantProposals = `-- name: ExpireAssistantProposals :exec
UPDATE assistant_proposals
SET status = 'expired', decided_at = ?1
WHERE status = 'open' AND expires_at != '' AND expires_at <= ?1
`

// Lazy expiry, applied on a decide: an open proposal past its expiry is not an
// offer any more. There is no timer behind this -- a proposal nobody looks at
// costs nothing, and a sweep would be a second writer on a table whose whole
// content is decisions.
func (q *Queries) ExpireAssistantProposals(ctx context.Context, at string) error {
	_, err := q.db.ExecContext(ctx, expireAssistantProposals, at)
	return err
}

const getAssistantChannel = `-- name: GetAssistantChannel :one
SELECT id, name, project_id, created_at, kind FROM channels WHERE kind = 'assistant' ORDER BY created_at ASC, id ASC LIMIT 1
`

// The conversation, found without the state row. The oldest wins: if a second
// one was ever created, the first is the one the history is in.
func (q *Queries) GetAssistantChannel(ctx context.Context) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getAssistantChannel)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.CreatedAt,
		&i.Kind,
	)
	return i, err
}

const getAssistantFollow = `-- name: GetAssistantFollow :one
SELECT session_id, since, briefed, source FROM assistant_follows WHERE session_id = ?
`

func (q *Queries) GetAssistantFollow(ctx context.Context, sessionID string) (AssistantFollow, error) {
	row := q.db.QueryRowContext(ctx, getAssistantFollow, sessionID)
	var i AssistantFollow
	err := row.Scan(
		&i.SessionID,
		&i.Since,
		&i.Briefed,
		&i.Source,
	)
	return i, err
}

const getAssistantPolicy = `-- name: GetAssistantPolicy :one
SELECT id, name, text, enabled, budget_in_flight, budget_per_day, last_fired_at, created_at, updated_at FROM assistant_policies WHERE id = ?
`

func (q *Queries) GetAssistantPolicy(ctx context.Context, id string) (AssistantPolicy, error) {
	row := q.db.QueryRowContext(ctx, getAssistantPolicy, id)
	var i AssistantPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Text,
		&i.Enabled,
		&i.BudgetInFlight,
		&i.BudgetPerDay,
		&i.LastFiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssistantProposal = `-- name: GetAssistantProposal :one
SELECT id, created_at, verb, session_id, project_id, channel_id, args, rationale, evidence, status, decided_at, decided_via, outcome, expires_at FROM assistant_proposals WHERE id = ?
`

func (q *Queries) GetAssistantProposal(ctx context.Context, id string) (AssistantProposal, error) {
	row := q.db.QueryRowContext(ctx, getAssistantProposal, id)
	var i AssistantProposal
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Verb,
		&i.SessionID,
		&i.ProjectID,
		&i.ChannelID,
		&i.Args,
		&i.Rationale,
		&i.Evidence,
		&i.Status,
		&i.DecidedAt,
		&i.DecidedVia,
		&i.Outcome,
		&i.ExpiresAt,
	)
	return i, err
}

const getAssistantState = `-- name: GetAssistantState :one

SELECT id, channel_id, model, last_heartbeat_at, last_digest_at, surface_marks, created_at, updated_at FROM assistant_state WHERE id = 1
`

// The assistant's state, journal, follow list and conversation channel.
// See docs/assistant.md and migration 056.
//
// Keep this file ASCII. sqlc expands `SELECT *` by byte offset, so one
// multi-byte character shifts those offsets and corrupts the generated code
// for LATER queries.
func (q *Queries) GetAssistantState(ctx context.Context) (AssistantState, error) {
	row := q.db.QueryRowContext(ctx, getAssistantState)
	var i AssistantState
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Model,
		&i.LastHeartbeatAt,
		&i.LastDigestAt,
		&i.SurfaceMarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenAssistantProposalFor = `-- name: GetOpenAssistantProposalFor :one
SELECT id, created_at, verb, session_id, project_id, channel_id, args, rationale, evidence, status, decided_at, decided_via, outcome, expires_at FROM assistant_proposals
WHERE status = 'open'
  AND verb = ?1
  AND session_id = ?2
  AND channel_id = ?3
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetOpenAssistantProposalForParams struct {
	Verb      string `json:"verb"`
	SessionID string `json:"session_id"`
	ChannelID string `json:"channel_id"`
}

// One open proposal for the same verb and the same target, if there is one.
//
// Asking twice for the same thing is one card, not two: a second row would
// give the operator two buttons for one decision, and accepting either would
// leave the other pointing at work already done.
func (q *Queries) GetOpenAssistantProposalFor(ctx context.Context, arg GetOpenAssistantProposalForParams) (AssistantProposal, error) {
	row := q.db.QueryRowContext(ctx, getOpenAssistantProposalFor, arg.Verb, arg.SessionID, arg.ChannelID)
	var i AssistantProposal
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Verb,
		&i.SessionID,
		&i.ProjectID,
		&i.ChannelID,
		&i.Args,
		&i.Rationale,
		&i.Evidence,
		&i.Status,
		&i.DecidedAt,
		&i.DecidedVia,
		&i.Outcome,
		&i.ExpiresAt,
	)
	return i, err
}

const insertAssistantJournalEntry = `-- name: InsertAssistantJournalEntry :one
INSERT INTO assistant_journal (at, kind, session_id, project_id, summary, payload, untrusted, notable)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, at, kind, session_id, project_id, summary, payload, untrusted, notable, seen_by, created_at
`

type InsertAssistantJournalEntryParams struct {
	At        string `json:"at"`
	Kind      string `json:"kind"`
	SessionID string `json:"session_id"`
	ProjectID string `json:"project_id"`
	Summary   string `json:"summary"`
	Payload   string `json:"payload"`
	Untrusted int64  `json:"untrusted"`
	Notable   int64  `json:"notable"`
}

func (q *Queries) InsertAssistantJournalEntry(ctx context.Context, arg InsertAssistantJournalEntryParams) (AssistantJournal, error) {
	row := q.db.QueryRowContext(ctx, insertAssistantJournalEntry,
		arg.At,
		arg.Kind,
		arg.SessionID,
		arg.ProjectID,
		arg.Summary,
		arg.Payload,
		arg.Untrusted,
		arg.Notable,
	)
	var i AssistantJournal
	err := row.Scan(
		&i.ID,
		&i.At,
		&i.Kind,
		&i.SessionID,
		&i.ProjectID,
		&i.Summary,
		&i.Payload,
		&i.Untrusted,
		&i.Notable,
		&i.SeenBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertAssistantMessage = `-- name: InsertAssistantMessage :one
INSERT INTO messages (id, channel_id, sender_type, sender_id, sender_name, content, message_type, metadata, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, channel_id, sender_type, sender_id, sender_name, content, message_type, metadata, created_at
`

type InsertAssistantMessageParams struct {
	ID          string `json:"id"`
	ChannelID   string `json:"channel_id"`
	SenderType  string `json:"sender_type"`
	SenderID    string `json:"sender_id"`
	SenderName  string `json:"sender_name"`
	Content     string `json:"content"`
	MessageType string `json:"message_type"`
	Metadata    string `json:"metadata"`
	CreatedAt   string `json:"created_at"`
}

// One message of the conversation.
//
// Its own insert rather than InsertMessage because created_at is passed IN.
// The table's default stamps milliseconds, and an ask and its reply can land
// in the same millisecond -- at which point the only tiebreak left is the
// uuid, and the two read back in no order at all. A fixed-width nanosecond
// stamp sorts lexicographically, which for this column is the only kind of
// sorting there is. Nothing else writes to an assistant channel, so the
// sharper format is consistent within the timeline that reads it.
func (q *Queries) InsertAssistantMessage(ctx context.Context, arg InsertAssistantMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, insertAssistantMessage,
		arg.ID,
		arg.ChannelID,
		arg.SenderType,
		arg.SenderID,
		arg.SenderName,
		arg.Content,
		arg.MessageType,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.SenderType,
		&i.SenderID,
		&i.SenderName,
		&i.Content,
		&i.MessageType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const insertAssistantProposal = `-- name: InsertAssistantProposal :one

INSERT INTO assistant_proposals (
    id, created_at, verb, session_id, project_id, channel_id,
    args, rationale, evidence, status, expires_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'open', ?)
RETURNING id, created_at, verb, session_id, project_id, channel_id, args, rationale, evidence, status, decided_at, decided_via, outcome, expires_at
`

type InsertAssistantProposalParams struct {
	ID        string `json:"id"`
	CreatedAt string `json:"created_at"`
	Verb      string `json:"verb"`
	SessionID string `json:"session_id"`
	ProjectID string `json:"project_id"`
	ChannelID string `json:"channel_id"`
	Args      string `json:"args"`
	Rationale string `json:"rationale"`
	Evidence  string `json:"evidence"`
	ExpiresAt string `json:"expires_at"`
}

// Proposals: the uncontained tier's card, and the record of its yes or no.
// See docs/assistant.md's M3 contract and migration 057.
func (q *Queries) InsertAssistantProposal(ctx context.Context, arg InsertAssistantProposalParams) (AssistantProposal, error) {
	row := q.db.QueryRowContext(ctx, insertAssistantProposal,
		arg.ID,
		arg.CreatedAt,
		arg.Verb,
		arg.SessionID,
		arg.ProjectID,
		arg.ChannelID,
		arg.Args,
		arg.Rationale,
		arg.Evidence,
		arg.ExpiresAt,
	)
	var i AssistantProposal
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Verb,
		&i.SessionID,
		&i.ProjectID,
		&i.ChannelID,
		&i.Args,
		&i.Rationale,
		&i.Evidence,
		&i.Status,
		&i.DecidedAt,
		&i.DecidedVia,
		&i.Outcome,
		&i.ExpiresAt,
	)
	return i, err
}

const listAssistantFollows = `-- name: ListAssistantFollows :many
SELECT session_id, since, briefed, source FROM assistant_follows ORDER BY since ASC
`

func (q *Queries) ListAssistantFollows(ctx context.Context) ([]AssistantFollow, error) {
	rows, err := q.db.QueryContext(ctx, listAssistantFollows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistantFollow{}
	for rows.Next() {
		var i AssistantFollow
		if err := rows.Scan(
			&i.SessionID,
			&i.Since,
			&i.Briefed,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistantJournalSince = `-- name: ListAssistantJournalSince :many
SELECT id, at, kind, session_id, project_id, summary, payload, untrusted, notable, seen_by, created_at FROM assistant_journal
WHERE at >= ?1
ORDER BY at DESC, id DESC
LIMIT ?2
`

type ListAssistantJournalSinceParams struct {
	Since string `json:"since"`
	Lim   int64  `json:"lim"`
}

func (q *Queries) ListAssistantJournalSince(ctx context.Context, arg ListAssistantJournalSinceParams) ([]AssistantJournal, error) {
	rows, err := q.db.QueryContext(ctx, listAssistantJournalSince, arg.Since, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistantJournal{}
	for rows.Next() {
		var i AssistantJournal
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Kind,
			&i.SessionID,
			&i.ProjectID,
			&i.Summary,
			&i.Payload,
			&i.Untrusted,
			&i.Notable,
			&i.SeenBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistantJournalUnseen = `-- name: ListAssistantJournalUnseen :many
SELECT id, at, kind, session_id, project_id, summary, payload, untrusted, notable, seen_by, created_at FROM assistant_journal
WHERE json_extract(seen_by, '$.' || ?1) IS NULL
  AND kind != 'heartbeat'
ORDER BY at DESC, id DESC
LIMIT ?2
`

type ListAssistantJournalUnseenParams struct {
	Surface sql.NullString `json:"surface"`
	Lim     int64          `json:"lim"`
}

// What a surface has missed. 'heartbeat' rows are left out, for the same reason
// the digest and the head's news leave them out: a tick that woke up, looked and
// decided nothing is the assistant's own bookkeeping, and what it DID has its
// own entry beside it. They stay in ListAssistantJournalSince, which is the
// journal page and the audit trail for every model the heartbeat paid for.
func (q *Queries) ListAssistantJournalUnseen(ctx context.Context, arg ListAssistantJournalUnseenParams) ([]AssistantJournal, error) {
	rows, err := q.db.QueryContext(ctx, listAssistantJournalUnseen, arg.Surface, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistantJournal{}
	for rows.Next() {
		var i AssistantJournal
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Kind,
			&i.SessionID,
			&i.ProjectID,
			&i.Summary,
			&i.Payload,
			&i.Untrusted,
			&i.Notable,
			&i.SeenBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistantMessagesBefore = `-- name: ListAssistantMessagesBefore :many
SELECT id, channel_id, sender_type, sender_id, sender_name, content, message_type, metadata, created_at FROM messages
WHERE channel_id = ?1
  AND (?2 = '' OR (created_at, id) < (?2, ?3))
ORDER BY created_at DESC, id DESC
LIMIT ?4
`

type ListAssistantMessagesBeforeParams struct {
	ChannelID string      `json:"channel_id"`
	BeforeAt  interface{} `json:"before_at"`
	BeforeID  string      `json:"before_id"`
	Lim       int64       `json:"lim"`
}

// One page of the conversation, newest first. An empty `before` starts at the
// newest message; otherwise it is a created_at cursor.
//
// rowid breaks the tie, not id. messages.created_at has millisecond precision
// and a message's id is a uuid, so two turns written in the same millisecond --
// an ask and a mirrored reply -- would come back in uuid order, which is to say
// in no order. rowid is insertion order, which is the order they were said in.
func (q *Queries) ListAssistantMessagesBefore(ctx context.Context, arg ListAssistantMessagesBeforeParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listAssistantMessagesBefore,
		arg.ChannelID,
		arg.BeforeAt,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.SenderType,
			&i.SenderID,
			&i.SenderName,
			&i.Content,
			&i.MessageType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistantMessagesSince = `-- name: ListAssistantMessagesSince :many
SELECT id, channel_id, sender_type, sender_id, sender_name, content, message_type, metadata, created_at FROM messages
WHERE channel_id = ?1 AND created_at > ?2
ORDER BY created_at ASC, id ASC
LIMIT ?3
`

type ListAssistantMessagesSinceParams struct {
	ChannelID string `json:"channel_id"`
	Since     string `json:"since"`
	Lim       int64  `json:"lim"`
}

// What has been said in the conversation since a surface last looked, oldest
// first: this is read to be pasted into a preamble or a strip, in order.
func (q *Queries) ListAssistantMessagesSince(ctx context.Context, arg ListAssistantMessagesSinceParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listAssistantMessagesSince, arg.ChannelID, arg.Since, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.SenderType,
			&i.SenderID,
			&i.SenderName,
			&i.Content,
			&i.MessageType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistantPolicies = `-- name: ListAssistantPolicies :many

SELECT id, name, text, enabled, budget_in_flight, budget_per_day, last_fired_at, created_at, updated_at FROM assistant_policies ORDER BY name ASC, id ASC
`

// Standing instructions and the heartbeat's mark (docs/assistant.md, the M4
// contract, and migration 059).
// Name order, so the list a person reads and the list the heartbeat reads are
// in the same order. The id breaks a tie between two policies named the same.
func (q *Queries) ListAssistantPolicies(ctx context.Context) ([]AssistantPolicy, error) {
	rows, err := q.db.QueryContext(ctx, listAssistantPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistantPolicy{}
	for rows.Next() {
		var i AssistantPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Text,
			&i.Enabled,
			&i.BudgetInFlight,
			&i.BudgetPerDay,
			&i.LastFiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistantProposals = `-- name: ListAssistantProposals :many
SELECT id, created_at, verb, session_id, project_id, channel_id, args, rationale, evidence, status, decided_at, decided_via, outcome, expires_at FROM assistant_proposals
ORDER BY (status != 'open'), created_at DESC, id DESC
LIMIT ?1
`

// Open first, then whatever was decided, newest first within each half. A
// surface renders the open ones as cards and the rest as history, and one read
// answers both.
func (q *Queries) ListAssistantProposals(ctx context.Context, lim int64) ([]AssistantProposal, error) {
	rows, err := q.db.QueryContext(ctx, listAssistantProposals, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistantProposal{}
	for rows.Next() {
		var i AssistantProposal
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Verb,
			&i.SessionID,
			&i.ProjectID,
			&i.ChannelID,
			&i.Args,
			&i.Rationale,
			&i.Evidence,
			&i.Status,
			&i.DecidedAt,
			&i.DecidedVia,
			&i.Outcome,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionOutcomeBaseline = `-- name: ListSessionOutcomeBaseline :many
SELECT id, worktree_merged, archived_at FROM sessions
`

type ListSessionOutcomeBaselineRow struct {
	ID             string         `json:"id"`
	WorktreeMerged int64          `json:"worktree_merged"`
	ArchivedAt     sql.NullString `json:"archived_at"`
}

// The session.state observer's baseline: what every session's two outcome
// facts already were before the observer started watching. A push is a whole
// snapshot, not a transition, so without this the first push for a session
// archived last month reads as news -- and on the first boot with the
// assistant on, that was one entry per archived session ever.
func (q *Queries) ListSessionOutcomeBaseline(ctx context.Context) ([]ListSessionOutcomeBaselineRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionOutcomeBaseline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionOutcomeBaselineRow{}
	for rows.Next() {
		var i ListSessionOutcomeBaselineRow
		if err := rows.Scan(&i.ID, &i.WorktreeMerged, &i.ArchivedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAssistantJournalSeenThrough = `-- name: MarkAssistantJournalSeenThrough :exec
UPDATE assistant_journal
SET seen_by = json_set(seen_by, '$.' || ?1, ?2)
WHERE json_extract(seen_by, '$.' || ?1) IS NULL
  AND (at < ?3
       OR (at = ?3 AND id <= ?4))
`

type MarkAssistantJournalSeenThroughParams struct {
	Surface   sql.NullString `json:"surface"`
	At        interface{}    `json:"at"`
	ThroughAt string         `json:"through_at"`
	ThroughID int64          `json:"through_id"`
}

// Stamps everything this surface has now been shown, THROUGH the newest row it
// was handed.
//
// Through a boundary rather than row by row, because a look is bounded and the
// journal is not: stamping only the rows returned left a backlog larger than
// one page unseen, so the next look answered with the next fifty OLDER entries
// and announced last week as news. The boundary is the newest row of the look,
// so what it means is "you are caught up to here" -- which is the only reading
// that is monotonic in time.
//
// Already-stamped rows are left alone: a second surface's mark must not be
// rewritten, and re-stamping the whole history on every look would be an
// UPDATE over the table.
func (q *Queries) MarkAssistantJournalSeenThrough(ctx context.Context, arg MarkAssistantJournalSeenThroughParams) error {
	_, err := q.db.ExecContext(ctx, markAssistantJournalSeenThrough,
		arg.Surface,
		arg.At,
		arg.ThroughAt,
		arg.ThroughID,
	)
	return err
}

const setAssistantChannel = `-- name: SetAssistantChannel :exec
INSERT INTO assistant_state (id, channel_id, created_at, updated_at)
VALUES (1, ?1, ?2, ?2)
ON CONFLICT(id) DO UPDATE SET
  channel_id = excluded.channel_id,
  updated_at = excluded.updated_at
`

type SetAssistantChannelParams struct {
	ChannelID string `json:"channel_id"`
	Now       string `json:"now"`
}

func (q *Queries) SetAssistantChannel(ctx context.Context, arg SetAssistantChannelParams) error {
	_, err := q.db.ExecContext(ctx, setAssistantChannel, arg.ChannelID, arg.Now)
	return err
}

const setAssistantDigestAt = `-- name: SetAssistantDigestAt :exec
INSERT INTO assistant_state (id, last_digest_at, created_at, updated_at)
VALUES (1, ?1, ?2, ?2)
ON CONFLICT(id) DO UPDATE SET
  last_digest_at = excluded.last_digest_at,
  updated_at = excluded.updated_at
`

type SetAssistantDigestAtParams struct {
	LastDigestAt string `json:"last_digest_at"`
	Now          string `json:"now"`
}

// Stamps the window the last digest covered, so the next one starts where it
// finished. Written only by Digest.
func (q *Queries) SetAssistantDigestAt(ctx context.Context, arg SetAssistantDigestAtParams) error {
	_, err := q.db.ExecContext(ctx, setAssistantDigestAt, arg.LastDigestAt, arg.Now)
	return err
}

const setAssistantFollowBriefed = `-- name: SetAssistantFollowBriefed :exec
UPDATE assistant_follows SET briefed = ? WHERE session_id = ?
`

type SetAssistantFollowBriefedParams struct {
	Briefed   int64  `json:"briefed"`
	SessionID string `json:"session_id"`
}

func (q *Queries) SetAssistantFollowBriefed(ctx context.Context, arg SetAssistantFollowBriefedParams) error {
	_, err := q.db.ExecContext(ctx, setAssistantFollowBriefed, arg.Briefed, arg.SessionID)
	return err
}

const setAssistantHeartbeatAt = `-- name: SetAssistantHeartbeatAt :exec
INSERT INTO assistant_state (id, last_heartbeat_at, created_at, updated_at)
VALUES (1, ?1, ?2, ?2)
ON CONFLICT(id) DO UPDATE SET
  last_heartbeat_at = excluded.last_heartbeat_at,
  updated_at = excluded.updated_at
`

type SetAssistantHeartbeatAtParams struct {
	LastHeartbeatAt string `json:"last_heartbeat_at"`
	Now             string `json:"now"`
}

// The heartbeat's mark: when the last tick measured from. Stamped by every
// tick, including the ones that ran no model at all.
func (q *Queries) SetAssistantHeartbeatAt(ctx context.Context, arg SetAssistantHeartbeatAtParams) error {
	_, err := q.db.ExecContext(ctx, setAssistantHeartbeatAt, arg.LastHeartbeatAt, arg.Now)
	return err
}

const setAssistantModel = `-- name: SetAssistantModel :exec
INSERT INTO assistant_state (id, model, created_at, updated_at)
VALUES (1, ?1, ?2, ?2)
ON CONFLICT(id) DO UPDATE SET
  model = excluded.model,
  updated_at = excluded.updated_at
`

type SetAssistantModelParams struct {
	Model string `json:"model"`
	Now   string `json:"now"`
}

func (q *Queries) SetAssistantModel(ctx context.Context, arg SetAssistantModelParams) error {
	_, err := q.db.ExecContext(ctx, setAssistantModel, arg.Model, arg.Now)
	return err
}

const setAssistantSurfaceMark = `-- name: SetAssistantSurfaceMark :exec
INSERT INTO assistant_state (id, surface_marks, created_at, updated_at)
VALUES (1, json_set('{}', '$.' || ?1, ?2), ?3, ?3)
ON CONFLICT(id) DO UPDATE SET
  surface_marks = json_set(assistant_state.surface_marks, '$.' || ?1, ?2),
  updated_at = excluded.updated_at
`

type SetAssistantSurfaceMarkParams struct {
	Surface sql.NullString `json:"surface"`
	At      interface{}    `json:"at"`
	Now     string         `json:"now"`
}

// Records that a surface has looked. json_set on the existing object rather
// than a rewrite, so two surfaces cannot overwrite each other's mark.
//
// The DO UPDATE clause uses ?1/?2 rather than sqlc.arg(): sqlc does NOT rewrite
// a named parameter inside an upsert's DO UPDATE, it copies the text through,
// and `sqlc.arg(surface)` reaching SQLite is a runtime error in a statement
// whose failure this code only logs. The numbers are the same parameters the
// VALUES clause names.
func (q *Queries) SetAssistantSurfaceMark(ctx context.Context, arg SetAssistantSurfaceMarkParams) error {
	_, err := q.db.ExecContext(ctx, setAssistantSurfaceMark, arg.Surface, arg.At, arg.Now)
	return err
}

const touchAssistantPolicy = `-- name: TouchAssistantPolicy :exec
UPDATE assistant_policies
SET last_fired_at = ?1, updated_at = ?2
WHERE id = ?3
`

type TouchAssistantPolicyParams struct {
	LastFiredAt string `json:"last_fired_at"`
	Now         string `json:"now"`
	ID          string `json:"id"`
}

// When the heartbeat last acted under this policy. Bookkeeping the operator
// reads, never a budget: what a budget counts is journal entries, which an
// edit cannot rewrite.
func (q *Queries) TouchAssistantPolicy(ctx context.Context, arg TouchAssistantPolicyParams) error {
	_, err := q.db.ExecContext(ctx, touchAssistantPolicy, arg.LastFiredAt, arg.Now, arg.ID)
	return err
}

const upsertAssistantFollow = `-- name: UpsertAssistantFollow :exec
INSERT INTO assistant_follows (session_id, since, briefed, source)
VALUES (?, ?, 0, ?)
ON CONFLICT(session_id) DO UPDATE SET source = excluded.source
`

type UpsertAssistantFollowParams struct {
	SessionID string `json:"session_id"`
	Since     string `json:"since"`
	Source    string `json:"source"`
}

func (q *Queries) UpsertAssistantFollow(ctx context.Context, arg UpsertAssistantFollowParams) error {
	_, err := q.db.ExecContext(ctx, upsertAssistantFollow, arg.SessionID, arg.Since, arg.Source)
	return err
}

const upsertAssistantPolicy = `-- name: UpsertAssistantPolicy :one
INSERT INTO assistant_policies (
    id, name, text, enabled, budget_in_flight, budget_per_day, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, ?7
)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  text = excluded.text,
  enabled = excluded.enabled,
  budget_in_flight = excluded.budget_in_flight,
  budget_per_day = excluded.budget_per_day,
  updated_at = excluded.updated_at
RETURNING id, name, text, enabled, budget_in_flight, budget_per_day, last_fired_at, created_at, updated_at
`

type UpsertAssistantPolicyParams struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	Text           string `json:"text"`
	Enabled        int64  `json:"enabled"`
	BudgetInFlight int64  `json:"budget_in_flight"`
	BudgetPerDay   int64  `json:"budget_per_day"`
	Now            string `json:"now"`
}

// One statement for a new policy and an edit, because the client sends the
// whole row either way: a policy is one form with a Save button, and a
// partial update would need a field-by-field patch nobody asked for.
// created_at is left alone on an edit, so a row keeps the day it was written.
func (q *Queries) UpsertAssistantPolicy(ctx context.Context, arg UpsertAssistantPolicyParams) (AssistantPolicy, error) {
	row := q.db.QueryRowContext(ctx, upsertAssistantPolicy,
		arg.ID,
		arg.Name,
		arg.Text,
		arg.Enabled,
		arg.BudgetInFlight,
		arg.BudgetPerDay,
		arg.Now,
	)
	var i AssistantPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Text,
		&i.Enabled,
		&i.BudgetInFlight,
		&i.BudgetPerDay,
		&i.LastFiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
