// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package store

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthSession = `-- name: CreateAuthSession :exec
INSERT INTO auth_sessions (token, user_id, expires_at) VALUES (?, ?, ?)
`

type CreateAuthSessionParams struct {
	Token     string `json:"token"`
	UserID    string `json:"user_id"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) error {
	_, err := q.db.ExecContext(ctx, createAuthSession, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const createInviteToken = `-- name: CreateInviteToken :exec
INSERT INTO invite_tokens (token, created_by, expires_at) VALUES (?, ?, ?)
`

type CreateInviteTokenParams struct {
	Token     string `json:"token"`
	CreatedBy string `json:"created_by"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) CreateInviteToken(ctx context.Context, arg CreateInviteTokenParams) error {
	_, err := q.db.ExecContext(ctx, createInviteToken, arg.Token, arg.CreatedBy, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, display_name, is_admin) VALUES (?, ?, ?) RETURNING id, display_name, is_admin, created_at
`

type CreateUserParams struct {
	ID          string `json:"id"`
	DisplayName string `json:"display_name"`
	IsAdmin     int64  `json:"is_admin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.DisplayName, arg.IsAdmin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const createWebAuthnCredential = `-- name: CreateWebAuthnCredential :exec
INSERT INTO webauthn_credentials (id, user_id, public_key, attestation_type, aaguid, sign_count, transport)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateWebAuthnCredentialParams struct {
	ID              string `json:"id"`
	UserID          string `json:"user_id"`
	PublicKey       []byte `json:"public_key"`
	AttestationType string `json:"attestation_type"`
	Aaguid          []byte `json:"aaguid"`
	SignCount       int64  `json:"sign_count"`
	Transport       string `json:"transport"`
}

func (q *Queries) CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) error {
	_, err := q.db.ExecContext(ctx, createWebAuthnCredential,
		arg.ID,
		arg.UserID,
		arg.PublicKey,
		arg.AttestationType,
		arg.Aaguid,
		arg.SignCount,
		arg.Transport,
	)
	return err
}

const deleteAuthSession = `-- name: DeleteAuthSession :exec
DELETE FROM auth_sessions WHERE token = ?
`

func (q *Queries) DeleteAuthSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthSession, token)
	return err
}

const deleteExpiredAuthSessions = `-- name: DeleteExpiredAuthSessions :exec
DELETE FROM auth_sessions WHERE expires_at <= strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
`

func (q *Queries) DeleteExpiredAuthSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAuthSessions)
	return err
}

const getAuthSession = `-- name: GetAuthSession :one
SELECT s.token, s.user_id, s.expires_at, s.created_at,
       u.display_name, u.is_admin
FROM auth_sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token = ? AND s.expires_at > strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
`

type GetAuthSessionRow struct {
	Token       string `json:"token"`
	UserID      string `json:"user_id"`
	ExpiresAt   string `json:"expires_at"`
	CreatedAt   string `json:"created_at"`
	DisplayName string `json:"display_name"`
	IsAdmin     int64  `json:"is_admin"`
}

func (q *Queries) GetAuthSession(ctx context.Context, token string) (GetAuthSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getAuthSession, token)
	var i GetAuthSessionRow
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.DisplayName,
		&i.IsAdmin,
	)
	return i, err
}

const getCredentialByID = `-- name: GetCredentialByID :one
SELECT id, user_id, public_key, attestation_type, aaguid, sign_count, transport, created_at FROM webauthn_credentials WHERE id = ?
`

func (q *Queries) GetCredentialByID(ctx context.Context, id string) (WebauthnCredential, error) {
	row := q.db.QueryRowContext(ctx, getCredentialByID, id)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Aaguid,
		&i.SignCount,
		&i.Transport,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteToken = `-- name: GetInviteToken :one
SELECT token, created_by, expires_at, used_by, used_at, created_at FROM invite_tokens WHERE token = ? AND used_by IS NULL AND expires_at > strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
`

func (q *Queries) GetInviteToken(ctx context.Context, token string) (InviteToken, error) {
	row := q.db.QueryRowContext(ctx, getInviteToken, token)
	var i InviteToken
	err := row.Scan(
		&i.Token,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedBy,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, display_name, is_admin, created_at FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const listCredentialsByUser = `-- name: ListCredentialsByUser :many
SELECT id, user_id, public_key, attestation_type, aaguid, sign_count, transport, created_at FROM webauthn_credentials WHERE user_id = ?
`

func (q *Queries) ListCredentialsByUser(ctx context.Context, userID string) ([]WebauthnCredential, error) {
	rows, err := q.db.QueryContext(ctx, listCredentialsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebauthnCredential{}
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PublicKey,
			&i.AttestationType,
			&i.Aaguid,
			&i.SignCount,
			&i.Transport,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInviteTokens = `-- name: ListInviteTokens :many
SELECT token, created_by, expires_at, used_by, used_at, created_at FROM invite_tokens WHERE created_by = ? ORDER BY created_at DESC
`

func (q *Queries) ListInviteTokens(ctx context.Context, createdBy string) ([]InviteToken, error) {
	rows, err := q.db.QueryContext(ctx, listInviteTokens, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InviteToken{}
	for rows.Next() {
		var i InviteToken
		if err := rows.Scan(
			&i.Token,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.UsedBy,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredentialSignCount = `-- name: UpdateCredentialSignCount :exec
UPDATE webauthn_credentials SET sign_count = ? WHERE id = ?
`

type UpdateCredentialSignCountParams struct {
	SignCount int64  `json:"sign_count"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateCredentialSignCount(ctx context.Context, arg UpdateCredentialSignCountParams) error {
	_, err := q.db.ExecContext(ctx, updateCredentialSignCount, arg.SignCount, arg.ID)
	return err
}

const useInviteToken = `-- name: UseInviteToken :exec
UPDATE invite_tokens SET used_by = ?, used_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE token = ?
`

type UseInviteTokenParams struct {
	UsedBy sql.NullString `json:"used_by"`
	Token  string         `json:"token"`
}

func (q *Queries) UseInviteToken(ctx context.Context, arg UseInviteTokenParams) error {
	_, err := q.db.ExecContext(ctx, useInviteToken, arg.UsedBy, arg.Token)
	return err
}
