// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: brain_jobs.sql

package store

import (
	"context"
)

const createBrainJob = `-- name: CreateBrainJob :one
INSERT INTO brain_jobs (id, kind, scope, payload, attempts) VALUES (?, ?, ?, ?, ?) RETURNING id, kind, scope, payload, attempts, last_error, created_at
`

type CreateBrainJobParams struct {
	ID       string `json:"id"`
	Kind     string `json:"kind"`
	Scope    string `json:"scope"`
	Payload  string `json:"payload"`
	Attempts int64  `json:"attempts"`
}

func (q *Queries) CreateBrainJob(ctx context.Context, arg CreateBrainJobParams) (BrainJob, error) {
	row := q.db.QueryRowContext(ctx, createBrainJob,
		arg.ID,
		arg.Kind,
		arg.Scope,
		arg.Payload,
		arg.Attempts,
	)
	var i BrainJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Scope,
		&i.Payload,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBrainJob = `-- name: DeleteBrainJob :exec
DELETE FROM brain_jobs WHERE id = ?
`

func (q *Queries) DeleteBrainJob(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBrainJob, id)
	return err
}

const listBrainJobs = `-- name: ListBrainJobs :many
SELECT id, kind, scope, payload, attempts, last_error, created_at FROM brain_jobs ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListBrainJobs(ctx context.Context) ([]BrainJob, error) {
	rows, err := q.db.QueryContext(ctx, listBrainJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BrainJob{}
	for rows.Next() {
		var i BrainJob
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Scope,
			&i.Payload,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBrainJobAttempts = `-- name: UpdateBrainJobAttempts :exec
UPDATE brain_jobs SET attempts = ?, last_error = ? WHERE id = ?
`

type UpdateBrainJobAttemptsParams struct {
	Attempts  int64  `json:"attempts"`
	LastError string `json:"last_error"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateBrainJobAttempts(ctx context.Context, arg UpdateBrainJobAttemptsParams) error {
	_, err := q.db.ExecContext(ctx, updateBrainJobAttempts, arg.Attempts, arg.LastError, arg.ID)
	return err
}
