// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channels.sql

package store

import (
	"context"
	"database/sql"
)

const addChannelMember = `-- name: AddChannelMember :exec
INSERT INTO channel_members (channel_id, session_id, role) VALUES (?, ?, ?)
ON CONFLICT (channel_id, session_id) DO UPDATE SET role = excluded.role
`

type AddChannelMemberParams struct {
	ChannelID string `json:"channel_id"`
	SessionID string `json:"session_id"`
	Role      string `json:"role"`
}

func (q *Queries) AddChannelMember(ctx context.Context, arg AddChannelMemberParams) error {
	_, err := q.db.ExecContext(ctx, addChannelMember, arg.ChannelID, arg.SessionID, arg.Role)
	return err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (id, name, project_id) VALUES (?, ?, ?) RETURNING id, name, project_id, created_at
`

type CreateChannelParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createChannel, arg.ID, arg.Name, arg.ProjectID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels WHERE id = ?
`

func (q *Queries) DeleteChannel(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteChannel, id)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT id, name, project_id, created_at FROM channels WHERE id = ?
`

func (q *Queries) GetChannel(ctx context.Context, id string) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentMessagesByChannel = `-- name: ListAgentMessagesByChannel :many
SELECT se.id, se.session_id, se.turn_index, se.seq, se.type, se.data, se.created_at, se.message_id FROM session_events se
JOIN channel_members cm ON cm.session_id = se.session_id
WHERE cm.channel_id = ? AND se.type = 'agent_message'
ORDER BY se.created_at ASC
`

func (q *Queries) ListAgentMessagesByChannel(ctx context.Context, channelID string) ([]SessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentMessagesByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionEvent{}
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TurnIndex,
			&i.Seq,
			&i.Type,
			&i.Data,
			&i.CreatedAt,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelMemberSessions = `-- name: ListChannelMemberSessions :many
SELECT s.id, s.project_id, s.name, s.work_dir, s.worktree_path, s.worktree_branch, s.state, s.created_at, s.updated_at, s.claude_session_id, s.worktree_base_sha, s.model, s.worktree_merged, s.permission_mode, s.auto_approve, s.pr_url, s.effort, s.max_budget, s.max_turns, s.last_query_at, s.completed_at, s.behavior_presets, s.channel_id, s.channel_role, s.auto_approve_mode, s.agent_profile_id, s.parent_session_id, cm.role AS member_role FROM sessions s
JOIN channel_members cm ON cm.session_id = s.id
WHERE cm.channel_id = ?
ORDER BY cm.joined_at ASC
`

type ListChannelMemberSessionsRow struct {
	ID              string         `json:"id"`
	ProjectID       string         `json:"project_id"`
	Name            string         `json:"name"`
	WorkDir         string         `json:"work_dir"`
	WorktreePath    sql.NullString `json:"worktree_path"`
	WorktreeBranch  sql.NullString `json:"worktree_branch"`
	State           string         `json:"state"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
	ClaudeSessionID sql.NullString `json:"claude_session_id"`
	WorktreeBaseSha sql.NullString `json:"worktree_base_sha"`
	Model           string         `json:"model"`
	WorktreeMerged  int64          `json:"worktree_merged"`
	PermissionMode  string         `json:"permission_mode"`
	AutoApprove     int64          `json:"auto_approve"`
	PrUrl           string         `json:"pr_url"`
	Effort          string         `json:"effort"`
	MaxBudget       float64        `json:"max_budget"`
	MaxTurns        int64          `json:"max_turns"`
	LastQueryAt     sql.NullString `json:"last_query_at"`
	CompletedAt     sql.NullString `json:"completed_at"`
	BehaviorPresets string         `json:"behavior_presets"`
	ChannelID       sql.NullString `json:"channel_id"`
	ChannelRole     string         `json:"channel_role"`
	AutoApproveMode string         `json:"auto_approve_mode"`
	AgentProfileID  sql.NullString `json:"agent_profile_id"`
	ParentSessionID sql.NullString `json:"parent_session_id"`
	MemberRole      string         `json:"member_role"`
}

func (q *Queries) ListChannelMemberSessions(ctx context.Context, channelID string) ([]ListChannelMemberSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannelMemberSessions, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelMemberSessionsRow{}
	for rows.Next() {
		var i ListChannelMemberSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.WorkDir,
			&i.WorktreePath,
			&i.WorktreeBranch,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaudeSessionID,
			&i.WorktreeBaseSha,
			&i.Model,
			&i.WorktreeMerged,
			&i.PermissionMode,
			&i.AutoApprove,
			&i.PrUrl,
			&i.Effort,
			&i.MaxBudget,
			&i.MaxTurns,
			&i.LastQueryAt,
			&i.CompletedAt,
			&i.BehaviorPresets,
			&i.ChannelID,
			&i.ChannelRole,
			&i.AutoApproveMode,
			&i.AgentProfileID,
			&i.ParentSessionID,
			&i.MemberRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsByProject = `-- name: ListChannelsByProject :many
SELECT id, name, project_id, created_at FROM channels WHERE project_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListChannelsByProject(ctx context.Context, projectID string) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listChannelsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionChannels = `-- name: ListSessionChannels :many
SELECT cm.channel_id, cm.role FROM channel_members cm WHERE cm.session_id = ?
`

type ListSessionChannelsRow struct {
	ChannelID string `json:"channel_id"`
	Role      string `json:"role"`
}

func (q *Queries) ListSessionChannels(ctx context.Context, sessionID string) ([]ListSessionChannelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionChannels, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionChannelsRow{}
	for rows.Next() {
		var i ListSessionChannelsRow
		if err := rows.Scan(&i.ChannelID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeChannelMember = `-- name: RemoveChannelMember :exec
DELETE FROM channel_members WHERE channel_id = ? AND session_id = ?
`

type RemoveChannelMemberParams struct {
	ChannelID string `json:"channel_id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) RemoveChannelMember(ctx context.Context, arg RemoveChannelMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeChannelMember, arg.ChannelID, arg.SessionID)
	return err
}

const removeSessionFromAllChannels = `-- name: RemoveSessionFromAllChannels :exec
DELETE FROM channel_members WHERE session_id = ?
`

func (q *Queries) RemoveSessionFromAllChannels(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, removeSessionFromAllChannels, sessionID)
	return err
}

const updateChannelName = `-- name: UpdateChannelName :exec
UPDATE channels SET name = ? WHERE id = ?
`

type UpdateChannelNameParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateChannelName(ctx context.Context, arg UpdateChannelNameParams) error {
	_, err := q.db.ExecContext(ctx, updateChannelName, arg.Name, arg.ID)
	return err
}
