// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: events.sql

package store

import (
	"context"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO session_events (session_id, turn_index, seq, type, data) VALUES (?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	SessionID string `json:"session_id"`
	TurnIndex int64  `json:"turn_index"`
	Seq       int64  `json:"seq"`
	Type      string `json:"type"`
	Data      string `json:"data"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.SessionID,
		arg.TurnIndex,
		arg.Seq,
		arg.Type,
		arg.Data,
	)
	return err
}

const listEventsBySession = `-- name: ListEventsBySession :many
SELECT id, session_id, turn_index, seq, type, data, created_at FROM session_events WHERE session_id = ? ORDER BY turn_index, seq
`

func (q *Queries) ListEventsBySession(ctx context.Context, sessionID string) ([]SessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listEventsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionEvent{}
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TurnIndex,
			&i.Seq,
			&i.Type,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxTurnIndex = `-- name: MaxTurnIndex :one
SELECT CAST(COALESCE(MAX(turn_index), -1) AS INTEGER) FROM session_events WHERE session_id = ?
`

func (q *Queries) MaxTurnIndex(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxTurnIndex, sessionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
