// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package store

import (
	"context"
	"database/sql"
)

const allSessionSummaries = `-- name: AllSessionSummaries :many
SELECT
  s.id AS session_id,
  CAST(COALESCE(MAX(e.turn_index) + 1, 0) AS INTEGER) AS turn_count,
  CAST(COALESCE(SUM(CASE WHEN e.type = 'result' THEN json_extract(e.data, '$.cost') ELSE 0 END), 0) AS REAL) AS total_cost
FROM sessions s
LEFT JOIN session_events e ON e.session_id = s.id
GROUP BY s.id
`

type AllSessionSummariesRow struct {
	SessionID string  `json:"session_id"`
	TurnCount int64   `json:"turn_count"`
	TotalCost float64 `json:"total_cost"`
}

func (q *Queries) AllSessionSummaries(ctx context.Context) ([]AllSessionSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, allSessionSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllSessionSummariesRow{}
	for rows.Next() {
		var i AllSessionSummariesRow
		if err := rows.Scan(&i.SessionID, &i.TurnCount, &i.TotalCost); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTurnsBySession = `-- name: CountTurnsBySession :one
SELECT CAST(COALESCE(MAX(turn_index) + 1, 0) AS INTEGER) FROM session_events WHERE session_id = ?
`

func (q *Queries) CountTurnsBySession(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTurnsBySession, sessionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO session_events (session_id, turn_index, seq, type, data) VALUES (?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	SessionID string `json:"session_id"`
	TurnIndex int64  `json:"turn_index"`
	Seq       int64  `json:"seq"`
	Type      string `json:"type"`
	Data      string `json:"data"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.SessionID,
		arg.TurnIndex,
		arg.Seq,
		arg.Type,
		arg.Data,
	)
	return err
}

const insertEventWithMessageID = `-- name: InsertEventWithMessageID :exec
INSERT INTO session_events (session_id, turn_index, seq, type, data, message_id) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertEventWithMessageIDParams struct {
	SessionID string         `json:"session_id"`
	TurnIndex int64          `json:"turn_index"`
	Seq       int64          `json:"seq"`
	Type      string         `json:"type"`
	Data      string         `json:"data"`
	MessageID sql.NullString `json:"message_id"`
}

func (q *Queries) InsertEventWithMessageID(ctx context.Context, arg InsertEventWithMessageIDParams) error {
	_, err := q.db.ExecContext(ctx, insertEventWithMessageID,
		arg.SessionID,
		arg.TurnIndex,
		arg.Seq,
		arg.Type,
		arg.Data,
		arg.MessageID,
	)
	return err
}

const listEventsBySession = `-- name: ListEventsBySession :many
SELECT id, session_id, turn_index, seq, type, data, created_at, message_id FROM session_events WHERE session_id = ? ORDER BY turn_index, seq
`

func (q *Queries) ListEventsBySession(ctx context.Context, sessionID string) ([]SessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listEventsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionEvent{}
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TurnIndex,
			&i.Seq,
			&i.Type,
			&i.Data,
			&i.CreatedAt,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentEventsBySession = `-- name: ListRecentEventsBySession :many
SELECT e.id, e.session_id, e.turn_index, e.seq, e.type, e.data, e.created_at, e.message_id FROM session_events e
WHERE e.session_id = ?
  AND e.turn_index >= (
    SELECT COALESCE(MAX(sub.turn_index), 0) - CAST(? AS INTEGER) + 1
    FROM session_events sub WHERE sub.session_id = e.session_id
  )
ORDER BY e.turn_index, e.seq
`

type ListRecentEventsBySessionParams struct {
	SessionID string `json:"session_id"`
	Column2   int64  `json:"column_2"`
}

func (q *Queries) ListRecentEventsBySession(ctx context.Context, arg ListRecentEventsBySessionParams) ([]SessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listRecentEventsBySession, arg.SessionID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionEvent{}
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TurnIndex,
			&i.Seq,
			&i.Type,
			&i.Data,
			&i.CreatedAt,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxTurnIndex = `-- name: MaxTurnIndex :one
SELECT CAST(COALESCE(MAX(turn_index), -1) AS INTEGER) FROM session_events WHERE session_id = ?
`

func (q *Queries) MaxTurnIndex(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxTurnIndex, sessionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sessionSummariesByProject = `-- name: SessionSummariesByProject :many
SELECT
  s.id AS session_id,
  CAST(COALESCE(MAX(e.turn_index) + 1, 0) AS INTEGER) AS turn_count,
  CAST(COALESCE(SUM(CASE WHEN e.type = 'result' THEN json_extract(e.data, '$.cost') ELSE 0 END), 0) AS REAL) AS total_cost
FROM sessions s
LEFT JOIN session_events e ON e.session_id = s.id
WHERE s.project_id = ?
GROUP BY s.id
`

type SessionSummariesByProjectRow struct {
	SessionID string  `json:"session_id"`
	TurnCount int64   `json:"turn_count"`
	TotalCost float64 `json:"total_cost"`
}

func (q *Queries) SessionSummariesByProject(ctx context.Context, projectID string) ([]SessionSummariesByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, sessionSummariesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionSummariesByProjectRow{}
	for rows.Next() {
		var i SessionSummariesByProjectRow
		if err := rows.Scan(&i.SessionID, &i.TurnCount, &i.TotalCost); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
