// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: machines.sql

package store

import (
	"context"
)

const deleteMachine = `-- name: DeleteMachine :exec
DELETE FROM machines WHERE machine_id = ?
`

func (q *Queries) DeleteMachine(ctx context.Context, machineID string) error {
	_, err := q.db.ExecContext(ctx, deleteMachine, machineID)
	return err
}

const getHostPresentation = `-- name: GetHostPresentation :one
SELECT label, icon FROM host_presentation WHERE id = 1
`

type GetHostPresentationRow struct {
	Label string `json:"label"`
	Icon  string `json:"icon"`
}

func (q *Queries) GetHostPresentation(ctx context.Context) (GetHostPresentationRow, error) {
	row := q.db.QueryRowContext(ctx, getHostPresentation)
	var i GetHostPresentationRow
	err := row.Scan(&i.Label, &i.Icon)
	return i, err
}

const getMachine = `-- name: GetMachine :one
SELECT machine_id, label, base_url, token, added_at, icon, session_id, identity_key FROM machines WHERE machine_id = ?
`

func (q *Queries) GetMachine(ctx context.Context, machineID string) (Machine, error) {
	row := q.db.QueryRowContext(ctx, getMachine, machineID)
	var i Machine
	err := row.Scan(
		&i.MachineID,
		&i.Label,
		&i.BaseUrl,
		&i.Token,
		&i.AddedAt,
		&i.Icon,
		&i.SessionID,
		&i.IdentityKey,
	)
	return i, err
}

const listMachines = `-- name: ListMachines :many
SELECT machine_id, label, base_url, token, added_at, icon, session_id, identity_key FROM machines ORDER BY label
`

func (q *Queries) ListMachines(ctx context.Context) ([]Machine, error) {
	rows, err := q.db.QueryContext(ctx, listMachines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Machine{}
	for rows.Next() {
		var i Machine
		if err := rows.Scan(
			&i.MachineID,
			&i.Label,
			&i.BaseUrl,
			&i.Token,
			&i.AddedAt,
			&i.Icon,
			&i.SessionID,
			&i.IdentityKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setHostPresentation = `-- name: SetHostPresentation :exec
INSERT INTO host_presentation (id, label, icon)
VALUES (1, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  label = excluded.label,
  icon = excluded.icon
`

type SetHostPresentationParams struct {
	Label string `json:"label"`
	Icon  string `json:"icon"`
}

func (q *Queries) SetHostPresentation(ctx context.Context, arg SetHostPresentationParams) error {
	_, err := q.db.ExecContext(ctx, setHostPresentation, arg.Label, arg.Icon)
	return err
}

const updateMachinePresentation = `-- name: UpdateMachinePresentation :execrows
UPDATE machines SET label = ?, icon = ? WHERE machine_id = ?
`

type UpdateMachinePresentationParams struct {
	Label     string `json:"label"`
	Icon      string `json:"icon"`
	MachineID string `json:"machine_id"`
}

func (q *Queries) UpdateMachinePresentation(ctx context.Context, arg UpdateMachinePresentationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMachinePresentation, arg.Label, arg.Icon, arg.MachineID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertMachine = `-- name: UpsertMachine :exec
INSERT INTO machines (machine_id, label, base_url, token, added_at, icon, session_id, identity_key)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(machine_id) DO UPDATE SET
  label = excluded.label,
  base_url = excluded.base_url,
  token = excluded.token,
  icon = excluded.icon,
  session_id = excluded.session_id,
  identity_key = excluded.identity_key
`

type UpsertMachineParams struct {
	MachineID   string `json:"machine_id"`
	Label       string `json:"label"`
	BaseUrl     string `json:"base_url"`
	Token       string `json:"token"`
	AddedAt     string `json:"added_at"`
	Icon        string `json:"icon"`
	SessionID   string `json:"session_id"`
	IdentityKey string `json:"identity_key"`
}

func (q *Queries) UpsertMachine(ctx context.Context, arg UpsertMachineParams) error {
	_, err := q.db.ExecContext(ctx, upsertMachine,
		arg.MachineID,
		arg.Label,
		arg.BaseUrl,
		arg.Token,
		arg.AddedAt,
		arg.Icon,
		arg.SessionID,
		arg.IdentityKey,
	)
	return err
}
