// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: machines.sql

package store

import (
	"context"
)

const deleteMachine = `-- name: DeleteMachine :exec
DELETE FROM machines WHERE machine_id = ?
`

func (q *Queries) DeleteMachine(ctx context.Context, machineID string) error {
	_, err := q.db.ExecContext(ctx, deleteMachine, machineID)
	return err
}

const listMachines = `-- name: ListMachines :many
SELECT machine_id, label, base_url, token, added_at FROM machines ORDER BY label
`

func (q *Queries) ListMachines(ctx context.Context) ([]Machine, error) {
	rows, err := q.db.QueryContext(ctx, listMachines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Machine{}
	for rows.Next() {
		var i Machine
		if err := rows.Scan(
			&i.MachineID,
			&i.Label,
			&i.BaseUrl,
			&i.Token,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMachine = `-- name: UpsertMachine :exec
INSERT INTO machines (machine_id, label, base_url, token, added_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(machine_id) DO UPDATE SET
  label = excluded.label,
  base_url = excluded.base_url,
  token = excluded.token
`

type UpsertMachineParams struct {
	MachineID string `json:"machine_id"`
	Label     string `json:"label"`
	BaseUrl   string `json:"base_url"`
	Token     string `json:"token"`
	AddedAt   string `json:"added_at"`
}

func (q *Queries) UpsertMachine(ctx context.Context, arg UpsertMachineParams) error {
	_, err := q.db.ExecContext(ctx, upsertMachine,
		arg.MachineID,
		arg.Label,
		arg.BaseUrl,
		arg.Token,
		arg.AddedAt,
	)
	return err
}
