// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message_deliveries.sql

package store

import (
	"context"
	"database/sql"
)

const insertMessageDelivery = `-- name: InsertMessageDelivery :exec
INSERT INTO message_deliveries (message_id, recipient_session_id, status)
VALUES (?, ?, ?)
`

type InsertMessageDeliveryParams struct {
	MessageID          string `json:"message_id"`
	RecipientSessionID string `json:"recipient_session_id"`
	Status             string `json:"status"`
}

func (q *Queries) InsertMessageDelivery(ctx context.Context, arg InsertMessageDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, insertMessageDelivery, arg.MessageID, arg.RecipientSessionID, arg.Status)
	return err
}

const listPendingDeliveriesForSession = `-- name: ListPendingDeliveriesForSession :many
SELECT md.message_id, md.recipient_session_id, md.status, md.delivered_at, m.content, m.sender_name, m.message_type, m.metadata, m.channel_id
FROM message_deliveries md
JOIN messages m ON m.id = md.message_id
WHERE md.recipient_session_id = ? AND md.status = 'pending'
ORDER BY m.created_at ASC
`

type ListPendingDeliveriesForSessionRow struct {
	MessageID          string         `json:"message_id"`
	RecipientSessionID string         `json:"recipient_session_id"`
	Status             string         `json:"status"`
	DeliveredAt        sql.NullString `json:"delivered_at"`
	Content            string         `json:"content"`
	SenderName         string         `json:"sender_name"`
	MessageType        string         `json:"message_type"`
	Metadata           string         `json:"metadata"`
	ChannelID          string         `json:"channel_id"`
}

func (q *Queries) ListPendingDeliveriesForSession(ctx context.Context, recipientSessionID string) ([]ListPendingDeliveriesForSessionRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingDeliveriesForSession, recipientSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingDeliveriesForSessionRow{}
	for rows.Next() {
		var i ListPendingDeliveriesForSessionRow
		if err := rows.Scan(
			&i.MessageID,
			&i.RecipientSessionID,
			&i.Status,
			&i.DeliveredAt,
			&i.Content,
			&i.SenderName,
			&i.MessageType,
			&i.Metadata,
			&i.ChannelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeliveryStatus = `-- name: UpdateDeliveryStatus :exec
UPDATE message_deliveries
SET status = ?, delivered_at = strftime('%Y-%m-%dT%H:%M:%f', 'now')
WHERE message_id = ? AND recipient_session_id = ?
`

type UpdateDeliveryStatusParams struct {
	Status             string `json:"status"`
	MessageID          string `json:"message_id"`
	RecipientSessionID string `json:"recipient_session_id"`
}

func (q *Queries) UpdateDeliveryStatus(ctx context.Context, arg UpdateDeliveryStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeliveryStatus, arg.Status, arg.MessageID, arg.RecipientSessionID)
	return err
}
