// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package store

import (
	"context"
)

const countSessionIntroductionsInChannel = `-- name: CountSessionIntroductionsInChannel :one
SELECT COUNT(*) FROM messages
WHERE channel_id = ?
  AND sender_type = 'session'
  AND sender_id = ?
  AND message_type = 'introduction'
`

type CountSessionIntroductionsInChannelParams struct {
	ChannelID string `json:"channel_id"`
	SenderID  string `json:"sender_id"`
}

func (q *Queries) CountSessionIntroductionsInChannel(ctx context.Context, arg CountSessionIntroductionsInChannelParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionIntroductionsInChannel, arg.ChannelID, arg.SenderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMessagesByChannel = `-- name: DeleteMessagesByChannel :exec
DELETE FROM messages WHERE channel_id = ?
`

func (q *Queries) DeleteMessagesByChannel(ctx context.Context, channelID string) error {
	_, err := q.db.ExecContext(ctx, deleteMessagesByChannel, channelID)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT id, channel_id, sender_type, sender_id, sender_name, content, message_type, metadata, created_at FROM messages WHERE id = ?
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.SenderType,
		&i.SenderID,
		&i.SenderName,
		&i.Content,
		&i.MessageType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (id, channel_id, sender_type, sender_id, sender_name, content, message_type, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, channel_id, sender_type, sender_id, sender_name, content, message_type, metadata, created_at
`

type InsertMessageParams struct {
	ID          string `json:"id"`
	ChannelID   string `json:"channel_id"`
	SenderType  string `json:"sender_type"`
	SenderID    string `json:"sender_id"`
	SenderName  string `json:"sender_name"`
	Content     string `json:"content"`
	MessageType string `json:"message_type"`
	Metadata    string `json:"metadata"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, insertMessage,
		arg.ID,
		arg.ChannelID,
		arg.SenderType,
		arg.SenderID,
		arg.SenderName,
		arg.Content,
		arg.MessageType,
		arg.Metadata,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.SenderType,
		&i.SenderID,
		&i.SenderName,
		&i.Content,
		&i.MessageType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listMessagesByChannel = `-- name: ListMessagesByChannel :many
SELECT id, channel_id, sender_type, sender_id, sender_name, content, message_type, metadata, created_at FROM messages WHERE channel_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListMessagesByChannel(ctx context.Context, channelID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.SenderType,
			&i.SenderID,
			&i.SenderName,
			&i.Content,
			&i.MessageType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
