// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_resolutions.sql

package store

import (
	"context"
)

const listModelResolutions = `-- name: ListModelResolutions :many
SELECT provider, slug, resolved_id, last_seen_at FROM model_resolutions ORDER BY provider, slug
`

func (q *Queries) ListModelResolutions(ctx context.Context) ([]ModelResolution, error) {
	rows, err := q.db.QueryContext(ctx, listModelResolutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelResolution{}
	for rows.Next() {
		var i ModelResolution
		if err := rows.Scan(
			&i.Provider,
			&i.Slug,
			&i.ResolvedID,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertModelResolution = `-- name: UpsertModelResolution :exec
INSERT INTO model_resolutions (provider, slug, resolved_id, last_seen_at)
VALUES (?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
ON CONFLICT (provider, slug) DO UPDATE SET
    resolved_id = excluded.resolved_id,
    last_seen_at = excluded.last_seen_at
`

type UpsertModelResolutionParams struct {
	Provider   string `json:"provider"`
	Slug       string `json:"slug"`
	ResolvedID string `json:"resolved_id"`
}

func (q *Queries) UpsertModelResolution(ctx context.Context, arg UpsertModelResolutionParams) error {
	_, err := q.db.ExecContext(ctx, upsertModelResolution, arg.Provider, arg.Slug, arg.ResolvedID)
	return err
}
