// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type AgentProfile struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Role        string         `json:"role"`
	Description string         `json:"description"`
	ProjectID   sql.NullString `json:"project_id"`
	Avatar      string         `json:"avatar"`
	Config      string         `json:"config"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

type AuthSession struct {
	Token     string         `json:"token"`
	UserID    string         `json:"user_id"`
	ExpiresAt string         `json:"expires_at"`
	CreatedAt string         `json:"created_at"`
	ID        sql.NullString `json:"id"`
	Label     string         `json:"label"`
	Kind      string         `json:"kind"`
}

type BrainJob struct {
	ID        string `json:"id"`
	Kind      string `json:"kind"`
	Scope     string `json:"scope"`
	Payload   string `json:"payload"`
	Attempts  int64  `json:"attempts"`
	LastError string `json:"last_error"`
	CreatedAt string `json:"created_at"`
}

type Channel struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	ProjectID sql.NullString `json:"project_id"`
	CreatedAt string         `json:"created_at"`
}

type ChannelMember struct {
	ChannelID string `json:"channel_id"`
	SessionID string `json:"session_id"`
	Role      string `json:"role"`
	JoinedAt  string `json:"joined_at"`
}

type HostPresentation struct {
	ID    int64  `json:"id"`
	Label string `json:"label"`
	Icon  string `json:"icon"`
}

type InviteToken struct {
	Token     string         `json:"token"`
	CreatedBy string         `json:"created_by"`
	ExpiresAt string         `json:"expires_at"`
	UsedBy    sql.NullString `json:"used_by"`
	UsedAt    sql.NullString `json:"used_at"`
	CreatedAt string         `json:"created_at"`
}

type Machine struct {
	MachineID   string `json:"machine_id"`
	Label       string `json:"label"`
	BaseUrl     string `json:"base_url"`
	Token       string `json:"token"`
	AddedAt     string `json:"added_at"`
	Icon        string `json:"icon"`
	SessionID   string `json:"session_id"`
	IdentityKey string `json:"identity_key"`
}

type Message struct {
	ID          string `json:"id"`
	ChannelID   string `json:"channel_id"`
	SenderType  string `json:"sender_type"`
	SenderID    string `json:"sender_id"`
	SenderName  string `json:"sender_name"`
	Content     string `json:"content"`
	MessageType string `json:"message_type"`
	Metadata    string `json:"metadata"`
	CreatedAt   string `json:"created_at"`
}

type MessageDelivery struct {
	MessageID          string         `json:"message_id"`
	RecipientSessionID string         `json:"recipient_session_id"`
	Status             string         `json:"status"`
	DeliveredAt        sql.NullString `json:"delivered_at"`
}

type ModelResolution struct {
	Provider   string `json:"provider"`
	Slug       string `json:"slug"`
	ResolvedID string `json:"resolved_id"`
	LastSeenAt string `json:"last_seen_at"`
}

type PairingToken struct {
	Token     string         `json:"token"`
	UserID    string         `json:"user_id"`
	ExpiresAt string         `json:"expires_at"`
	UsedAt    sql.NullString `json:"used_at"`
	CreatedAt string         `json:"created_at"`
}

type PersonaInteraction struct {
	ID             string  `json:"id"`
	ProfileID      string  `json:"profile_id"`
	TeamID         string  `json:"team_id"`
	AskerType      string  `json:"asker_type"`
	AskerID        string  `json:"asker_id"`
	Question       string  `json:"question"`
	Action         string  `json:"action"`
	Confidence     float64 `json:"confidence"`
	Response       string  `json:"response"`
	RedirectTo     string  `json:"redirect_to"`
	ResponseTimeMs int64   `json:"response_time_ms"`
	CreatedAt      string  `json:"created_at"`
}

type Project struct {
	ID                     string `json:"id"`
	Name                   string `json:"name"`
	Path                   string `json:"path"`
	DefaultModel           string `json:"default_model"`
	DefaultPermissionMode  string `json:"default_permission_mode"`
	DefaultSystemPrompt    string `json:"default_system_prompt"`
	CreatedAt              string `json:"created_at"`
	UpdatedAt              string `json:"updated_at"`
	Slug                   string `json:"slug"`
	SortOrder              int64  `json:"sort_order"`
	DefaultBehaviorPresets string `json:"default_behavior_presets"`
	Favorite               int64  `json:"favorite"`
	Color                  string `json:"color"`
	Icon                   string `json:"icon"`
	Folder                 string `json:"folder"`
	MaxSessions            int64  `json:"max_sessions"`
	Pinned                 int64  `json:"pinned"`
	RemoteUrl              string `json:"remote_url"`
}

type PromptTemplate struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Content     string `json:"content"`
	Settings    string `json:"settings"`
	Tags        string `json:"tags"`
	SortOrder   int64  `json:"sort_order"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type Schedule struct {
	ID                  string `json:"id"`
	ProjectID           string `json:"project_id"`
	SessionID           string `json:"session_id"`
	Name                string `json:"name"`
	Prompt              string `json:"prompt"`
	Cron                string `json:"cron"`
	Mode                string `json:"mode"`
	Enabled             int64  `json:"enabled"`
	PauseReason         string `json:"pause_reason"`
	Attention           string `json:"attention"`
	AttentionRunID      string `json:"attention_run_id"`
	NextRunAt           string `json:"next_run_at"`
	ExpiresAt           string `json:"expires_at"`
	LastRunAt           string `json:"last_run_at"`
	LastViewedAt        string `json:"last_viewed_at"`
	ConsecutiveFailures int64  `json:"consecutive_failures"`
	CreatedBy           string `json:"created_by"`
	CreatedAt           string `json:"created_at"`
	UpdatedAt           string `json:"updated_at"`
}

type ScheduleRun struct {
	ID            string `json:"id"`
	ScheduleID    string `json:"schedule_id"`
	SessionID     string `json:"session_id"`
	ScheduledFor  string `json:"scheduled_for"`
	CreatedAt     string `json:"created_at"`
	FiredAt       string `json:"fired_at"`
	FinishedAt    string `json:"finished_at"`
	Status        string `json:"status"`
	Overdue       int64  `json:"overdue"`
	Attempts      int64  `json:"attempts"`
	NextAttemptAt string `json:"next_attempt_at"`
	TurnIndex     int64  `json:"turn_index"`
	Summary       string `json:"summary"`
	Reason        string `json:"reason"`
	Error         string `json:"error"`
	ErrorKind     string `json:"error_kind"`
	LateReport    string `json:"late_report"`
	DurationMs    int64  `json:"duration_ms"`
}

type Session struct {
	ID              string         `json:"id"`
	ProjectID       string         `json:"project_id"`
	Name            string         `json:"name"`
	WorkDir         string         `json:"work_dir"`
	WorktreePath    sql.NullString `json:"worktree_path"`
	WorktreeBranch  sql.NullString `json:"worktree_branch"`
	State           string         `json:"state"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
	ClaudeSessionID sql.NullString `json:"claude_session_id"`
	WorktreeBaseSha sql.NullString `json:"worktree_base_sha"`
	Model           string         `json:"model"`
	WorktreeMerged  int64          `json:"worktree_merged"`
	PermissionMode  string         `json:"permission_mode"`
	AutoApprove     int64          `json:"auto_approve"`
	PrUrl           string         `json:"pr_url"`
	Effort          string         `json:"effort"`
	MaxBudget       float64        `json:"max_budget"`
	MaxTurns        int64          `json:"max_turns"`
	LastQueryAt     sql.NullString `json:"last_query_at"`
	ArchivedAt      sql.NullString `json:"archived_at"`
	BehaviorPresets string         `json:"behavior_presets"`
	ChannelID       sql.NullString `json:"channel_id"`
	ChannelRole     string         `json:"channel_role"`
	AutoApproveMode string         `json:"auto_approve_mode"`
	AgentProfileID  sql.NullString `json:"agent_profile_id"`
	ParentSessionID sql.NullString `json:"parent_session_id"`
	Provider        string         `json:"provider"`
	ResolvedModel   string         `json:"resolved_model"`
	Pinned          int64          `json:"pinned"`
	PinOrder        int64          `json:"pin_order"`
}

type SessionEvent struct {
	ID        int64          `json:"id"`
	SessionID string         `json:"session_id"`
	TurnIndex int64          `json:"turn_index"`
	Seq       int64          `json:"seq"`
	Type      string         `json:"type"`
	Data      string         `json:"data"`
	CreatedAt string         `json:"created_at"`
	MessageID sql.NullString `json:"message_id"`
}

type Team struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type TeamMember struct {
	TeamID         string `json:"team_id"`
	AgentProfileID string `json:"agent_profile_id"`
	SortOrder      int64  `json:"sort_order"`
	JoinedAt       string `json:"joined_at"`
}

type User struct {
	ID               string `json:"id"`
	DisplayName      string `json:"display_name"`
	IsAdmin          int64  `json:"is_admin"`
	CreatedAt        string `json:"created_at"`
	SidebarFocusMode int64  `json:"sidebar_focus_mode"`
}

type WebauthnCredential struct {
	ID              string `json:"id"`
	UserID          string `json:"user_id"`
	PublicKey       []byte `json:"public_key"`
	AttestationType string `json:"attestation_type"`
	Aaguid          []byte `json:"aaguid"`
	SignCount       int64  `json:"sign_count"`
	Transport       string `json:"transport"`
	CreatedAt       string `json:"created_at"`
	BackupEligible  int64  `json:"backup_eligible"`
	BackupState     int64  `json:"backup_state"`
}
