// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"database/sql"
)

type AuthSession struct {
	Token     string `json:"token"`
	UserID    string `json:"user_id"`
	ExpiresAt string `json:"expires_at"`
	CreatedAt string `json:"created_at"`
}

type InviteToken struct {
	Token     string         `json:"token"`
	CreatedBy string         `json:"created_by"`
	ExpiresAt string         `json:"expires_at"`
	UsedBy    sql.NullString `json:"used_by"`
	UsedAt    sql.NullString `json:"used_at"`
	CreatedAt string         `json:"created_at"`
}

type Project struct {
	ID                    string `json:"id"`
	Name                  string `json:"name"`
	Path                  string `json:"path"`
	DefaultModel          string `json:"default_model"`
	DefaultPermissionMode string `json:"default_permission_mode"`
	DefaultSystemPrompt   string `json:"default_system_prompt"`
	CreatedAt             string `json:"created_at"`
	UpdatedAt             string `json:"updated_at"`
	Slug                  string `json:"slug"`
	SortOrder             int64  `json:"sort_order"`
}

type Session struct {
	ID              string         `json:"id"`
	ProjectID       string         `json:"project_id"`
	Name            string         `json:"name"`
	WorkDir         string         `json:"work_dir"`
	WorktreePath    sql.NullString `json:"worktree_path"`
	WorktreeBranch  sql.NullString `json:"worktree_branch"`
	State           string         `json:"state"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
	ClaudeSessionID sql.NullString `json:"claude_session_id"`
	WorktreeBaseSha sql.NullString `json:"worktree_base_sha"`
	Model           string         `json:"model"`
	WorktreeMerged  int64          `json:"worktree_merged"`
	PermissionMode  string         `json:"permission_mode"`
	AutoApprove     int64          `json:"auto_approve"`
	PrUrl           string         `json:"pr_url"`
	Effort          string         `json:"effort"`
	MaxBudget       float64        `json:"max_budget"`
	MaxTurns        int64          `json:"max_turns"`
	LastQueryAt     sql.NullString `json:"last_query_at"`
	CompletedAt     sql.NullString `json:"completed_at"`
}

type SessionEvent struct {
	ID        int64  `json:"id"`
	SessionID string `json:"session_id"`
	TurnIndex int64  `json:"turn_index"`
	Seq       int64  `json:"seq"`
	Type      string `json:"type"`
	Data      string `json:"data"`
	CreatedAt string `json:"created_at"`
}

type User struct {
	ID          string `json:"id"`
	DisplayName string `json:"display_name"`
	IsAdmin     int64  `json:"is_admin"`
	CreatedAt   string `json:"created_at"`
}

type WebauthnCredential struct {
	ID              string `json:"id"`
	UserID          string `json:"user_id"`
	PublicKey       []byte `json:"public_key"`
	AttestationType string `json:"attestation_type"`
	Aaguid          []byte `json:"aaguid"`
	SignCount       int64  `json:"sign_count"`
	Transport       string `json:"transport"`
	CreatedAt       string `json:"created_at"`
	BackupEligible  int64  `json:"backup_eligible"`
	BackupState     int64  `json:"backup_state"`
}
