// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: peer.sql

package store

import (
	"context"
)

const insertPeerOutbox = `-- name: InsertPeerOutbox :one
INSERT INTO peer_outbox (credential_id, kind, session_id, payload, at)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING seq
`

type InsertPeerOutboxParams struct {
	CredentialID string `json:"credential_id"`
	Kind         string `json:"kind"`
	SessionID    string `json:"session_id"`
	Payload      string `json:"payload"`
	At           string `json:"at"`
}

func (q *Queries) InsertPeerOutbox(ctx context.Context, arg InsertPeerOutboxParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPeerOutbox,
		arg.CredentialID,
		arg.Kind,
		arg.SessionID,
		arg.Payload,
		arg.At,
	)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const latestPeerOutboxSeq = `-- name: LatestPeerOutboxSeq :one
SELECT CAST(COALESCE(MAX(seq), 0) AS INTEGER) FROM peer_outbox WHERE credential_id = ?
`

// The newest seq one follower has, 0 when it has none: what a follower that
// has never read starts from when it wants news from now on rather than the
// whole retention window.
func (q *Queries) LatestPeerOutboxSeq(ctx context.Context, credentialID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, latestPeerOutboxSeq, credentialID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listPeerFollowers = `-- name: ListPeerFollowers :many
SELECT credential_id FROM peer_follows WHERE session_id = ? ORDER BY credential_id
`

func (q *Queries) ListPeerFollowers(ctx context.Context, sessionID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPeerFollowers, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var credential_id string
		if err := rows.Scan(&credential_id); err != nil {
			return nil, err
		}
		items = append(items, credential_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeerOutboxSince = `-- name: ListPeerOutboxSince :many
SELECT seq, kind, session_id, payload, at FROM peer_outbox
WHERE credential_id = ?1 AND seq > ?2
ORDER BY seq
LIMIT ?3
`

type ListPeerOutboxSinceParams struct {
	CredentialID string `json:"credential_id"`
	Since        int64  `json:"since"`
	MaxRows      int64  `json:"max_rows"`
}

type ListPeerOutboxSinceRow struct {
	Seq       int64  `json:"seq"`
	Kind      string `json:"kind"`
	SessionID string `json:"session_id"`
	Payload   string `json:"payload"`
	At        string `json:"at"`
}

func (q *Queries) ListPeerOutboxSince(ctx context.Context, arg ListPeerOutboxSinceParams) ([]ListPeerOutboxSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listPeerOutboxSince, arg.CredentialID, arg.Since, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPeerOutboxSinceRow{}
	for rows.Next() {
		var i ListPeerOutboxSinceRow
		if err := rows.Scan(
			&i.Seq,
			&i.Kind,
			&i.SessionID,
			&i.Payload,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const prunePeerOutbox = `-- name: PrunePeerOutbox :execrows
DELETE FROM peer_outbox WHERE at < ?
`

func (q *Queries) PrunePeerOutbox(ctx context.Context, at string) (int64, error) {
	result, err := q.db.ExecContext(ctx, prunePeerOutbox, at)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertPeerFollow = `-- name: UpsertPeerFollow :exec
INSERT INTO peer_follows (session_id, credential_id, policy_id, followed_at)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (session_id, credential_id) DO UPDATE
SET policy_id = excluded.policy_id, followed_at = excluded.followed_at
`

type UpsertPeerFollowParams struct {
	SessionID    string `json:"session_id"`
	CredentialID string `json:"credential_id"`
	PolicyID     string `json:"policy_id"`
	FollowedAt   string `json:"followed_at"`
}

func (q *Queries) UpsertPeerFollow(ctx context.Context, arg UpsertPeerFollowParams) error {
	_, err := q.db.ExecContext(ctx, upsertPeerFollow,
		arg.SessionID,
		arg.CredentialID,
		arg.PolicyID,
		arg.FollowedAt,
	)
	return err
}
