// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: persona_interactions.sql

package store

import (
	"context"
)

const insertPersonaInteraction = `-- name: InsertPersonaInteraction :one
INSERT INTO persona_interactions (id, profile_id, team_id, asker_type, asker_id, question, action, confidence, response, redirect_to, response_time_ms)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, profile_id, team_id, asker_type, asker_id, question, "action", confidence, response, redirect_to, response_time_ms, created_at
`

type InsertPersonaInteractionParams struct {
	ID             string  `json:"id"`
	ProfileID      string  `json:"profile_id"`
	TeamID         string  `json:"team_id"`
	AskerType      string  `json:"asker_type"`
	AskerID        string  `json:"asker_id"`
	Question       string  `json:"question"`
	Action         string  `json:"action"`
	Confidence     float64 `json:"confidence"`
	Response       string  `json:"response"`
	RedirectTo     string  `json:"redirect_to"`
	ResponseTimeMs int64   `json:"response_time_ms"`
}

func (q *Queries) InsertPersonaInteraction(ctx context.Context, arg InsertPersonaInteractionParams) (PersonaInteraction, error) {
	row := q.db.QueryRowContext(ctx, insertPersonaInteraction,
		arg.ID,
		arg.ProfileID,
		arg.TeamID,
		arg.AskerType,
		arg.AskerID,
		arg.Question,
		arg.Action,
		arg.Confidence,
		arg.Response,
		arg.RedirectTo,
		arg.ResponseTimeMs,
	)
	var i PersonaInteraction
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.TeamID,
		&i.AskerType,
		&i.AskerID,
		&i.Question,
		&i.Action,
		&i.Confidence,
		&i.Response,
		&i.RedirectTo,
		&i.ResponseTimeMs,
		&i.CreatedAt,
	)
	return i, err
}

const listPersonaInteractions = `-- name: ListPersonaInteractions :many
SELECT id, profile_id, team_id, asker_type, asker_id, question, "action", confidence, response, redirect_to, response_time_ms, created_at FROM persona_interactions
WHERE team_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListPersonaInteractionsParams struct {
	TeamID string `json:"team_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListPersonaInteractions(ctx context.Context, arg ListPersonaInteractionsParams) ([]PersonaInteraction, error) {
	rows, err := q.db.QueryContext(ctx, listPersonaInteractions, arg.TeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PersonaInteraction{}
	for rows.Next() {
		var i PersonaInteraction
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.TeamID,
			&i.AskerType,
			&i.AskerID,
			&i.Question,
			&i.Action,
			&i.Confidence,
			&i.Response,
			&i.RedirectTo,
			&i.ResponseTimeMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonaInteractionsForProfile = `-- name: ListPersonaInteractionsForProfile :many
SELECT id, profile_id, team_id, asker_type, asker_id, question, "action", confidence, response, redirect_to, response_time_ms, created_at FROM persona_interactions
WHERE profile_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListPersonaInteractionsForProfileParams struct {
	ProfileID string `json:"profile_id"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

func (q *Queries) ListPersonaInteractionsForProfile(ctx context.Context, arg ListPersonaInteractionsForProfileParams) ([]PersonaInteraction, error) {
	rows, err := q.db.QueryContext(ctx, listPersonaInteractionsForProfile, arg.ProfileID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PersonaInteraction{}
	for rows.Next() {
		var i PersonaInteraction
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.TeamID,
			&i.AskerType,
			&i.AskerID,
			&i.Question,
			&i.Action,
			&i.Confidence,
			&i.Response,
			&i.RedirectTo,
			&i.ResponseTimeMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
