// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projects.sql

package store

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, name, path, slug) VALUES (?, ?, ?, ?) RETURNING id, name, path, default_model, default_permission_mode, default_system_prompt, created_at, updated_at, slug, sort_order, default_behavior_presets, favorite
`

type CreateProjectParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Path string `json:"path"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Path,
		arg.Slug,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.DefaultModel,
		&i.DefaultPermissionMode,
		&i.DefaultSystemPrompt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.SortOrder,
		&i.DefaultBehaviorPresets,
		&i.Favorite,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, path, default_model, default_permission_mode, default_system_prompt, created_at, updated_at, slug, sort_order, default_behavior_presets, favorite FROM projects WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.DefaultModel,
		&i.DefaultPermissionMode,
		&i.DefaultSystemPrompt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.SortOrder,
		&i.DefaultBehaviorPresets,
		&i.Favorite,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, name, path, default_model, default_permission_mode, default_system_prompt, created_at, updated_at, slug, sort_order, default_behavior_presets, favorite FROM projects WHERE slug = ?
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.DefaultModel,
		&i.DefaultPermissionMode,
		&i.DefaultSystemPrompt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.SortOrder,
		&i.DefaultBehaviorPresets,
		&i.Favorite,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, path, default_model, default_permission_mode, default_system_prompt, created_at, updated_at, slug, sort_order, default_behavior_presets, favorite FROM projects ORDER BY sort_order ASC, updated_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.DefaultModel,
			&i.DefaultPermissionMode,
			&i.DefaultSystemPrompt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.SortOrder,
			&i.DefaultBehaviorPresets,
			&i.Favorite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectBehaviorPresets = `-- name: UpdateProjectBehaviorPresets :one
UPDATE projects SET default_behavior_presets = ?, updated_at = datetime('now') WHERE id = ? RETURNING id, name, path, default_model, default_permission_mode, default_system_prompt, created_at, updated_at, slug, sort_order, default_behavior_presets, favorite
`

type UpdateProjectBehaviorPresetsParams struct {
	DefaultBehaviorPresets string `json:"default_behavior_presets"`
	ID                     string `json:"id"`
}

func (q *Queries) UpdateProjectBehaviorPresets(ctx context.Context, arg UpdateProjectBehaviorPresetsParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProjectBehaviorPresets, arg.DefaultBehaviorPresets, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.DefaultModel,
		&i.DefaultPermissionMode,
		&i.DefaultSystemPrompt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.SortOrder,
		&i.DefaultBehaviorPresets,
		&i.Favorite,
	)
	return i, err
}

const updateProjectFavorite = `-- name: UpdateProjectFavorite :one
UPDATE projects SET favorite = ?, updated_at = datetime('now') WHERE id = ? RETURNING id, name, path, default_model, default_permission_mode, default_system_prompt, created_at, updated_at, slug, sort_order, default_behavior_presets, favorite
`

type UpdateProjectFavoriteParams struct {
	Favorite int64  `json:"favorite"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateProjectFavorite(ctx context.Context, arg UpdateProjectFavoriteParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProjectFavorite, arg.Favorite, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.DefaultModel,
		&i.DefaultPermissionMode,
		&i.DefaultSystemPrompt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.SortOrder,
		&i.DefaultBehaviorPresets,
		&i.Favorite,
	)
	return i, err
}

const updateProjectSlug = `-- name: UpdateProjectSlug :one
UPDATE projects SET slug = ?, updated_at = datetime('now') WHERE id = ? RETURNING id, name, path, default_model, default_permission_mode, default_system_prompt, created_at, updated_at, slug, sort_order, default_behavior_presets, favorite
`

type UpdateProjectSlugParams struct {
	Slug string `json:"slug"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateProjectSlug(ctx context.Context, arg UpdateProjectSlugParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProjectSlug, arg.Slug, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.DefaultModel,
		&i.DefaultPermissionMode,
		&i.DefaultSystemPrompt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.SortOrder,
		&i.DefaultBehaviorPresets,
		&i.Favorite,
	)
	return i, err
}

const updateProjectSortOrder = `-- name: UpdateProjectSortOrder :exec
UPDATE projects SET sort_order = ? WHERE id = ?
`

type UpdateProjectSortOrderParams struct {
	SortOrder int64  `json:"sort_order"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateProjectSortOrder(ctx context.Context, arg UpdateProjectSortOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectSortOrder, arg.SortOrder, arg.ID)
	return err
}
