// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prompt_templates.sql

package store

import (
	"context"
)

const createPromptTemplate = `-- name: CreatePromptTemplate :one
INSERT INTO prompt_templates (id, name, description, content, settings, tags)
VALUES (?, ?, ?, ?, ?, ?) RETURNING id, name, description, content, settings, tags, sort_order, created_at, updated_at
`

type CreatePromptTemplateParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Content     string `json:"content"`
	Settings    string `json:"settings"`
	Tags        string `json:"tags"`
}

func (q *Queries) CreatePromptTemplate(ctx context.Context, arg CreatePromptTemplateParams) (PromptTemplate, error) {
	row := q.db.QueryRowContext(ctx, createPromptTemplate,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Content,
		arg.Settings,
		arg.Tags,
	)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.Settings,
		&i.Tags,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePromptTemplate = `-- name: DeletePromptTemplate :exec
DELETE FROM prompt_templates WHERE id = ?
`

func (q *Queries) DeletePromptTemplate(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePromptTemplate, id)
	return err
}

const getPromptTemplate = `-- name: GetPromptTemplate :one
SELECT id, name, description, content, settings, tags, sort_order, created_at, updated_at FROM prompt_templates WHERE id = ?
`

func (q *Queries) GetPromptTemplate(ctx context.Context, id string) (PromptTemplate, error) {
	row := q.db.QueryRowContext(ctx, getPromptTemplate, id)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.Settings,
		&i.Tags,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPromptTemplates = `-- name: ListPromptTemplates :many
SELECT id, name, description, content, settings, tags, sort_order, created_at, updated_at FROM prompt_templates ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListPromptTemplates(ctx context.Context) ([]PromptTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listPromptTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromptTemplate{}
	for rows.Next() {
		var i PromptTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Content,
			&i.Settings,
			&i.Tags,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderPromptTemplates = `-- name: ReorderPromptTemplates :exec
UPDATE prompt_templates SET sort_order = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type ReorderPromptTemplatesParams struct {
	SortOrder int64  `json:"sort_order"`
	ID        string `json:"id"`
}

func (q *Queries) ReorderPromptTemplates(ctx context.Context, arg ReorderPromptTemplatesParams) error {
	_, err := q.db.ExecContext(ctx, reorderPromptTemplates, arg.SortOrder, arg.ID)
	return err
}

const updatePromptTemplate = `-- name: UpdatePromptTemplate :one
UPDATE prompt_templates
SET name = ?, description = ?, content = ?, settings = ?, tags = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ? RETURNING id, name, description, content, settings, tags, sort_order, created_at, updated_at
`

type UpdatePromptTemplateParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Content     string `json:"content"`
	Settings    string `json:"settings"`
	Tags        string `json:"tags"`
	ID          string `json:"id"`
}

func (q *Queries) UpdatePromptTemplate(ctx context.Context, arg UpdatePromptTemplateParams) (PromptTemplate, error) {
	row := q.db.QueryRowContext(ctx, updatePromptTemplate,
		arg.Name,
		arg.Description,
		arg.Content,
		arg.Settings,
		arg.Tags,
		arg.ID,
	)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.Settings,
		&i.Tags,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
