// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddChannelMember(ctx context.Context, arg AddChannelMemberParams) error
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error
	AdvanceScheduleNextRunIfEnabled(ctx context.Context, arg AdvanceScheduleNextRunIfEnabledParams) (int64, error)
	AllSessionSummaries(ctx context.Context) ([]AllSessionSummariesRow, error)
	AppendScheduleRunLateReport(ctx context.Context, arg AppendScheduleRunLateReportParams) error
	ClaimScheduleRun(ctx context.Context, id string) (int64, error)
	ClearScheduleActionAttention(ctx context.Context, arg ClearScheduleActionAttentionParams) error
	// The mark describes the MOST RECENT stop, so resuming clears it: a session
	// that has run since is no longer a session agentique reclaimed. Also the
	// release path when the stop behind a claim fails and the session stays alive.
	ClearSessionEvictedAt(ctx context.Context, id string) error
	// The read receipt. Idempotent by construction: clearing an already-clear row
	// touches nothing the client can see.
	ClearSessionUnseenCompletedAt(ctx context.Context, id string) error
	ConsumePairingToken(ctx context.Context, tokenHash string) (PairingToken, error)
	CountActiveSessionsByProject(ctx context.Context, projectID string) (int64, error)
	// How many entries this surface has never been shown. The rail's notch reads
	// it once per connection; the journal pushes keep it current after that.
	CountAssistantJournalUnseen(ctx context.Context, surface sql.NullString) (int64, error)
	CountSessionIntroductionsInChannel(ctx context.Context, arg CountSessionIntroductionsInChannelParams) (int64, error)
	CountTurnsBySession(ctx context.Context, sessionID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountWebAuthnCredentials(ctx context.Context) (int64, error)
	CreateAgentProfile(ctx context.Context, arg CreateAgentProfileParams) (AgentProfile, error)
	CreateAssistantChannel(ctx context.Context, arg CreateAssistantChannelParams) (Channel, error)
	CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) error
	CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error)
	CreateInviteToken(ctx context.Context, arg CreateInviteTokenParams) error
	CreatePairingToken(ctx context.Context, arg CreatePairingTokenParams) error
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreatePromptTemplate(ctx context.Context, arg CreatePromptTemplateParams) (PromptTemplate, error)
	// Scheduled loops (docs/scheduled-loops.md). All timestamps are UTC RFC3339
	// seconds precision ("2006-01-02T15:04:05Z"); '' means unset.
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error)
	CreateScheduleRun(ctx context.Context, arg CreateScheduleRunParams) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) error
	// The decision. Guarded on status = 'open' so two surfaces cannot both decide
	// one proposal: the second write touches nothing, and the caller re-reads the
	// row it did not change.
	//
	// It answers how many rows it changed, so the caller does not have to assume
	// the guard matched. Zero means somebody else settled this proposal first,
	// which is a different thing from the write failing -- and after an action has
	// already been performed, the difference is worth a log line that says which.
	DecideAssistantProposal(ctx context.Context, arg DecideAssistantProposalParams) (int64, error)
	DeleteAgentProfile(ctx context.Context, id string) error
	DeleteAllAuthSessions(ctx context.Context) error
	DeleteAllWebAuthnCredentials(ctx context.Context) error
	DeleteAssistantFollow(ctx context.Context, sessionID string) error
	DeleteAuthSession(ctx context.Context, tokenHash string) error
	DeleteAuthSessionByID(ctx context.Context, id sql.NullString) (int64, error)
	DeleteBearerAuthSessionByIDAndUser(ctx context.Context, arg DeleteBearerAuthSessionByIDAndUserParams) (int64, error)
	DeleteChannel(ctx context.Context, id string) error
	DeleteExpiredAuthSessions(ctx context.Context) error
	DeleteExpiredPairingTokens(ctx context.Context) error
	DeleteMachine(ctx context.Context, machineID string) error
	DeleteMessagesByChannel(ctx context.Context, channelID string) error
	DeleteProject(ctx context.Context, id string) error
	DeletePromptTemplate(ctx context.Context, id string) error
	DeleteSchedule(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteTeam(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	// Lazy expiry, applied on a decide: an open proposal past its expiry is not an
	// offer any more. There is no timer behind this -- a proposal nobody looks at
	// costs nothing, and a sweep would be a second writer on a table whose whole
	// content is decisions.
	ExpireAssistantProposals(ctx context.Context, at string) error
	GetActiveSessionByAgentProfile(ctx context.Context, agentProfileID sql.NullString) (Session, error)
	GetAdminUser(ctx context.Context) (User, error)
	GetAgentProfile(ctx context.Context, id string) (AgentProfile, error)
	// The conversation, found without the state row. The oldest wins: if a second
	// one was ever created, the first is the one the history is in.
	GetAssistantChannel(ctx context.Context) (Channel, error)
	GetAssistantFollow(ctx context.Context, sessionID string) (AssistantFollow, error)
	GetAssistantProposal(ctx context.Context, id string) (AssistantProposal, error)
	// The assistant's state, journal, follow list and conversation channel.
	// See docs/assistant.md and migration 056.
	//
	// Keep this file ASCII. sqlc expands `SELECT *` by byte offset, so one
	// multi-byte character shifts those offsets and corrupts the generated code
	// for LATER queries.
	GetAssistantState(ctx context.Context) (AssistantState, error)
	GetAuthSession(ctx context.Context, tokenHash string) (GetAuthSessionRow, error)
	GetChannel(ctx context.Context, id string) (Channel, error)
	GetCredentialByID(ctx context.Context, id string) (WebauthnCredential, error)
	GetHostPresentation(ctx context.Context) (GetHostPresentationRow, error)
	GetInviteToken(ctx context.Context, tokenHash string) (InviteToken, error)
	GetMachine(ctx context.Context, machineID string) (Machine, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	// One learned mapping, for a session whose own run never reported a model: the
	// last_seen_at that comes back is what dates the answer.
	GetModelResolution(ctx context.Context, arg GetModelResolutionParams) (ModelResolution, error)
	// One open proposal for the same verb and the same target, if there is one.
	//
	// Asking twice for the same thing is one card, not two: a second row would
	// give the operator two buttons for one decision, and accepting either would
	// leave the other pointing at work already done.
	GetOpenAssistantProposalFor(ctx context.Context, arg GetOpenAssistantProposalForParams) (AssistantProposal, error)
	GetProject(ctx context.Context, id string) (Project, error)
	GetProjectBySlug(ctx context.Context, slug string) (Project, error)
	GetPromptTemplate(ctx context.Context, id string) (PromptTemplate, error)
	GetSchedule(ctx context.Context, id string) (Schedule, error)
	GetScheduleRun(ctx context.Context, id string) (ScheduleRun, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetSessionEvent(ctx context.Context, arg GetSessionEventParams) (SessionEvent, error)
	GetTeam(ctx context.Context, id string) (Team, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByDisplayName(ctx context.Context, displayName string) (User, error)
	GetVoiceSettings(ctx context.Context) (GetVoiceSettingsRow, error)
	InsertAssistantJournalEntry(ctx context.Context, arg InsertAssistantJournalEntryParams) (AssistantJournal, error)
	// One message of the conversation.
	//
	// Its own insert rather than InsertMessage because created_at is passed IN.
	// The table's default stamps milliseconds, and an ask and its reply can land
	// in the same millisecond -- at which point the only tiebreak left is the
	// uuid, and the two read back in no order at all. A fixed-width nanosecond
	// stamp sorts lexicographically, which for this column is the only kind of
	// sorting there is. Nothing else writes to an assistant channel, so the
	// sharper format is consistent within the timeline that reads it.
	InsertAssistantMessage(ctx context.Context, arg InsertAssistantMessageParams) (Message, error)
	// Proposals: the uncontained tier's card, and the record of its yes or no.
	// See docs/assistant.md's M3 contract and migration 057.
	InsertAssistantProposal(ctx context.Context, arg InsertAssistantProposalParams) (AssistantProposal, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	InsertEventWithMessageID(ctx context.Context, arg InsertEventWithMessageIDParams) error
	InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error)
	InsertMessageDelivery(ctx context.Context, arg InsertMessageDeliveryParams) error
	InsertPersonaInteraction(ctx context.Context, arg InsertPersonaInteractionParams) (PersonaInteraction, error)
	ListAgentMessagesByChannel(ctx context.Context, channelID string) ([]SessionEvent, error)
	ListAgentProfiles(ctx context.Context) ([]AgentProfile, error)
	ListAllSessions(ctx context.Context) ([]Session, error)
	ListAssistantFollows(ctx context.Context) ([]AssistantFollow, error)
	ListAssistantJournalSince(ctx context.Context, arg ListAssistantJournalSinceParams) ([]AssistantJournal, error)
	ListAssistantJournalUnseen(ctx context.Context, arg ListAssistantJournalUnseenParams) ([]AssistantJournal, error)
	// One page of the conversation, newest first. An empty `before` starts at the
	// newest message; otherwise it is a created_at cursor.
	//
	// rowid breaks the tie, not id. messages.created_at has millisecond precision
	// and a message's id is a uuid, so two turns written in the same millisecond --
	// an ask and a mirrored reply -- would come back in uuid order, which is to say
	// in no order. rowid is insertion order, which is the order they were said in.
	ListAssistantMessagesBefore(ctx context.Context, arg ListAssistantMessagesBeforeParams) ([]Message, error)
	// What has been said in the conversation since a surface last looked, oldest
	// first: this is read to be pasted into a preamble or a strip, in order.
	ListAssistantMessagesSince(ctx context.Context, arg ListAssistantMessagesSinceParams) ([]Message, error)
	// Open first, then whatever was decided, newest first within each half. A
	// surface renders the open ones as cards and the rest as history, and one read
	// answers both.
	ListAssistantProposals(ctx context.Context, lim int64) ([]AssistantProposal, error)
	ListAuthSessions(ctx context.Context) ([]ListAuthSessionsRow, error)
	ListChannelMemberSessions(ctx context.Context, channelID string) ([]ListChannelMemberSessionsRow, error)
	// Ordinary channels only. The assistant's conversation is a channel with
	// kind = 'assistant' and is not one of a project's channels: it has no project,
	// it has no roster, and a row for it in the channel list would offer every
	// channel gesture (dissolve, add a member) against the thread.
	ListChannelsByProject(ctx context.Context, projectID sql.NullString) ([]Channel, error)
	ListChildSessions(ctx context.Context, parentSessionID sql.NullString) ([]Session, error)
	ListCredentialsByUser(ctx context.Context, userID string) ([]WebauthnCredential, error)
	ListDueSchedules(ctx context.Context, nextRunAt string) ([]Schedule, error)
	ListEnabledSchedulesBySession(ctx context.Context, sessionID string) ([]Schedule, error)
	ListEventsBySession(ctx context.Context, sessionID string) ([]SessionEvent, error)
	ListInviteTokens(ctx context.Context, createdBy string) ([]InviteToken, error)
	ListMachines(ctx context.Context) ([]Machine, error)
	ListMessagesByChannel(ctx context.Context, channelID string) ([]Message, error)
	ListModelResolutions(ctx context.Context) ([]ModelResolution, error)
	ListPendingDeliveriesForSession(ctx context.Context, recipientSessionID string) ([]ListPendingDeliveriesForSessionRow, error)
	ListPersonaInteractions(ctx context.Context, arg ListPersonaInteractionsParams) ([]PersonaInteraction, error)
	ListPersonaInteractionsForProfile(ctx context.Context, arg ListPersonaInteractionsForProfileParams) ([]PersonaInteraction, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListPromptTemplates(ctx context.Context) ([]PromptTemplate, error)
	ListQueuedRunsBySession(ctx context.Context, sessionID string) ([]ScheduleRun, error)
	ListRecentActivityByProject(ctx context.Context, arg ListRecentActivityByProjectParams) ([]ListRecentActivityByProjectRow, error)
	ListRecentActivityGlobal(ctx context.Context, arg ListRecentActivityGlobalParams) ([]ListRecentActivityGlobalRow, error)
	ListRecentEventsBySession(ctx context.Context, arg ListRecentEventsBySessionParams) ([]SessionEvent, error)
	ListRunsSince(ctx context.Context, arg ListRunsSinceParams) (ListRunsSinceRow, error)
	ListScheduleRuns(ctx context.Context, arg ListScheduleRunsParams) ([]ScheduleRun, error)
	ListSchedules(ctx context.Context) ([]Schedule, error)
	ListSchedulesBySession(ctx context.Context, sessionID string) ([]Schedule, error)
	ListSessionChannels(ctx context.Context, sessionID string) ([]ListSessionChannelsRow, error)
	// The session.state observer's baseline: what every session's two outcome
	// facts already were before the observer started watching. A push is a whole
	// snapshot, not a transition, so without this the first push for a session
	// archived last month reads as news -- and on the first boot with the
	// assistant on, that was one entry per archived session ever.
	ListSessionOutcomeBaseline(ctx context.Context) ([]ListSessionOutcomeBaselineRow, error)
	ListSessionsByProject(ctx context.Context, projectID string) ([]Session, error)
	ListTeamMembers(ctx context.Context, teamID string) ([]AgentProfile, error)
	ListTeams(ctx context.Context) ([]Team, error)
	ListTeamsForAgent(ctx context.Context, agentProfileID string) ([]Team, error)
	ListUnfinishedRunsForSchedule(ctx context.Context, scheduleID string) ([]ScheduleRun, error)
	ListUnfinishedScheduleRuns(ctx context.Context) ([]ScheduleRun, error)
	ListUsers(ctx context.Context) ([]User, error)
	// Stamps everything this surface has now been shown, THROUGH the newest row it
	// was handed.
	//
	// Through a boundary rather than row by row, because a look is bounded and the
	// journal is not: stamping only the rows returned left a backlog larger than
	// one page unseen, so the next look answered with the next fifty OLDER entries
	// and announced last week as news. The boundary is the newest row of the look,
	// so what it means is "you are caught up to here" -- which is the only reading
	// that is monotonic in time.
	//
	// Already-stamped rows are left alone: a second surface's mark must not be
	// rewritten, and re-stamping the whole history on every look would be an
	// UPDATE over the table.
	MarkAssistantJournalSeenThrough(ctx context.Context, arg MarkAssistantJournalSeenThroughParams) error
	MarkScheduleRunFired(ctx context.Context, arg MarkScheduleRunFiredParams) error
	MarkScheduleViewed(ctx context.Context, arg MarkScheduleViewedParams) error
	MaxTurnIndex(ctx context.Context, sessionID string) (int64, error)
	PruneScheduleRuns(ctx context.Context, arg PruneScheduleRunsParams) error
	RecoverStaleSessions(ctx context.Context) error
	RemoveChannelMember(ctx context.Context, arg RemoveChannelMemberParams) error
	RemoveSessionFromAllChannels(ctx context.Context, sessionID string) error
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	ReorderPromptTemplates(ctx context.Context, arg ReorderPromptTemplatesParams) error
	RequeueScheduleRun(ctx context.Context, arg RequeueScheduleRunParams) error
	ResolveScheduleRun(ctx context.Context, arg ResolveScheduleRunParams) (int64, error)
	// Two correlated subqueries rather than a join: the join read every event
	// row of every session in the project (117ms for one project on a live
	// database) where the turn count needs only the index and the cost only the
	// result rows.
	SessionSummariesByProject(ctx context.Context, projectID string) ([]SessionSummariesByProjectRow, error)
	SetAssistantChannel(ctx context.Context, arg SetAssistantChannelParams) error
	// Stamps the window the last digest covered, so the next one starts where it
	// finished. Written only by Digest.
	SetAssistantDigestAt(ctx context.Context, arg SetAssistantDigestAtParams) error
	SetAssistantFollowBriefed(ctx context.Context, arg SetAssistantFollowBriefedParams) error
	SetAssistantModel(ctx context.Context, arg SetAssistantModelParams) error
	// Records that a surface has looked. json_set on the existing object rather
	// than a rewrite, so two surfaces cannot overwrite each other's mark.
	//
	// The DO UPDATE clause uses ?1/?2 rather than sqlc.arg(): sqlc does NOT rewrite
	// a named parameter inside an upsert's DO UPDATE, it copies the text through,
	// and `sqlc.arg(surface)` reaching SQLite is a runtime error in a statement
	// whose failure this code only logs. The numbers are the same parameters the
	// VALUES clause names.
	SetAssistantSurfaceMark(ctx context.Context, arg SetAssistantSurfaceMarkParams) error
	SetHostPresentation(ctx context.Context, arg SetHostPresentationParams) error
	SetScheduleAttention(ctx context.Context, arg SetScheduleAttentionParams) error
	SetScheduleEnabled(ctx context.Context, arg SetScheduleEnabledParams) error
	SetScheduleFailures(ctx context.Context, arg SetScheduleFailuresParams) error
	SetScheduleRunOverdue(ctx context.Context, id string) error
	// Archiving releases the pin. Pinned means "keep this at the top" and archived
	// means "stow this away": a session cannot be both, and leaving the pin set kept
	// filed-away work sitting in the priority section. Clearing it here rather than
	// at each caller means no archive path (the RPC, a completing merge, a local
	// session's commit) can forget to.
	//
	// Keep this comment ASCII. sqlc expands `SELECT *` by byte offset, so a
	// multi-byte character anywhere in this file shifts those offsets and corrupts
	// the generated code for LATER queries.
	SetSessionArchived(ctx context.Context, id string) error
	// Stamps "agentique reclaimed this session's CLI; nobody stopped it". Written
	// by the idle-eviction sweep and by nothing else, because it is a claim about
	// what agentique DID -- a person's stop and a restart's reap both really did
	// end something, and must keep reading as a plain stop.
	//
	// The timestamp is a parameter rather than strftime('now') because the sweep
	// already knows when it claimed the session; it must be UTC RFC3339 seconds
	// ("2006-01-02T15:04:05Z") like every other timestamp here, since SQLite
	// compares TEXT lexicographically.
	SetSessionEvictedAt(ctx context.Context, arg SetSessionEvictedAtParams) error
	// Stamps "this finished while nobody was reading it". The timestamp is a
	// parameter rather than strftime('now') because the caller is the turn-end
	// seam, which already knows when the turn completed; it must be UTC RFC3339
	// seconds ("2006-01-02T15:04:05Z") like every other timestamp here, since
	// SQLite compares TEXT lexicographically.
	SetSessionUnseenCompletedAt(ctx context.Context, arg SetSessionUnseenCompletedAtParams) error
	SetVoiceSettings(ctx context.Context, arg SetVoiceSettingsParams) error
	SetWorktreeMerged(ctx context.Context, id string) error
	// What this server itself spent today, per provider, from its own turn results.
	// Deliberately NOT a scan of the CLI's transcripts: agentique is the thing that
	// ran these turns, so it already knows, and this answers for every provider
	// rather than only the one that writes JSONL.
	// 'now' is local (no 'utc' modifier) so "today" means the operator's day.
	TodaySpendByProvider(ctx context.Context) ([]TodaySpendByProviderRow, error)
	UnsetSessionArchived(ctx context.Context, id string) error
	UnsetWorktreeMerged(ctx context.Context, id string) error
	UpdateAgentProfile(ctx context.Context, arg UpdateAgentProfileParams) (AgentProfile, error)
	UpdateChannelName(ctx context.Context, arg UpdateChannelNameParams) error
	UpdateClaudeSessionID(ctx context.Context, arg UpdateClaudeSessionIDParams) error
	UpdateCredentialAfterLogin(ctx context.Context, arg UpdateCredentialAfterLoginParams) error
	UpdateDeliveryStatus(ctx context.Context, arg UpdateDeliveryStatusParams) error
	UpdateMachinePresentation(ctx context.Context, arg UpdateMachinePresentationParams) (int64, error)
	UpdateProjectBehaviorPresets(ctx context.Context, arg UpdateProjectBehaviorPresetsParams) (Project, error)
	UpdateProjectColor(ctx context.Context, arg UpdateProjectColorParams) (Project, error)
	UpdateProjectFavorite(ctx context.Context, arg UpdateProjectFavoriteParams) (Project, error)
	UpdateProjectFolder(ctx context.Context, arg UpdateProjectFolderParams) (Project, error)
	UpdateProjectIcon(ctx context.Context, arg UpdateProjectIconParams) (Project, error)
	UpdateProjectMaxSessions(ctx context.Context, arg UpdateProjectMaxSessionsParams) (Project, error)
	UpdateProjectName(ctx context.Context, arg UpdateProjectNameParams) (Project, error)
	UpdateProjectPinned(ctx context.Context, arg UpdateProjectPinnedParams) (Project, error)
	UpdateProjectRemoteURL(ctx context.Context, arg UpdateProjectRemoteURLParams) error
	UpdateProjectSlug(ctx context.Context, arg UpdateProjectSlugParams) (Project, error)
	UpdateProjectSortOrder(ctx context.Context, arg UpdateProjectSortOrderParams) error
	UpdatePromptTemplate(ctx context.Context, arg UpdatePromptTemplateParams) (PromptTemplate, error)
	UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) error
	UpdateScheduleNextRun(ctx context.Context, arg UpdateScheduleNextRunParams) error
	UpdateSessionAutoApproveMode(ctx context.Context, arg UpdateSessionAutoApproveModeParams) error
	UpdateSessionBehaviorPresets(ctx context.Context, arg UpdateSessionBehaviorPresetsParams) error
	UpdateSessionLastQueryAt(ctx context.Context, id string) error
	// Changing the requested slug discards what the old one resolved to, stamp and
	// all: the pair describes a reading, and half a reading is worse than none.
	UpdateSessionModel(ctx context.Context, arg UpdateSessionModelParams) error
	UpdateSessionName(ctx context.Context, arg UpdateSessionNameParams) error
	UpdateSessionPRUrl(ctx context.Context, arg UpdateSessionPRUrlParams) error
	UpdateSessionPermissionMode(ctx context.Context, arg UpdateSessionPermissionModeParams) error
	UpdateSessionPinned(ctx context.Context, arg UpdateSessionPinnedParams) (Session, error)
	UpdateSessionResolvedModel(ctx context.Context, arg UpdateSessionResolvedModelParams) error
	UpdateSessionState(ctx context.Context, arg UpdateSessionStateParams) error
	UpdateSessionWorktree(ctx context.Context, arg UpdateSessionWorktreeParams) error
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
	UpdateUserSidebarFocusMode(ctx context.Context, arg UpdateUserSidebarFocusModeParams) error
	UpdateWorktreeBaseSHA(ctx context.Context, arg UpdateWorktreeBaseSHAParams) error
	UpsertAssistantFollow(ctx context.Context, arg UpsertAssistantFollowParams) error
	// platform_os keeps its stored value when the caller sends empty: a client
	// that predates the field re-upserts rows on re-pair, and blanking a known
	// platform would strip the glyph until the next fresh pair.
	UpsertMachine(ctx context.Context, arg UpsertMachineParams) error
	UpsertModelResolution(ctx context.Context, arg UpsertModelResolutionParams) error
	UseInviteToken(ctx context.Context, arg UseInviteTokenParams) error
}

var _ Querier = (*Queries)(nil)
