// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddChannelMember(ctx context.Context, arg AddChannelMemberParams) error
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error
	AdvanceScheduleNextRunIfEnabled(ctx context.Context, arg AdvanceScheduleNextRunIfEnabledParams) (int64, error)
	AllSessionSummaries(ctx context.Context) ([]AllSessionSummariesRow, error)
	AppendScheduleRunLateReport(ctx context.Context, arg AppendScheduleRunLateReportParams) error
	ClaimScheduleRun(ctx context.Context, id string) (int64, error)
	ClearScheduleActionAttention(ctx context.Context, arg ClearScheduleActionAttentionParams) error
	// The mark describes the MOST RECENT stop, so resuming clears it: a session
	// that has run since is no longer a session agentique reclaimed. Also the
	// release path when the stop behind a claim fails and the session stays alive.
	ClearSessionEvictedAt(ctx context.Context, id string) error
	// The read receipt. Idempotent by construction: clearing an already-clear row
	// touches nothing the client can see.
	ClearSessionUnseenCompletedAt(ctx context.Context, id string) error
	ConsumePairingToken(ctx context.Context, tokenHash string) (PairingToken, error)
	CountActiveSessionsByProject(ctx context.Context, projectID string) (int64, error)
	// Whether this day has already been folded.
	//
	// The pass inserts the summary BEFORE it deletes the rows it was written from,
	// so a pass that dies between the two leaves a day holding both -- and the next
	// pass has to delete the leftovers without paying for a second summary. This is
	// what tells the two apart.
	CountAssistantDaySummaries(ctx context.Context, arg CountAssistantDaySummariesParams) (int64, error)
	// The shape of a WHOLE day: how many rows of each kind, and whether any of
	// them was agent-written.
	//
	// Read from the day rather than from what was rendered, and that is the point.
	// A summary's PROSE is written from at most the newest `maxCompactDayRows` of a
	// day, where the DELETE below takes every raw row -- so a busy day's payload
	// would otherwise describe two thousand rows and lose the rest of the day's
	// shape with nothing saying it had. `untrusted` is the same argument in the
	// safe direction: one untrusted row anywhere in the day makes the summary
	// untrusted, which is what the contract says ("when any folded row was").
	CountAssistantJournalRawKindsForDay(ctx context.Context, arg CountAssistantJournalRawKindsForDayParams) ([]CountAssistantJournalRawKindsForDayRow, error)
	// The heartbeat's gate: has anything happened since the last beat.
	//
	// The assistant's OWN heartbeat entries are excluded, and that exclusion is
	// what makes the gate able to close: a tick journals its verdict and stamps
	// the mark in the same second, so counting its own row would leave every
	// later tick with one entry to triage and a Haiku call to pay for it. The
	// lower boundary is inclusive, as the digest's is, on the same reasoning --
	// triaging one entry twice costs a tick, dropping one loses news.
	CountAssistantJournalSince(ctx context.Context, since string) (int64, error)
	// How many entries this surface has never been shown. The rail's notch reads
	// it once per connection; the journal pushes keep it current after that.
	//
	// Same exclusions, and here they are the load-bearing ones: a badge is a claim
	// on attention, so a heartbeat that ticks every fifteen minutes would put a
	// permanent notch on the assistant's row and teach the operator to ignore it.
	//
	// `day_summary` is left out for the other half of that rule: it is a row about
	// a fortnight ago, stamped at the day it is about, so it sorts to the BOTTOM of
	// every surface that renders the journal newest-first and is never what the
	// notch led the reader to. A fold of thirty days would claim thirty unread
	// things with nothing new to look at. The `compaction` row beside it is the one
	// that is news, and it stays counted (docs/assistant.md, M5 build notes).
	CountAssistantJournalUnseen(ctx context.Context, surface sql.NullString) (int64, error)
	// A policy's in-flight budget: how many of the sessions it created are still
	// unfinished. One count rather than a list intersected in Go, for the reason
	// CountPolicySessionsCreatedSince gives.
	//
	// "Unfinished" is 'not archived, not finished', which is the contract's own
	// wording -- and deliberately NOT the repo's 'active' triple beside this, which
	// also excludes 'stopped'. A stopped session is PARKED (CLAUDE.md): idle
	// eviction and a restart's reap both leave that state, the work is still there,
	// and the next message resumes it. Counting one as finished would hand a policy
	// its slot back after every server restart while the worktree and the branch it
	// was working on were still open. Filing it away (archiving) is what releases
	// the slot, because that is a person saying they are done with it.
	CountLiveSessionsForPolicy(ctx context.Context, arg CountLiveSessionsForPolicyParams) (int64, error)
	// Sessions the assistant created on paired machines since a stamp: the half of
	// the day ceiling the sessions table cannot see.
	CountPeerSessionsCreatedSince(ctx context.Context, since string) (int64, error)
	// A policy's day budget: how many sessions this standing instruction has
	// created since a stamp.
	//
	// Counted in SQL rather than by paging the journal into Go, and that is the
	// point rather than an optimisation. The page was 2000 rows over a fourteen-day
	// window and FAILED CLOSED when it filled, so a machine busy enough to journal
	// 143 entries a day would have refused every budgeted verb from then on, with
	// one log line to explain it. A count has no page to fill. Compaction (M5)
	// bounds the table now, but not this window: it folds only days OLDER than the
	// lookback, so a busy fortnight is still thousands of rows.
	//
	// The payload path is '$.policyId', which is `payloadPolicyID` in
	// internal/assistant: the key is spelled in both places, so a rename is two
	// edits or a budget that counts nothing.
	CountPolicySessionsCreatedSince(ctx context.Context, arg CountPolicySessionsCreatedSinceParams) (int64, error)
	CountSessionIntroductionsInChannel(ctx context.Context, arg CountSessionIntroductionsInChannelParams) (int64, error)
	// How many sessions of one origin were created since a stamp. The day cap's
	// backstop: the per-policy count comes from the journal, which names the
	// policy, and this is the total the assistant may have created in the window
	// whatever the journal says -- a journal write is logged rather than fatal, so
	// a lost entry must not be able to widen a budget.
	CountSessionsByOriginSince(ctx context.Context, arg CountSessionsByOriginSinceParams) (int64, error)
	CountTurnsBySession(ctx context.Context, sessionID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountWebAuthnCredentials(ctx context.Context) (int64, error)
	CreateAgentProfile(ctx context.Context, arg CreateAgentProfileParams) (AgentProfile, error)
	CreateAssistantChannel(ctx context.Context, arg CreateAssistantChannelParams) (Channel, error)
	CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) error
	CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error)
	CreateInviteToken(ctx context.Context, arg CreateInviteTokenParams) error
	CreatePairingToken(ctx context.Context, arg CreatePairingTokenParams) error
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreatePromptTemplate(ctx context.Context, arg CreatePromptTemplateParams) (PromptTemplate, error)
	// Scheduled loops (docs/scheduled-loops.md). All timestamps are UTC RFC3339
	// seconds precision ("2006-01-02T15:04:05Z"); '' means unset.
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error)
	CreateScheduleRun(ctx context.Context, arg CreateScheduleRunParams) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) error
	// The decision. Guarded on status = 'open' so two surfaces cannot both decide
	// one proposal: the second write touches nothing, and the caller re-reads the
	// row it did not change.
	//
	// It answers how many rows it changed, so the caller does not have to assume
	// the guard matched. Zero means somebody else settled this proposal first,
	// which is a different thing from the write failing -- and after an action has
	// already been performed, the difference is worth a log line that says which.
	DecideAssistantProposal(ctx context.Context, arg DecideAssistantProposalParams) (int64, error)
	DeleteAgentProfile(ctx context.Context, id string) error
	DeleteAllAuthSessions(ctx context.Context) error
	DeleteAllWebAuthnCredentials(ctx context.Context) error
	// Retention: a summary older than the keep window goes too.
	//
	// Ninety days, and the raw rows it folded are long gone -- which is why this
	// runs only on a pass that can also write summaries: deleting the one compact
	// record of the oldest days on a machine that cannot make any more would lose
	// them for nothing.
	DeleteAssistantDaySummariesBefore(ctx context.Context, before string) (int64, error)
	DeleteAssistantFollow(ctx context.Context, sessionID string) error
	// The fold itself: the day's raw rows go.
	//
	// Answers how many rows it removed, because that number is what the pass
	// reports and journals -- and it is the only count that is true after the fact,
	// where the one read before the delete is what the summary could see.
	DeleteAssistantJournalRawForDay(ctx context.Context, arg DeleteAssistantJournalRawForDayParams) (int64, error)
	DeleteAssistantPeerFollow(ctx context.Context, sessionID string) error
	DeleteAssistantPolicy(ctx context.Context, id string) error
	DeleteAuthSession(ctx context.Context, tokenHash string) error
	DeleteAuthSessionByID(ctx context.Context, id sql.NullString) (int64, error)
	DeleteBearerAuthSessionByIDAndUser(ctx context.Context, arg DeleteBearerAuthSessionByIDAndUserParams) (int64, error)
	DeleteChannel(ctx context.Context, id string) error
	DeleteExpiredAuthSessions(ctx context.Context) error
	DeleteExpiredPairingTokens(ctx context.Context) error
	DeleteMachine(ctx context.Context, machineID string) error
	DeleteMessagesByChannel(ctx context.Context, channelID string) error
	DeletePeerAuthSessionByIDAndUser(ctx context.Context, arg DeletePeerAuthSessionByIDAndUserParams) (int64, error)
	DeleteProject(ctx context.Context, id string) error
	DeletePromptTemplate(ctx context.Context, id string) error
	DeleteSchedule(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteTeam(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	// Lazy expiry, applied on a decide: an open proposal past its expiry is not an
	// offer any more. There is no timer behind this -- a proposal nobody looks at
	// costs nothing, and a sweep would be a second writer on a table whose whole
	// content is decisions.
	ExpireAssistantProposals(ctx context.Context, at string) error
	GetActiveSessionByAgentProfile(ctx context.Context, agentProfileID sql.NullString) (Session, error)
	GetAdminUser(ctx context.Context) (User, error)
	GetAgentProfile(ctx context.Context, id string) (AgentProfile, error)
	// The conversation, found without the state row. The oldest wins: if a second
	// one was ever created, the first is the one the history is in.
	GetAssistantChannel(ctx context.Context) (Channel, error)
	GetAssistantFollow(ctx context.Context, sessionID string) (AssistantFollow, error)
	GetAssistantPolicy(ctx context.Context, id string) (AssistantPolicy, error)
	GetAssistantProposal(ctx context.Context, id string) (AssistantProposal, error)
	// The assistant's state, journal, follow list and conversation channel.
	// See docs/assistant.md and migration 056.
	//
	// Keep this file ASCII. sqlc expands `SELECT *` by byte offset, so one
	// multi-byte character shifts those offsets and corrupts the generated code
	// for LATER queries.
	GetAssistantState(ctx context.Context) (AssistantState, error)
	GetAuthSession(ctx context.Context, tokenHash string) (GetAuthSessionRow, error)
	GetChannel(ctx context.Context, id string) (Channel, error)
	GetCredentialByID(ctx context.Context, id string) (WebauthnCredential, error)
	GetHostPresentation(ctx context.Context) (GetHostPresentationRow, error)
	GetInviteToken(ctx context.Context, tokenHash string) (InviteToken, error)
	GetMachine(ctx context.Context, machineID string) (Machine, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	// One learned mapping, for a session whose own run never reported a model: the
	// last_seen_at that comes back is what dates the answer.
	GetModelResolution(ctx context.Context, arg GetModelResolutionParams) (ModelResolution, error)
	// One open proposal for the same verb and the same target, if there is one.
	//
	// Asking twice for the same thing is one card, not two: a second row would
	// give the operator two buttons for one decision, and accepting either would
	// leave the other pointing at work already done.
	GetOpenAssistantProposalFor(ctx context.Context, arg GetOpenAssistantProposalForParams) (AssistantProposal, error)
	GetProject(ctx context.Context, id string) (Project, error)
	GetProjectBySlug(ctx context.Context, slug string) (Project, error)
	GetPromptTemplate(ctx context.Context, id string) (PromptTemplate, error)
	GetSchedule(ctx context.Context, id string) (Schedule, error)
	GetScheduleRun(ctx context.Context, id string) (ScheduleRun, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetSessionEvent(ctx context.Context, arg GetSessionEventParams) (SessionEvent, error)
	GetTeam(ctx context.Context, id string) (Team, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByDisplayName(ctx context.Context, displayName string) (User, error)
	GetVoiceSettings(ctx context.Context) (GetVoiceSettingsRow, error)
	InsertAssistantJournalEntry(ctx context.Context, arg InsertAssistantJournalEntryParams) (AssistantJournal, error)
	// One message of the conversation.
	//
	// Its own insert rather than InsertMessage because created_at is passed IN.
	// The table's default stamps milliseconds, and an ask and its reply can land
	// in the same millisecond -- at which point the only tiebreak left is the
	// uuid, and the two read back in no order at all. A fixed-width nanosecond
	// stamp sorts lexicographically, which for this column is the only kind of
	// sorting there is. Nothing else writes to an assistant channel, so the
	// sharper format is consistent within the timeline that reads it.
	InsertAssistantMessage(ctx context.Context, arg InsertAssistantMessageParams) (Message, error)
	// Proposals: the uncontained tier's card, and the record of its yes or no.
	// See docs/assistant.md's M3 contract and migration 057.
	InsertAssistantProposal(ctx context.Context, arg InsertAssistantProposalParams) (AssistantProposal, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	InsertEventWithMessageID(ctx context.Context, arg InsertEventWithMessageIDParams) error
	InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error)
	InsertMessageDelivery(ctx context.Context, arg InsertMessageDeliveryParams) error
	InsertPeerOutbox(ctx context.Context, arg InsertPeerOutboxParams) (int64, error)
	InsertPersonaInteraction(ctx context.Context, arg InsertPersonaInteractionParams) (PersonaInteraction, error)
	// The newest seq one follower has, 0 when it has none: what a follower that
	// has never read starts from when it wants news from now on rather than the
	// whole retention window.
	LatestPeerOutboxSeq(ctx context.Context, credentialID string) (int64, error)
	ListAgentMessagesByChannel(ctx context.Context, channelID string) ([]SessionEvent, error)
	ListAgentProfiles(ctx context.Context) ([]AgentProfile, error)
	ListAllSessions(ctx context.Context) ([]Session, error)
	ListAssistantFollows(ctx context.Context) ([]AssistantFollow, error)
	// Compaction: folding the journal's older days (docs/assistant.md, the M5
	// contract, and migration 060).
	//
	// Four reads and three writes, and one predicate runs through all of them: a
	// RAW row is every kind except 'day_summary' with notable = 0. Notable rows are
	// exempt and stay whole, and a summary is not raw or a second pass would fold
	// its own output. The predicate is spelled in each statement rather than in a
	// view, because sqlc generates from the statement and a view would hide which
	// rows a DELETE reaches.
	//
	// A day is `substr(at, 1, 10)`, the UTC date of the row's own stamp: `at` is
	// UTC RFC3339 seconds, so the first ten characters ARE the day and no date
	// function is needed. The trigger's "once a day" is a local-midnight question
	// and lives in Go; this is only which rows belong together.
	// Which days still have raw rows older than a stamp, oldest first.
	//
	// One row per day with its count, so the pass can order the days itself and
	// knows before it reads a day whether that day is past what one summary may be
	// written from. GROUP BY over a range rather than a DISTINCT of every row: a
	// fortnight of a busy machine is thousands of rows and thirty answers.
	ListAssistantJournalRawDaysBefore(ctx context.Context, arg ListAssistantJournalRawDaysBeforeParams) ([]ListAssistantJournalRawDaysBeforeRow, error)
	// One page of a day's raw rows, newest first.
	//
	// Paged with an (at, id) cursor rather than an offset, as the conversation's
	// history is: a day's rows are what the summary is written from, and an offset
	// over a table something else is writing to skips rows. An empty cursor starts
	// at the newest, which is also the end of the day the summary is written about.
	//
	// The cursor is spelled out rather than as the row value `(at, id) < (?, ?)`
	// the messages query uses, because sqlc cannot type a row value's parameters:
	// it emitted `interface{}` for the stamp and `string` for an INTEGER id, and an
	// id compared as text is an id compared by affinity luck.
	ListAssistantJournalRawForDay(ctx context.Context, arg ListAssistantJournalRawForDayParams) ([]AssistantJournal, error)
	// Every standing instruction a WHOLE day's raw rows named, in the order they
	// were first named.
	//
	// Same whole-day argument, and here it is the one that costs something: the
	// `policies` key exists so a longer budget lookback can find a folded day's
	// spending, and a list built from the newest two thousand rows would be a list
	// with the oldest ids silently missing. The payload path is '$.policyId',
	// which is `payloadPolicyID` in internal/assistant.
	ListAssistantJournalRawPolicyIDsForDay(ctx context.Context, arg ListAssistantJournalRawPolicyIDsForDayParams) ([]string, error)
	ListAssistantJournalSince(ctx context.Context, arg ListAssistantJournalSinceParams) ([]AssistantJournal, error)
	// What a surface has missed. 'heartbeat' rows are left out, for the same reason
	// the digest and the head's news leave them out: a tick that woke up, looked and
	// decided nothing is the assistant's own bookkeeping, and what it DID has its
	// own entry beside it. They stay in ListAssistantJournalSince, which is the
	// journal page and the audit trail for every model the heartbeat paid for.
	ListAssistantJournalUnseen(ctx context.Context, arg ListAssistantJournalUnseenParams) ([]AssistantJournal, error)
	// One page of the conversation, newest first. An empty `before` starts at the
	// newest message; otherwise it is a created_at cursor.
	//
	// rowid breaks the tie, not id. messages.created_at has millisecond precision
	// and a message's id is a uuid, so two turns written in the same millisecond --
	// an ask and a mirrored reply -- would come back in uuid order, which is to say
	// in no order. rowid is insertion order, which is the order they were said in.
	ListAssistantMessagesBefore(ctx context.Context, arg ListAssistantMessagesBeforeParams) ([]Message, error)
	// What has been said in the conversation since a surface last looked, oldest
	// first: this is read to be pasted into a preamble or a strip, in order.
	ListAssistantMessagesSince(ctx context.Context, arg ListAssistantMessagesSinceParams) ([]Message, error)
	ListAssistantPeerFollows(ctx context.Context) ([]AssistantPeerFollow, error)
	// Standing instructions and the heartbeat's mark (docs/assistant.md, the M4
	// contract, and migration 059).
	// Name order, so the list a person reads and the list the heartbeat reads are
	// in the same order. The id breaks a tie between two policies named the same.
	ListAssistantPolicies(ctx context.Context) ([]AssistantPolicy, error)
	// Open first, then whatever was decided, newest first within each half. A
	// surface renders the open ones as cards and the rest as history, and one read
	// answers both.
	ListAssistantProposals(ctx context.Context, lim int64) ([]AssistantProposal, error)
	ListAuthSessions(ctx context.Context) ([]ListAuthSessionsRow, error)
	ListChannelMemberSessions(ctx context.Context, channelID string) ([]ListChannelMemberSessionsRow, error)
	// Ordinary channels only. The assistant's conversation is a channel with
	// kind = 'assistant' and is not one of a project's channels: it has no project,
	// it has no roster, and a row for it in the channel list would offer every
	// channel gesture (dissolve, add a member) against the thread.
	ListChannelsByProject(ctx context.Context, projectID sql.NullString) ([]Channel, error)
	ListChildSessions(ctx context.Context, parentSessionID sql.NullString) ([]Session, error)
	ListCredentialsByUser(ctx context.Context, userID string) ([]WebauthnCredential, error)
	ListDueSchedules(ctx context.Context, nextRunAt string) ([]Schedule, error)
	ListEnabledSchedulesBySession(ctx context.Context, sessionID string) ([]Schedule, error)
	ListEventsBySession(ctx context.Context, sessionID string) ([]SessionEvent, error)
	ListInviteTokens(ctx context.Context, createdBy string) ([]InviteToken, error)
	ListMachines(ctx context.Context) ([]Machine, error)
	ListMessagesByChannel(ctx context.Context, channelID string) ([]Message, error)
	ListModelResolutions(ctx context.Context) ([]ModelResolution, error)
	ListPeerFollowers(ctx context.Context, sessionID string) ([]string, error)
	ListPeerOutboxSince(ctx context.Context, arg ListPeerOutboxSinceParams) ([]ListPeerOutboxSinceRow, error)
	// A policy's sessions created on PAIRED machines in a window: the half of its
	// in-flight budget this server's sessions table cannot see (docs/peers.md).
	// Rows, not a count, because whether each is unfinished is that machine's
	// answer; a policy's budget keeps the list short.
	ListPeerPolicySessionsCreatedSince(ctx context.Context, arg ListPeerPolicySessionsCreatedSinceParams) ([]ListPeerPolicySessionsCreatedSinceRow, error)
	ListPendingDeliveriesForSession(ctx context.Context, recipientSessionID string) ([]ListPendingDeliveriesForSessionRow, error)
	ListPersonaInteractions(ctx context.Context, arg ListPersonaInteractionsParams) ([]PersonaInteraction, error)
	ListPersonaInteractionsForProfile(ctx context.Context, arg ListPersonaInteractionsForProfileParams) ([]PersonaInteraction, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListPromptTemplates(ctx context.Context) ([]PromptTemplate, error)
	ListQueuedRunsBySession(ctx context.Context, sessionID string) ([]ScheduleRun, error)
	ListRecentActivityByProject(ctx context.Context, arg ListRecentActivityByProjectParams) ([]ListRecentActivityByProjectRow, error)
	ListRecentActivityGlobal(ctx context.Context, arg ListRecentActivityGlobalParams) ([]ListRecentActivityGlobalRow, error)
	ListRecentEventsBySession(ctx context.Context, arg ListRecentEventsBySessionParams) ([]SessionEvent, error)
	ListRunsSince(ctx context.Context, arg ListRunsSinceParams) (ListRunsSinceRow, error)
	ListScheduleRuns(ctx context.Context, arg ListScheduleRunsParams) ([]ScheduleRun, error)
	ListSchedules(ctx context.Context) ([]Schedule, error)
	ListSchedulesBySession(ctx context.Context, sessionID string) ([]Schedule, error)
	ListSessionChannels(ctx context.Context, sessionID string) ([]ListSessionChannelsRow, error)
	// The session.state observer's baseline: what every session's two outcome
	// facts already were before the observer started watching. A push is a whole
	// snapshot, not a transition, so without this the first push for a session
	// archived last month reads as news -- and on the first boot with the
	// assistant on, that was one entry per archived session ever.
	ListSessionOutcomeBaseline(ctx context.Context) ([]ListSessionOutcomeBaselineRow, error)
	ListSessionsByProject(ctx context.Context, projectID string) ([]Session, error)
	ListTeamMembers(ctx context.Context, teamID string) ([]AgentProfile, error)
	ListTeams(ctx context.Context) ([]Team, error)
	ListTeamsForAgent(ctx context.Context, agentProfileID string) ([]Team, error)
	ListUnfinishedRunsForSchedule(ctx context.Context, scheduleID string) ([]ScheduleRun, error)
	ListUnfinishedScheduleRuns(ctx context.Context) ([]ScheduleRun, error)
	ListUsers(ctx context.Context) ([]User, error)
	// Stamps everything this surface has now been shown, THROUGH the newest row it
	// was handed.
	//
	// Through a boundary rather than row by row, because a look is bounded and the
	// journal is not: stamping only the rows returned left a backlog larger than
	// one page unseen, so the next look answered with the next fifty OLDER entries
	// and announced last week as news. The boundary is the newest row of the look,
	// so what it means is "you are caught up to here" -- which is the only reading
	// that is monotonic in time.
	//
	// Already-stamped rows are left alone: a second surface's mark must not be
	// rewritten, and re-stamping the whole history on every look would be an
	// UPDATE over the table.
	MarkAssistantJournalSeenThrough(ctx context.Context, arg MarkAssistantJournalSeenThroughParams) error
	MarkScheduleRunFired(ctx context.Context, arg MarkScheduleRunFiredParams) error
	MarkScheduleViewed(ctx context.Context, arg MarkScheduleViewedParams) error
	MaxTurnIndex(ctx context.Context, sessionID string) (int64, error)
	PrunePeerOutbox(ctx context.Context, at string) (int64, error)
	PruneScheduleRuns(ctx context.Context, arg PruneScheduleRunsParams) error
	RecoverStaleSessions(ctx context.Context) error
	RemoveChannelMember(ctx context.Context, arg RemoveChannelMemberParams) error
	RemoveSessionFromAllChannels(ctx context.Context, sessionID string) error
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	ReorderPromptTemplates(ctx context.Context, arg ReorderPromptTemplatesParams) error
	RequeueScheduleRun(ctx context.Context, arg RequeueScheduleRunParams) error
	ResolveScheduleRun(ctx context.Context, arg ResolveScheduleRunParams) (int64, error)
	// Two correlated subqueries rather than a join: the join read every event
	// row of every session in the project (117ms for one project on a live
	// database) where the turn count needs only the index and the cost only the
	// result rows.
	SessionSummariesByProject(ctx context.Context, projectID string) ([]SessionSummariesByProjectRow, error)
	SetAssistantChannel(ctx context.Context, arg SetAssistantChannelParams) error
	// When the journal was last folded. Stamped BEFORE the pass runs, so a pass
	// that fails is retried tomorrow rather than on every tick for the rest of the
	// day.
	SetAssistantCompactedAt(ctx context.Context, arg SetAssistantCompactedAtParams) error
	// Stamps the window the last digest covered, so the next one starts where it
	// finished. Written only by Digest.
	SetAssistantDigestAt(ctx context.Context, arg SetAssistantDigestAtParams) error
	SetAssistantFollowBriefed(ctx context.Context, arg SetAssistantFollowBriefedParams) error
	// The heartbeat's mark: when the last tick measured from. Stamped by every
	// tick, including the ones that ran no model at all.
	SetAssistantHeartbeatAt(ctx context.Context, arg SetAssistantHeartbeatAtParams) error
	SetAssistantModel(ctx context.Context, arg SetAssistantModelParams) error
	// Records that a surface has looked. json_set on the existing object rather
	// than a rewrite, so two surfaces cannot overwrite each other's mark.
	//
	// The DO UPDATE clause uses ?1/?2 rather than sqlc.arg(): sqlc does NOT rewrite
	// a named parameter inside an upsert's DO UPDATE, it copies the text through,
	// and `sqlc.arg(surface)` reaching SQLite is a runtime error in a statement
	// whose failure this code only logs. The numbers are the same parameters the
	// VALUES clause names.
	SetAssistantSurfaceMark(ctx context.Context, arg SetAssistantSurfaceMarkParams) error
	SetHostPresentation(ctx context.Context, arg SetHostPresentationParams) error
	SetMachinePeerCredential(ctx context.Context, arg SetMachinePeerCredentialParams) (int64, error)
	SetMachinePeerCursor(ctx context.Context, arg SetMachinePeerCursorParams) (int64, error)
	SetScheduleAttention(ctx context.Context, arg SetScheduleAttentionParams) error
	SetScheduleEnabled(ctx context.Context, arg SetScheduleEnabledParams) error
	SetScheduleFailures(ctx context.Context, arg SetScheduleFailuresParams) error
	SetScheduleRunOverdue(ctx context.Context, id string) error
	// Archiving releases the pin. Pinned means "keep this at the top" and archived
	// means "stow this away": a session cannot be both, and leaving the pin set kept
	// filed-away work sitting in the priority section. Clearing it here rather than
	// at each caller means no archive path (the RPC, a completing merge, a local
	// session's commit) can forget to.
	//
	// Keep this comment ASCII. sqlc expands `SELECT *` by byte offset, so a
	// multi-byte character anywhere in this file shifts those offsets and corrupts
	// the generated code for LATER queries.
	SetSessionArchived(ctx context.Context, id string) error
	// Stamps "agentique reclaimed this session's CLI; nobody stopped it". Written
	// by the idle-eviction sweep and by nothing else, because it is a claim about
	// what agentique DID -- a person's stop and a restart's reap both really did
	// end something, and must keep reading as a plain stop.
	//
	// The timestamp is a parameter rather than strftime('now') because the sweep
	// already knows when it claimed the session; it must be UTC RFC3339 seconds
	// ("2006-01-02T15:04:05Z") like every other timestamp here, since SQLite
	// compares TEXT lexicographically.
	SetSessionEvictedAt(ctx context.Context, arg SetSessionEvictedAtParams) error
	// Where a session came from (docs/assistant.md, the M4 contract, and migration
	// 059). '' is a person's, 'assistant' is the assistant's own.
	// The one writer, called from INSIDE CreateSession (from CreateSessionParams.
	// Origin) before the session.created push is built, so a client never draws an
	// assistant's session as a person's and correct it on the next list. Every
	// other creation path leaves the parameter at its zero value, which is '' --
	// a person asked.
	SetSessionOrigin(ctx context.Context, arg SetSessionOriginParams) error
	// Stamps "this finished while nobody was reading it". The timestamp is a
	// parameter rather than strftime('now') because the caller is the turn-end
	// seam, which already knows when the turn completed; it must be UTC RFC3339
	// seconds ("2006-01-02T15:04:05Z") like every other timestamp here, since
	// SQLite compares TEXT lexicographically.
	SetSessionUnseenCompletedAt(ctx context.Context, arg SetSessionUnseenCompletedAtParams) error
	SetVoiceSettings(ctx context.Context, arg SetVoiceSettingsParams) error
	SetWorktreeMerged(ctx context.Context, id string) error
	// What this server itself spent today, per provider, from its own turn results.
	// Deliberately NOT a scan of the CLI's transcripts: agentique is the thing that
	// ran these turns, so it already knows, and this answers for every provider
	// rather than only the one that writes JSONL.
	// 'now' is local (no 'utc' modifier) so "today" means the operator's day.
	TodaySpendByProvider(ctx context.Context) ([]TodaySpendByProviderRow, error)
	// When the heartbeat last acted under this policy. Bookkeeping the operator
	// reads, never a budget: what a budget counts is journal entries, which an
	// edit cannot rewrite.
	TouchAssistantPolicy(ctx context.Context, arg TouchAssistantPolicyParams) error
	UnsetSessionArchived(ctx context.Context, id string) error
	UnsetWorktreeMerged(ctx context.Context, id string) error
	UpdateAgentProfile(ctx context.Context, arg UpdateAgentProfileParams) (AgentProfile, error)
	UpdateChannelName(ctx context.Context, arg UpdateChannelNameParams) error
	UpdateClaudeSessionID(ctx context.Context, arg UpdateClaudeSessionIDParams) error
	UpdateCredentialAfterLogin(ctx context.Context, arg UpdateCredentialAfterLoginParams) error
	UpdateDeliveryStatus(ctx context.Context, arg UpdateDeliveryStatusParams) error
	UpdateMachinePresentation(ctx context.Context, arg UpdateMachinePresentationParams) (int64, error)
	UpdateProjectBehaviorPresets(ctx context.Context, arg UpdateProjectBehaviorPresetsParams) (Project, error)
	UpdateProjectColor(ctx context.Context, arg UpdateProjectColorParams) (Project, error)
	UpdateProjectFavorite(ctx context.Context, arg UpdateProjectFavoriteParams) (Project, error)
	UpdateProjectFolder(ctx context.Context, arg UpdateProjectFolderParams) (Project, error)
	UpdateProjectIcon(ctx context.Context, arg UpdateProjectIconParams) (Project, error)
	UpdateProjectMaxSessions(ctx context.Context, arg UpdateProjectMaxSessionsParams) (Project, error)
	UpdateProjectName(ctx context.Context, arg UpdateProjectNameParams) (Project, error)
	UpdateProjectPinned(ctx context.Context, arg UpdateProjectPinnedParams) (Project, error)
	UpdateProjectRemoteURL(ctx context.Context, arg UpdateProjectRemoteURLParams) error
	UpdateProjectSlug(ctx context.Context, arg UpdateProjectSlugParams) (Project, error)
	UpdateProjectSortOrder(ctx context.Context, arg UpdateProjectSortOrderParams) error
	UpdatePromptTemplate(ctx context.Context, arg UpdatePromptTemplateParams) (PromptTemplate, error)
	UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) error
	UpdateScheduleNextRun(ctx context.Context, arg UpdateScheduleNextRunParams) error
	UpdateSessionAutoApproveMode(ctx context.Context, arg UpdateSessionAutoApproveModeParams) error
	UpdateSessionBehaviorPresets(ctx context.Context, arg UpdateSessionBehaviorPresetsParams) error
	UpdateSessionLastQueryAt(ctx context.Context, id string) error
	// Changing the requested slug discards what the old one resolved to, stamp and
	// all: the pair describes a reading, and half a reading is worse than none.
	UpdateSessionModel(ctx context.Context, arg UpdateSessionModelParams) error
	UpdateSessionName(ctx context.Context, arg UpdateSessionNameParams) error
	UpdateSessionPRUrl(ctx context.Context, arg UpdateSessionPRUrlParams) error
	UpdateSessionPermissionMode(ctx context.Context, arg UpdateSessionPermissionModeParams) error
	UpdateSessionPinned(ctx context.Context, arg UpdateSessionPinnedParams) (Session, error)
	UpdateSessionResolvedModel(ctx context.Context, arg UpdateSessionResolvedModelParams) error
	UpdateSessionState(ctx context.Context, arg UpdateSessionStateParams) error
	UpdateSessionWorktree(ctx context.Context, arg UpdateSessionWorktreeParams) error
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
	UpdateUserSidebarFocusMode(ctx context.Context, arg UpdateUserSidebarFocusModeParams) error
	UpdateWorktreeBaseSHA(ctx context.Context, arg UpdateWorktreeBaseSHAParams) error
	UpsertAssistantFollow(ctx context.Context, arg UpsertAssistantFollowParams) error
	UpsertAssistantPeerFollow(ctx context.Context, arg UpsertAssistantPeerFollowParams) error
	// One statement for a new policy and an edit, because the client sends the
	// whole row either way: a policy is one form with a Save button, and a
	// partial update would need a field-by-field patch nobody asked for.
	// created_at is left alone on an edit, so a row keeps the day it was written.
	UpsertAssistantPolicy(ctx context.Context, arg UpsertAssistantPolicyParams) (AssistantPolicy, error)
	// platform_os keeps its stored value when the caller sends empty: a client
	// that predates the field re-upserts rows on re-pair, and blanking a known
	// platform would strip the glyph until the next fresh pair.
	UpsertMachine(ctx context.Context, arg UpsertMachineParams) error
	UpsertModelResolution(ctx context.Context, arg UpsertModelResolutionParams) error
	UpsertPeerFollow(ctx context.Context, arg UpsertPeerFollowParams) error
	UseInviteToken(ctx context.Context, arg UseInviteTokenParams) error
}

var _ Querier = (*Queries)(nil)
