// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddChannelMember(ctx context.Context, arg AddChannelMemberParams) error
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error
	AllSessionSummaries(ctx context.Context) ([]AllSessionSummariesRow, error)
	CountActiveSessionsByProject(ctx context.Context, projectID string) (int64, error)
	CountSessionIntroductionsInChannel(ctx context.Context, arg CountSessionIntroductionsInChannelParams) (int64, error)
	CountTurnsBySession(ctx context.Context, sessionID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountWebAuthnCredentials(ctx context.Context) (int64, error)
	CreateAgentProfile(ctx context.Context, arg CreateAgentProfileParams) (AgentProfile, error)
	CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) error
	CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error)
	CreateInviteToken(ctx context.Context, arg CreateInviteTokenParams) error
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreatePromptTemplate(ctx context.Context, arg CreatePromptTemplateParams) (PromptTemplate, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) error
	DeleteAgentProfile(ctx context.Context, id string) error
	DeleteAllAuthSessions(ctx context.Context) error
	DeleteAllWebAuthnCredentials(ctx context.Context) error
	DeleteAuthSession(ctx context.Context, token string) error
	DeleteChannel(ctx context.Context, id string) error
	DeleteExpiredAuthSessions(ctx context.Context) error
	DeleteMessagesByChannel(ctx context.Context, channelID string) error
	DeleteProject(ctx context.Context, id string) error
	DeletePromptTemplate(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteTeam(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	GetActiveSessionByAgentProfile(ctx context.Context, agentProfileID sql.NullString) (Session, error)
	GetAgentProfile(ctx context.Context, id string) (AgentProfile, error)
	GetAuthSession(ctx context.Context, token string) (GetAuthSessionRow, error)
	GetChannel(ctx context.Context, id string) (Channel, error)
	GetCredentialByID(ctx context.Context, id string) (WebauthnCredential, error)
	GetInviteToken(ctx context.Context, token string) (InviteToken, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetProject(ctx context.Context, id string) (Project, error)
	GetProjectBySlug(ctx context.Context, slug string) (Project, error)
	GetPromptTemplate(ctx context.Context, id string) (PromptTemplate, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetTeam(ctx context.Context, id string) (Team, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByDisplayName(ctx context.Context, displayName string) (User, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	InsertEventWithMessageID(ctx context.Context, arg InsertEventWithMessageIDParams) error
	InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error)
	InsertMessageDelivery(ctx context.Context, arg InsertMessageDeliveryParams) error
	InsertPersonaInteraction(ctx context.Context, arg InsertPersonaInteractionParams) (PersonaInteraction, error)
	ListAgentMessagesByChannel(ctx context.Context, channelID string) ([]SessionEvent, error)
	ListAgentProfiles(ctx context.Context) ([]AgentProfile, error)
	ListAllSessions(ctx context.Context) ([]Session, error)
	ListChannelMemberSessions(ctx context.Context, channelID string) ([]ListChannelMemberSessionsRow, error)
	ListChannelsByProject(ctx context.Context, projectID string) ([]Channel, error)
	ListCredentialsByUser(ctx context.Context, userID string) ([]WebauthnCredential, error)
	ListEventsBySession(ctx context.Context, sessionID string) ([]SessionEvent, error)
	ListInviteTokens(ctx context.Context, createdBy string) ([]InviteToken, error)
	ListMessagesByChannel(ctx context.Context, channelID string) ([]Message, error)
	ListPendingDeliveriesForSession(ctx context.Context, recipientSessionID string) ([]ListPendingDeliveriesForSessionRow, error)
	ListPersonaInteractions(ctx context.Context, arg ListPersonaInteractionsParams) ([]PersonaInteraction, error)
	ListPersonaInteractionsForProfile(ctx context.Context, arg ListPersonaInteractionsForProfileParams) ([]PersonaInteraction, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListPromptTemplates(ctx context.Context) ([]PromptTemplate, error)
	ListRecentActivityByProject(ctx context.Context, arg ListRecentActivityByProjectParams) ([]ListRecentActivityByProjectRow, error)
	ListRecentEventsBySession(ctx context.Context, arg ListRecentEventsBySessionParams) ([]SessionEvent, error)
	ListSessionChannels(ctx context.Context, sessionID string) ([]ListSessionChannelsRow, error)
	ListSessionsByProject(ctx context.Context, projectID string) ([]Session, error)
	ListTeamMembers(ctx context.Context, teamID string) ([]AgentProfile, error)
	ListTeams(ctx context.Context) ([]Team, error)
	ListTeamsForAgent(ctx context.Context, agentProfileID string) ([]Team, error)
	ListUsers(ctx context.Context) ([]User, error)
	MaxTurnIndex(ctx context.Context, sessionID string) (int64, error)
	RecoverStaleSessions(ctx context.Context) error
	RemoveChannelMember(ctx context.Context, arg RemoveChannelMemberParams) error
	RemoveSessionFromAllChannels(ctx context.Context, sessionID string) error
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	ReorderPromptTemplates(ctx context.Context, arg ReorderPromptTemplatesParams) error
	SessionSummariesByProject(ctx context.Context, projectID string) ([]SessionSummariesByProjectRow, error)
	SetSessionCompleted(ctx context.Context, id string) error
	SetWorktreeMerged(ctx context.Context, id string) error
	UnsetSessionCompleted(ctx context.Context, id string) error
	UnsetWorktreeMerged(ctx context.Context, id string) error
	UpdateAgentProfile(ctx context.Context, arg UpdateAgentProfileParams) (AgentProfile, error)
	UpdateChannelName(ctx context.Context, arg UpdateChannelNameParams) error
	UpdateClaudeSessionID(ctx context.Context, arg UpdateClaudeSessionIDParams) error
	UpdateCredentialAfterLogin(ctx context.Context, arg UpdateCredentialAfterLoginParams) error
	UpdateDeliveryStatus(ctx context.Context, arg UpdateDeliveryStatusParams) error
	UpdateProjectBehaviorPresets(ctx context.Context, arg UpdateProjectBehaviorPresetsParams) (Project, error)
	UpdateProjectColor(ctx context.Context, arg UpdateProjectColorParams) (Project, error)
	UpdateProjectFavorite(ctx context.Context, arg UpdateProjectFavoriteParams) (Project, error)
	UpdateProjectFolder(ctx context.Context, arg UpdateProjectFolderParams) (Project, error)
	UpdateProjectIcon(ctx context.Context, arg UpdateProjectIconParams) (Project, error)
	UpdateProjectMaxSessions(ctx context.Context, arg UpdateProjectMaxSessionsParams) (Project, error)
	UpdateProjectName(ctx context.Context, arg UpdateProjectNameParams) (Project, error)
	UpdateProjectSlug(ctx context.Context, arg UpdateProjectSlugParams) (Project, error)
	UpdateProjectSortOrder(ctx context.Context, arg UpdateProjectSortOrderParams) error
	UpdatePromptTemplate(ctx context.Context, arg UpdatePromptTemplateParams) (PromptTemplate, error)
	UpdateSessionAutoApproveMode(ctx context.Context, arg UpdateSessionAutoApproveModeParams) error
	UpdateSessionLastQueryAt(ctx context.Context, id string) error
	UpdateSessionModel(ctx context.Context, arg UpdateSessionModelParams) error
	UpdateSessionName(ctx context.Context, arg UpdateSessionNameParams) error
	UpdateSessionPRUrl(ctx context.Context, arg UpdateSessionPRUrlParams) error
	UpdateSessionPermissionMode(ctx context.Context, arg UpdateSessionPermissionModeParams) error
	UpdateSessionState(ctx context.Context, arg UpdateSessionStateParams) error
	UpdateSessionWorktree(ctx context.Context, arg UpdateSessionWorktreeParams) error
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
	UpdateWorktreeBaseSHA(ctx context.Context, arg UpdateWorktreeBaseSHAParams) error
	UseInviteToken(ctx context.Context, arg UseInviteTokenParams) error
}

var _ Querier = (*Queries)(nil)
