// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedules.sql

package store

import (
	"context"
)

const advanceScheduleNextRunIfEnabled = `-- name: AdvanceScheduleNextRunIfEnabled :execrows
UPDATE schedules SET next_run_at = ?, last_run_at = ?, updated_at = ?
WHERE id = ? AND enabled = 1
`

type AdvanceScheduleNextRunIfEnabledParams struct {
	NextRunAt string `json:"next_run_at"`
	LastRunAt string `json:"last_run_at"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) AdvanceScheduleNextRunIfEnabled(ctx context.Context, arg AdvanceScheduleNextRunIfEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceScheduleNextRunIfEnabled,
		arg.NextRunAt,
		arg.LastRunAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const appendScheduleRunLateReport = `-- name: AppendScheduleRunLateReport :exec
UPDATE schedule_runs SET late_report = ? WHERE id = ?
`

type AppendScheduleRunLateReportParams struct {
	LateReport string `json:"late_report"`
	ID         string `json:"id"`
}

func (q *Queries) AppendScheduleRunLateReport(ctx context.Context, arg AppendScheduleRunLateReportParams) error {
	_, err := q.db.ExecContext(ctx, appendScheduleRunLateReport, arg.LateReport, arg.ID)
	return err
}

const claimScheduleRun = `-- name: ClaimScheduleRun :execrows
UPDATE schedule_runs SET status = 'firing' WHERE id = ? AND status = 'queued'
`

func (q *Queries) ClaimScheduleRun(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimScheduleRun, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearScheduleActionAttention = `-- name: ClearScheduleActionAttention :exec
UPDATE schedules
SET attention = '', attention_run_id = '', updated_at = ?
WHERE id = ? AND attention = 'action_needed'
`

type ClearScheduleActionAttentionParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) ClearScheduleActionAttention(ctx context.Context, arg ClearScheduleActionAttentionParams) error {
	_, err := q.db.ExecContext(ctx, clearScheduleActionAttention, arg.UpdatedAt, arg.ID)
	return err
}

const createSchedule = `-- name: CreateSchedule :one

INSERT INTO schedules (
    id, project_id, session_id, name, prompt, cron, mode, enabled,
    pause_reason, next_run_at, expires_at, created_by, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, session_id, name, prompt, cron, mode, enabled, pause_reason, attention, attention_run_id, next_run_at, expires_at, last_run_at, last_viewed_at, consecutive_failures, created_by, created_at, updated_at
`

type CreateScheduleParams struct {
	ID          string `json:"id"`
	ProjectID   string `json:"project_id"`
	SessionID   string `json:"session_id"`
	Name        string `json:"name"`
	Prompt      string `json:"prompt"`
	Cron        string `json:"cron"`
	Mode        string `json:"mode"`
	Enabled     int64  `json:"enabled"`
	PauseReason string `json:"pause_reason"`
	NextRunAt   string `json:"next_run_at"`
	ExpiresAt   string `json:"expires_at"`
	CreatedBy   string `json:"created_by"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

// Scheduled loops (docs/scheduled-loops.md). All timestamps are UTC RFC3339
// seconds precision ("2006-01-02T15:04:05Z"); ” means unset.
func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, createSchedule,
		arg.ID,
		arg.ProjectID,
		arg.SessionID,
		arg.Name,
		arg.Prompt,
		arg.Cron,
		arg.Mode,
		arg.Enabled,
		arg.PauseReason,
		arg.NextRunAt,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SessionID,
		&i.Name,
		&i.Prompt,
		&i.Cron,
		&i.Mode,
		&i.Enabled,
		&i.PauseReason,
		&i.Attention,
		&i.AttentionRunID,
		&i.NextRunAt,
		&i.ExpiresAt,
		&i.LastRunAt,
		&i.LastViewedAt,
		&i.ConsecutiveFailures,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createScheduleRun = `-- name: CreateScheduleRun :execrows
INSERT INTO schedule_runs (
    id, schedule_id, session_id, scheduled_for, created_at, status, reason
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (schedule_id, scheduled_for) DO NOTHING
`

type CreateScheduleRunParams struct {
	ID           string `json:"id"`
	ScheduleID   string `json:"schedule_id"`
	SessionID    string `json:"session_id"`
	ScheduledFor string `json:"scheduled_for"`
	CreatedAt    string `json:"created_at"`
	Status       string `json:"status"`
	Reason       string `json:"reason"`
}

func (q *Queries) CreateScheduleRun(ctx context.Context, arg CreateScheduleRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createScheduleRun,
		arg.ID,
		arg.ScheduleID,
		arg.SessionID,
		arg.ScheduledFor,
		arg.CreatedAt,
		arg.Status,
		arg.Reason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules WHERE id = ?
`

func (q *Queries) DeleteSchedule(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSchedule, id)
	return err
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, project_id, session_id, name, prompt, cron, mode, enabled, pause_reason, attention, attention_run_id, next_run_at, expires_at, last_run_at, last_viewed_at, consecutive_failures, created_by, created_at, updated_at FROM schedules WHERE id = ?
`

func (q *Queries) GetSchedule(ctx context.Context, id string) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, getSchedule, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SessionID,
		&i.Name,
		&i.Prompt,
		&i.Cron,
		&i.Mode,
		&i.Enabled,
		&i.PauseReason,
		&i.Attention,
		&i.AttentionRunID,
		&i.NextRunAt,
		&i.ExpiresAt,
		&i.LastRunAt,
		&i.LastViewedAt,
		&i.ConsecutiveFailures,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScheduleRun = `-- name: GetScheduleRun :one
SELECT id, schedule_id, session_id, scheduled_for, created_at, fired_at, finished_at, status, overdue, attempts, next_attempt_at, turn_index, summary, reason, error, error_kind, late_report, duration_ms FROM schedule_runs WHERE id = ?
`

func (q *Queries) GetScheduleRun(ctx context.Context, id string) (ScheduleRun, error) {
	row := q.db.QueryRowContext(ctx, getScheduleRun, id)
	var i ScheduleRun
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.SessionID,
		&i.ScheduledFor,
		&i.CreatedAt,
		&i.FiredAt,
		&i.FinishedAt,
		&i.Status,
		&i.Overdue,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.TurnIndex,
		&i.Summary,
		&i.Reason,
		&i.Error,
		&i.ErrorKind,
		&i.LateReport,
		&i.DurationMs,
	)
	return i, err
}

const listDueSchedules = `-- name: ListDueSchedules :many
SELECT id, project_id, session_id, name, prompt, cron, mode, enabled, pause_reason, attention, attention_run_id, next_run_at, expires_at, last_run_at, last_viewed_at, consecutive_failures, created_by, created_at, updated_at FROM schedules
WHERE enabled = 1
  AND next_run_at != ''
  AND next_run_at <= ?
ORDER BY next_run_at
`

func (q *Queries) ListDueSchedules(ctx context.Context, nextRunAt string) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listDueSchedules, nextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SessionID,
			&i.Name,
			&i.Prompt,
			&i.Cron,
			&i.Mode,
			&i.Enabled,
			&i.PauseReason,
			&i.Attention,
			&i.AttentionRunID,
			&i.NextRunAt,
			&i.ExpiresAt,
			&i.LastRunAt,
			&i.LastViewedAt,
			&i.ConsecutiveFailures,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledSchedulesBySession = `-- name: ListEnabledSchedulesBySession :many
SELECT id, project_id, session_id, name, prompt, cron, mode, enabled, pause_reason, attention, attention_run_id, next_run_at, expires_at, last_run_at, last_viewed_at, consecutive_failures, created_by, created_at, updated_at FROM schedules WHERE session_id = ? AND enabled = 1
`

func (q *Queries) ListEnabledSchedulesBySession(ctx context.Context, sessionID string) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledSchedulesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SessionID,
			&i.Name,
			&i.Prompt,
			&i.Cron,
			&i.Mode,
			&i.Enabled,
			&i.PauseReason,
			&i.Attention,
			&i.AttentionRunID,
			&i.NextRunAt,
			&i.ExpiresAt,
			&i.LastRunAt,
			&i.LastViewedAt,
			&i.ConsecutiveFailures,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedRunsBySession = `-- name: ListQueuedRunsBySession :many
SELECT id, schedule_id, session_id, scheduled_for, created_at, fired_at, finished_at, status, overdue, attempts, next_attempt_at, turn_index, summary, reason, error, error_kind, late_report, duration_ms FROM schedule_runs WHERE session_id = ? AND status = 'queued'
`

func (q *Queries) ListQueuedRunsBySession(ctx context.Context, sessionID string) ([]ScheduleRun, error) {
	rows, err := q.db.QueryContext(ctx, listQueuedRunsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleRun{}
	for rows.Next() {
		var i ScheduleRun
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.SessionID,
			&i.ScheduledFor,
			&i.CreatedAt,
			&i.FiredAt,
			&i.FinishedAt,
			&i.Status,
			&i.Overdue,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.TurnIndex,
			&i.Summary,
			&i.Reason,
			&i.Error,
			&i.ErrorKind,
			&i.LateReport,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsSince = `-- name: ListRunsSince :one
SELECT COUNT(*) AS total,
       COALESCE(SUM(CASE WHEN status = 'ok' THEN 1 ELSE 0 END), 0) AS ok_count
FROM schedule_runs
WHERE schedule_id = ? AND created_at > ?
`

type ListRunsSinceParams struct {
	ScheduleID string `json:"schedule_id"`
	CreatedAt  string `json:"created_at"`
}

type ListRunsSinceRow struct {
	Total   int64       `json:"total"`
	OkCount interface{} `json:"ok_count"`
}

func (q *Queries) ListRunsSince(ctx context.Context, arg ListRunsSinceParams) (ListRunsSinceRow, error) {
	row := q.db.QueryRowContext(ctx, listRunsSince, arg.ScheduleID, arg.CreatedAt)
	var i ListRunsSinceRow
	err := row.Scan(&i.Total, &i.OkCount)
	return i, err
}

const listScheduleRuns = `-- name: ListScheduleRuns :many
SELECT id, schedule_id, session_id, scheduled_for, created_at, fired_at, finished_at, status, overdue, attempts, next_attempt_at, turn_index, summary, reason, error, error_kind, late_report, duration_ms FROM schedule_runs
WHERE schedule_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListScheduleRunsParams struct {
	ScheduleID string `json:"schedule_id"`
	Limit      int64  `json:"limit"`
	Offset     int64  `json:"offset"`
}

func (q *Queries) ListScheduleRuns(ctx context.Context, arg ListScheduleRunsParams) ([]ScheduleRun, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleRuns, arg.ScheduleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleRun{}
	for rows.Next() {
		var i ScheduleRun
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.SessionID,
			&i.ScheduledFor,
			&i.CreatedAt,
			&i.FiredAt,
			&i.FinishedAt,
			&i.Status,
			&i.Overdue,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.TurnIndex,
			&i.Summary,
			&i.Reason,
			&i.Error,
			&i.ErrorKind,
			&i.LateReport,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, project_id, session_id, name, prompt, cron, mode, enabled, pause_reason, attention, attention_run_id, next_run_at, expires_at, last_run_at, last_viewed_at, consecutive_failures, created_by, created_at, updated_at FROM schedules ORDER BY created_at DESC
`

func (q *Queries) ListSchedules(ctx context.Context) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SessionID,
			&i.Name,
			&i.Prompt,
			&i.Cron,
			&i.Mode,
			&i.Enabled,
			&i.PauseReason,
			&i.Attention,
			&i.AttentionRunID,
			&i.NextRunAt,
			&i.ExpiresAt,
			&i.LastRunAt,
			&i.LastViewedAt,
			&i.ConsecutiveFailures,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesBySession = `-- name: ListSchedulesBySession :many
SELECT id, project_id, session_id, name, prompt, cron, mode, enabled, pause_reason, attention, attention_run_id, next_run_at, expires_at, last_run_at, last_viewed_at, consecutive_failures, created_by, created_at, updated_at FROM schedules WHERE session_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListSchedulesBySession(ctx context.Context, sessionID string) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SessionID,
			&i.Name,
			&i.Prompt,
			&i.Cron,
			&i.Mode,
			&i.Enabled,
			&i.PauseReason,
			&i.Attention,
			&i.AttentionRunID,
			&i.NextRunAt,
			&i.ExpiresAt,
			&i.LastRunAt,
			&i.LastViewedAt,
			&i.ConsecutiveFailures,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnfinishedRunsForSchedule = `-- name: ListUnfinishedRunsForSchedule :many
SELECT id, schedule_id, session_id, scheduled_for, created_at, fired_at, finished_at, status, overdue, attempts, next_attempt_at, turn_index, summary, reason, error, error_kind, late_report, duration_ms FROM schedule_runs
WHERE schedule_id = ? AND status IN ('queued', 'firing', 'running')
`

func (q *Queries) ListUnfinishedRunsForSchedule(ctx context.Context, scheduleID string) ([]ScheduleRun, error) {
	rows, err := q.db.QueryContext(ctx, listUnfinishedRunsForSchedule, scheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleRun{}
	for rows.Next() {
		var i ScheduleRun
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.SessionID,
			&i.ScheduledFor,
			&i.CreatedAt,
			&i.FiredAt,
			&i.FinishedAt,
			&i.Status,
			&i.Overdue,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.TurnIndex,
			&i.Summary,
			&i.Reason,
			&i.Error,
			&i.ErrorKind,
			&i.LateReport,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnfinishedScheduleRuns = `-- name: ListUnfinishedScheduleRuns :many
SELECT id, schedule_id, session_id, scheduled_for, created_at, fired_at, finished_at, status, overdue, attempts, next_attempt_at, turn_index, summary, reason, error, error_kind, late_report, duration_ms FROM schedule_runs WHERE status IN ('queued', 'firing', 'running')
`

func (q *Queries) ListUnfinishedScheduleRuns(ctx context.Context) ([]ScheduleRun, error) {
	rows, err := q.db.QueryContext(ctx, listUnfinishedScheduleRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleRun{}
	for rows.Next() {
		var i ScheduleRun
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.SessionID,
			&i.ScheduledFor,
			&i.CreatedAt,
			&i.FiredAt,
			&i.FinishedAt,
			&i.Status,
			&i.Overdue,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.TurnIndex,
			&i.Summary,
			&i.Reason,
			&i.Error,
			&i.ErrorKind,
			&i.LateReport,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markScheduleRunFired = `-- name: MarkScheduleRunFired :exec
UPDATE schedule_runs
SET status = 'running', fired_at = ?, turn_index = ?, attempts = ?
WHERE id = ?
`

type MarkScheduleRunFiredParams struct {
	FiredAt   string `json:"fired_at"`
	TurnIndex int64  `json:"turn_index"`
	Attempts  int64  `json:"attempts"`
	ID        string `json:"id"`
}

func (q *Queries) MarkScheduleRunFired(ctx context.Context, arg MarkScheduleRunFiredParams) error {
	_, err := q.db.ExecContext(ctx, markScheduleRunFired,
		arg.FiredAt,
		arg.TurnIndex,
		arg.Attempts,
		arg.ID,
	)
	return err
}

const markScheduleViewed = `-- name: MarkScheduleViewed :exec
UPDATE schedules SET last_viewed_at = ?, updated_at = ? WHERE id = ?
`

type MarkScheduleViewedParams struct {
	LastViewedAt string `json:"last_viewed_at"`
	UpdatedAt    string `json:"updated_at"`
	ID           string `json:"id"`
}

func (q *Queries) MarkScheduleViewed(ctx context.Context, arg MarkScheduleViewedParams) error {
	_, err := q.db.ExecContext(ctx, markScheduleViewed, arg.LastViewedAt, arg.UpdatedAt, arg.ID)
	return err
}

const pruneScheduleRuns = `-- name: PruneScheduleRuns :exec
DELETE FROM schedule_runs
WHERE schedule_runs.schedule_id = ?
  AND schedule_runs.id NOT IN (
    SELECT keep.id FROM schedule_runs AS keep
    WHERE keep.schedule_id = ?
    ORDER BY keep.created_at DESC
    LIMIT ?
  )
`

type PruneScheduleRunsParams struct {
	ScheduleID   string `json:"schedule_id"`
	ScheduleID_2 string `json:"schedule_id_2"`
	Limit        int64  `json:"limit"`
}

func (q *Queries) PruneScheduleRuns(ctx context.Context, arg PruneScheduleRunsParams) error {
	_, err := q.db.ExecContext(ctx, pruneScheduleRuns, arg.ScheduleID, arg.ScheduleID_2, arg.Limit)
	return err
}

const requeueScheduleRun = `-- name: RequeueScheduleRun :exec
UPDATE schedule_runs SET status = 'queued', attempts = ?, next_attempt_at = ? WHERE id = ?
`

type RequeueScheduleRunParams struct {
	Attempts      int64  `json:"attempts"`
	NextAttemptAt string `json:"next_attempt_at"`
	ID            string `json:"id"`
}

func (q *Queries) RequeueScheduleRun(ctx context.Context, arg RequeueScheduleRunParams) error {
	_, err := q.db.ExecContext(ctx, requeueScheduleRun, arg.Attempts, arg.NextAttemptAt, arg.ID)
	return err
}

const resolveScheduleRun = `-- name: ResolveScheduleRun :execrows
UPDATE schedule_runs
SET status = ?, finished_at = ?, summary = ?, reason = ?, error = ?, error_kind = ?, duration_ms = ?
WHERE id = ? AND status IN ('queued', 'firing', 'running')
`

type ResolveScheduleRunParams struct {
	Status     string `json:"status"`
	FinishedAt string `json:"finished_at"`
	Summary    string `json:"summary"`
	Reason     string `json:"reason"`
	Error      string `json:"error"`
	ErrorKind  string `json:"error_kind"`
	DurationMs int64  `json:"duration_ms"`
	ID         string `json:"id"`
}

func (q *Queries) ResolveScheduleRun(ctx context.Context, arg ResolveScheduleRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveScheduleRun,
		arg.Status,
		arg.FinishedAt,
		arg.Summary,
		arg.Reason,
		arg.Error,
		arg.ErrorKind,
		arg.DurationMs,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setScheduleAttention = `-- name: SetScheduleAttention :exec
UPDATE schedules SET attention = ?, attention_run_id = ?, updated_at = ? WHERE id = ?
`

type SetScheduleAttentionParams struct {
	Attention      string `json:"attention"`
	AttentionRunID string `json:"attention_run_id"`
	UpdatedAt      string `json:"updated_at"`
	ID             string `json:"id"`
}

func (q *Queries) SetScheduleAttention(ctx context.Context, arg SetScheduleAttentionParams) error {
	_, err := q.db.ExecContext(ctx, setScheduleAttention,
		arg.Attention,
		arg.AttentionRunID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setScheduleEnabled = `-- name: SetScheduleEnabled :exec
UPDATE schedules SET enabled = ?, pause_reason = ?, next_run_at = ?, updated_at = ? WHERE id = ?
`

type SetScheduleEnabledParams struct {
	Enabled     int64  `json:"enabled"`
	PauseReason string `json:"pause_reason"`
	NextRunAt   string `json:"next_run_at"`
	UpdatedAt   string `json:"updated_at"`
	ID          string `json:"id"`
}

func (q *Queries) SetScheduleEnabled(ctx context.Context, arg SetScheduleEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setScheduleEnabled,
		arg.Enabled,
		arg.PauseReason,
		arg.NextRunAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setScheduleFailures = `-- name: SetScheduleFailures :exec
UPDATE schedules SET consecutive_failures = ?, updated_at = ? WHERE id = ?
`

type SetScheduleFailuresParams struct {
	ConsecutiveFailures int64  `json:"consecutive_failures"`
	UpdatedAt           string `json:"updated_at"`
	ID                  string `json:"id"`
}

func (q *Queries) SetScheduleFailures(ctx context.Context, arg SetScheduleFailuresParams) error {
	_, err := q.db.ExecContext(ctx, setScheduleFailures, arg.ConsecutiveFailures, arg.UpdatedAt, arg.ID)
	return err
}

const setScheduleRunOverdue = `-- name: SetScheduleRunOverdue :exec
UPDATE schedule_runs SET overdue = 1 WHERE id = ? AND status = 'running'
`

func (q *Queries) SetScheduleRunOverdue(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setScheduleRunOverdue, id)
	return err
}

const updateSchedule = `-- name: UpdateSchedule :exec
UPDATE schedules
SET name = ?, prompt = ?, cron = ?, mode = ?, expires_at = ?, updated_at = ?
WHERE id = ?
`

type UpdateScheduleParams struct {
	Name      string `json:"name"`
	Prompt    string `json:"prompt"`
	Cron      string `json:"cron"`
	Mode      string `json:"mode"`
	ExpiresAt string `json:"expires_at"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) error {
	_, err := q.db.ExecContext(ctx, updateSchedule,
		arg.Name,
		arg.Prompt,
		arg.Cron,
		arg.Mode,
		arg.ExpiresAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateScheduleNextRun = `-- name: UpdateScheduleNextRun :exec
UPDATE schedules SET next_run_at = ?, last_run_at = ?, updated_at = ? WHERE id = ?
`

type UpdateScheduleNextRunParams struct {
	NextRunAt string `json:"next_run_at"`
	LastRunAt string `json:"last_run_at"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateScheduleNextRun(ctx context.Context, arg UpdateScheduleNextRunParams) error {
	_, err := q.db.ExecContext(ctx, updateScheduleNextRun,
		arg.NextRunAt,
		arg.LastRunAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
