// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package store

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, project_id, name, work_dir, worktree_path, worktree_branch, worktree_base_sha, state, model, permission_mode, auto_approve)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, project_id, name, work_dir, worktree_path, worktree_branch, state, created_at, updated_at, claude_session_id, worktree_base_sha, model, worktree_merged, permission_mode, auto_approve
`

type CreateSessionParams struct {
	ID              string         `json:"id"`
	ProjectID       string         `json:"project_id"`
	Name            string         `json:"name"`
	WorkDir         string         `json:"work_dir"`
	WorktreePath    sql.NullString `json:"worktree_path"`
	WorktreeBranch  sql.NullString `json:"worktree_branch"`
	WorktreeBaseSha sql.NullString `json:"worktree_base_sha"`
	State           string         `json:"state"`
	Model           string         `json:"model"`
	PermissionMode  string         `json:"permission_mode"`
	AutoApprove     int64          `json:"auto_approve"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.WorkDir,
		arg.WorktreePath,
		arg.WorktreeBranch,
		arg.WorktreeBaseSha,
		arg.State,
		arg.Model,
		arg.PermissionMode,
		arg.AutoApprove,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.WorkDir,
		&i.WorktreePath,
		&i.WorktreeBranch,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaudeSessionID,
		&i.WorktreeBaseSha,
		&i.Model,
		&i.WorktreeMerged,
		&i.PermissionMode,
		&i.AutoApprove,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, project_id, name, work_dir, worktree_path, worktree_branch, state, created_at, updated_at, claude_session_id, worktree_base_sha, model, worktree_merged, permission_mode, auto_approve FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.WorkDir,
		&i.WorktreePath,
		&i.WorktreeBranch,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaudeSessionID,
		&i.WorktreeBaseSha,
		&i.Model,
		&i.WorktreeMerged,
		&i.PermissionMode,
		&i.AutoApprove,
	)
	return i, err
}

const listSessionsByProject = `-- name: ListSessionsByProject :many
SELECT id, project_id, name, work_dir, worktree_path, worktree_branch, state, created_at, updated_at, claude_session_id, worktree_base_sha, model, worktree_merged, permission_mode, auto_approve FROM sessions WHERE project_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListSessionsByProject(ctx context.Context, projectID string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.WorkDir,
			&i.WorktreePath,
			&i.WorktreeBranch,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaudeSessionID,
			&i.WorktreeBaseSha,
			&i.Model,
			&i.WorktreeMerged,
			&i.PermissionMode,
			&i.AutoApprove,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWorktreeMerged = `-- name: SetWorktreeMerged :exec
UPDATE sessions SET worktree_merged = 1, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

func (q *Queries) SetWorktreeMerged(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setWorktreeMerged, id)
	return err
}

const updateClaudeSessionID = `-- name: UpdateClaudeSessionID :exec
UPDATE sessions SET claude_session_id = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateClaudeSessionIDParams struct {
	ClaudeSessionID sql.NullString `json:"claude_session_id"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateClaudeSessionID(ctx context.Context, arg UpdateClaudeSessionIDParams) error {
	_, err := q.db.ExecContext(ctx, updateClaudeSessionID, arg.ClaudeSessionID, arg.ID)
	return err
}

const updateSessionAutoApprove = `-- name: UpdateSessionAutoApprove :exec
UPDATE sessions SET auto_approve = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateSessionAutoApproveParams struct {
	AutoApprove int64  `json:"auto_approve"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateSessionAutoApprove(ctx context.Context, arg UpdateSessionAutoApproveParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionAutoApprove, arg.AutoApprove, arg.ID)
	return err
}

const updateSessionModel = `-- name: UpdateSessionModel :exec
UPDATE sessions SET model = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateSessionModelParams struct {
	Model string `json:"model"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateSessionModel(ctx context.Context, arg UpdateSessionModelParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionModel, arg.Model, arg.ID)
	return err
}

const updateSessionName = `-- name: UpdateSessionName :exec
UPDATE sessions SET name = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateSessionNameParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateSessionName(ctx context.Context, arg UpdateSessionNameParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionName, arg.Name, arg.ID)
	return err
}

const updateSessionPermissionMode = `-- name: UpdateSessionPermissionMode :exec
UPDATE sessions SET permission_mode = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateSessionPermissionModeParams struct {
	PermissionMode string `json:"permission_mode"`
	ID             string `json:"id"`
}

func (q *Queries) UpdateSessionPermissionMode(ctx context.Context, arg UpdateSessionPermissionModeParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionPermissionMode, arg.PermissionMode, arg.ID)
	return err
}

const updateSessionState = `-- name: UpdateSessionState :exec
UPDATE sessions SET state = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateSessionStateParams struct {
	State string `json:"state"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateSessionState(ctx context.Context, arg UpdateSessionStateParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionState, arg.State, arg.ID)
	return err
}

const updateWorktreeBaseSHA = `-- name: UpdateWorktreeBaseSHA :exec
UPDATE sessions SET worktree_base_sha = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateWorktreeBaseSHAParams struct {
	WorktreeBaseSha sql.NullString `json:"worktree_base_sha"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateWorktreeBaseSHA(ctx context.Context, arg UpdateWorktreeBaseSHAParams) error {
	_, err := q.db.ExecContext(ctx, updateWorktreeBaseSHA, arg.WorktreeBaseSha, arg.ID)
	return err
}
