// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package store

import (
	"context"
	"database/sql"
)

const clearSessionUnseenCompletedAt = `-- name: ClearSessionUnseenCompletedAt :exec
UPDATE sessions SET unseen_completed_at = NULL, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

// The read receipt. Idempotent by construction: clearing an already-clear row
// touches nothing the client can see.
func (q *Queries) ClearSessionUnseenCompletedAt(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearSessionUnseenCompletedAt, id)
	return err
}

const countActiveSessionsByProject = `-- name: CountActiveSessionsByProject :one
SELECT COUNT(*) FROM sessions
WHERE project_id = ? AND archived_at IS NULL AND state NOT IN ('done', 'stopped', 'failed')
`

func (q *Queries) CountActiveSessionsByProject(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveSessionsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, project_id, name, work_dir, worktree_path, worktree_branch, worktree_base_sha, state, model, permission_mode, auto_approve_mode, effort, max_budget, max_turns, behavior_presets, agent_profile_id, parent_session_id, provider)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, project_id, name, work_dir, worktree_path, worktree_branch, state, created_at, updated_at, claude_session_id, worktree_base_sha, model, worktree_merged, permission_mode, auto_approve, pr_url, effort, max_budget, max_turns, last_query_at, archived_at, behavior_presets, channel_id, channel_role, auto_approve_mode, agent_profile_id, parent_session_id, provider, resolved_model, pinned, pin_order, unseen_completed_at
`

type CreateSessionParams struct {
	ID              string         `json:"id"`
	ProjectID       string         `json:"project_id"`
	Name            string         `json:"name"`
	WorkDir         string         `json:"work_dir"`
	WorktreePath    sql.NullString `json:"worktree_path"`
	WorktreeBranch  sql.NullString `json:"worktree_branch"`
	WorktreeBaseSha sql.NullString `json:"worktree_base_sha"`
	State           string         `json:"state"`
	Model           string         `json:"model"`
	PermissionMode  string         `json:"permission_mode"`
	AutoApproveMode string         `json:"auto_approve_mode"`
	Effort          string         `json:"effort"`
	MaxBudget       float64        `json:"max_budget"`
	MaxTurns        int64          `json:"max_turns"`
	BehaviorPresets string         `json:"behavior_presets"`
	AgentProfileID  sql.NullString `json:"agent_profile_id"`
	ParentSessionID sql.NullString `json:"parent_session_id"`
	Provider        string         `json:"provider"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.WorkDir,
		arg.WorktreePath,
		arg.WorktreeBranch,
		arg.WorktreeBaseSha,
		arg.State,
		arg.Model,
		arg.PermissionMode,
		arg.AutoApproveMode,
		arg.Effort,
		arg.MaxBudget,
		arg.MaxTurns,
		arg.BehaviorPresets,
		arg.AgentProfileID,
		arg.ParentSessionID,
		arg.Provider,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.WorkDir,
		&i.WorktreePath,
		&i.WorktreeBranch,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaudeSessionID,
		&i.WorktreeBaseSha,
		&i.Model,
		&i.WorktreeMerged,
		&i.PermissionMode,
		&i.AutoApprove,
		&i.PrUrl,
		&i.Effort,
		&i.MaxBudget,
		&i.MaxTurns,
		&i.LastQueryAt,
		&i.ArchivedAt,
		&i.BehaviorPresets,
		&i.ChannelID,
		&i.ChannelRole,
		&i.AutoApproveMode,
		&i.AgentProfileID,
		&i.ParentSessionID,
		&i.Provider,
		&i.ResolvedModel,
		&i.Pinned,
		&i.PinOrder,
		&i.UnseenCompletedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getActiveSessionByAgentProfile = `-- name: GetActiveSessionByAgentProfile :one
SELECT id, project_id, name, work_dir, worktree_path, worktree_branch, state, created_at, updated_at, claude_session_id, worktree_base_sha, model, worktree_merged, permission_mode, auto_approve, pr_url, effort, max_budget, max_turns, last_query_at, archived_at, behavior_presets, channel_id, channel_role, auto_approve_mode, agent_profile_id, parent_session_id, provider, resolved_model, pinned, pin_order, unseen_completed_at FROM sessions
WHERE agent_profile_id = ?
  AND archived_at IS NULL
  AND state NOT IN ('done', 'stopped', 'failed')
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetActiveSessionByAgentProfile(ctx context.Context, agentProfileID sql.NullString) (Session, error) {
	row := q.db.QueryRowContext(ctx, getActiveSessionByAgentProfile, agentProfileID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.WorkDir,
		&i.WorktreePath,
		&i.WorktreeBranch,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaudeSessionID,
		&i.WorktreeBaseSha,
		&i.Model,
		&i.WorktreeMerged,
		&i.PermissionMode,
		&i.AutoApprove,
		&i.PrUrl,
		&i.Effort,
		&i.MaxBudget,
		&i.MaxTurns,
		&i.LastQueryAt,
		&i.ArchivedAt,
		&i.BehaviorPresets,
		&i.ChannelID,
		&i.ChannelRole,
		&i.AutoApproveMode,
		&i.AgentProfileID,
		&i.ParentSessionID,
		&i.Provider,
		&i.ResolvedModel,
		&i.Pinned,
		&i.PinOrder,
		&i.UnseenCompletedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, project_id, name, work_dir, worktree_path, worktree_branch, state, created_at, updated_at, claude_session_id, worktree_base_sha, model, worktree_merged, permission_mode, auto_approve, pr_url, effort, max_budget, max_turns, last_query_at, archived_at, behavior_presets, channel_id, channel_role, auto_approve_mode, agent_profile_id, parent_session_id, provider, resolved_model, pinned, pin_order, unseen_completed_at FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.WorkDir,
		&i.WorktreePath,
		&i.WorktreeBranch,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaudeSessionID,
		&i.WorktreeBaseSha,
		&i.Model,
		&i.WorktreeMerged,
		&i.PermissionMode,
		&i.AutoApprove,
		&i.PrUrl,
		&i.Effort,
		&i.MaxBudget,
		&i.MaxTurns,
		&i.LastQueryAt,
		&i.ArchivedAt,
		&i.BehaviorPresets,
		&i.ChannelID,
		&i.ChannelRole,
		&i.AutoApproveMode,
		&i.AgentProfileID,
		&i.ParentSessionID,
		&i.Provider,
		&i.ResolvedModel,
		&i.Pinned,
		&i.PinOrder,
		&i.UnseenCompletedAt,
	)
	return i, err
}

const listAllSessions = `-- name: ListAllSessions :many
SELECT id, project_id, name, work_dir, worktree_path, worktree_branch, state, created_at, updated_at, claude_session_id, worktree_base_sha, model, worktree_merged, permission_mode, auto_approve, pr_url, effort, max_budget, max_turns, last_query_at, archived_at, behavior_presets, channel_id, channel_role, auto_approve_mode, agent_profile_id, parent_session_id, provider, resolved_model, pinned, pin_order, unseen_completed_at FROM sessions ORDER BY updated_at DESC
`

func (q *Queries) ListAllSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listAllSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.WorkDir,
			&i.WorktreePath,
			&i.WorktreeBranch,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaudeSessionID,
			&i.WorktreeBaseSha,
			&i.Model,
			&i.WorktreeMerged,
			&i.PermissionMode,
			&i.AutoApprove,
			&i.PrUrl,
			&i.Effort,
			&i.MaxBudget,
			&i.MaxTurns,
			&i.LastQueryAt,
			&i.ArchivedAt,
			&i.BehaviorPresets,
			&i.ChannelID,
			&i.ChannelRole,
			&i.AutoApproveMode,
			&i.AgentProfileID,
			&i.ParentSessionID,
			&i.Provider,
			&i.ResolvedModel,
			&i.Pinned,
			&i.PinOrder,
			&i.UnseenCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildSessions = `-- name: ListChildSessions :many
SELECT id, project_id, name, work_dir, worktree_path, worktree_branch, state, created_at, updated_at, claude_session_id, worktree_base_sha, model, worktree_merged, permission_mode, auto_approve, pr_url, effort, max_budget, max_turns, last_query_at, archived_at, behavior_presets, channel_id, channel_role, auto_approve_mode, agent_profile_id, parent_session_id, provider, resolved_model, pinned, pin_order, unseen_completed_at FROM sessions WHERE parent_session_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListChildSessions(ctx context.Context, parentSessionID sql.NullString) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listChildSessions, parentSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.WorkDir,
			&i.WorktreePath,
			&i.WorktreeBranch,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaudeSessionID,
			&i.WorktreeBaseSha,
			&i.Model,
			&i.WorktreeMerged,
			&i.PermissionMode,
			&i.AutoApprove,
			&i.PrUrl,
			&i.Effort,
			&i.MaxBudget,
			&i.MaxTurns,
			&i.LastQueryAt,
			&i.ArchivedAt,
			&i.BehaviorPresets,
			&i.ChannelID,
			&i.ChannelRole,
			&i.AutoApproveMode,
			&i.AgentProfileID,
			&i.ParentSessionID,
			&i.Provider,
			&i.ResolvedModel,
			&i.Pinned,
			&i.PinOrder,
			&i.UnseenCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByProject = `-- name: ListSessionsByProject :many
SELECT id, project_id, name, work_dir, worktree_path, worktree_branch, state, created_at, updated_at, claude_session_id, worktree_base_sha, model, worktree_merged, permission_mode, auto_approve, pr_url, effort, max_budget, max_turns, last_query_at, archived_at, behavior_presets, channel_id, channel_role, auto_approve_mode, agent_profile_id, parent_session_id, provider, resolved_model, pinned, pin_order, unseen_completed_at FROM sessions WHERE project_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListSessionsByProject(ctx context.Context, projectID string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.WorkDir,
			&i.WorktreePath,
			&i.WorktreeBranch,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaudeSessionID,
			&i.WorktreeBaseSha,
			&i.Model,
			&i.WorktreeMerged,
			&i.PermissionMode,
			&i.AutoApprove,
			&i.PrUrl,
			&i.Effort,
			&i.MaxBudget,
			&i.MaxTurns,
			&i.LastQueryAt,
			&i.ArchivedAt,
			&i.BehaviorPresets,
			&i.ChannelID,
			&i.ChannelRole,
			&i.AutoApproveMode,
			&i.AgentProfileID,
			&i.ParentSessionID,
			&i.Provider,
			&i.ResolvedModel,
			&i.Pinned,
			&i.PinOrder,
			&i.UnseenCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverStaleSessions = `-- name: RecoverStaleSessions :exec
UPDATE sessions SET state = 'stopped', updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE state IN ('running', 'merging')
`

func (q *Queries) RecoverStaleSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, recoverStaleSessions)
	return err
}

const setSessionArchived = `-- name: SetSessionArchived :exec
UPDATE sessions SET archived_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), pinned = 0, pin_order = 0, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

// Archiving releases the pin. Pinned means "keep this at the top" and archived
// means "stow this away": a session cannot be both, and leaving the pin set kept
// filed-away work sitting in the priority section. Clearing it here rather than
// at each caller means no archive path (the RPC, a completing merge, a local
// session's commit) can forget to.
//
// Keep this comment ASCII. sqlc expands `SELECT *` by byte offset, so a
// multi-byte character anywhere in this file shifts those offsets and corrupts
// the generated code for LATER queries.
func (q *Queries) SetSessionArchived(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setSessionArchived, id)
	return err
}

const setSessionUnseenCompletedAt = `-- name: SetSessionUnseenCompletedAt :exec
UPDATE sessions SET unseen_completed_at = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type SetSessionUnseenCompletedAtParams struct {
	UnseenCompletedAt sql.NullString `json:"unseen_completed_at"`
	ID                string         `json:"id"`
}

// Stamps "this finished while nobody was reading it". The timestamp is a
// parameter rather than strftime('now') because the caller is the turn-end
// seam, which already knows when the turn completed; it must be UTC RFC3339
// seconds ("2006-01-02T15:04:05Z") like every other timestamp here, since
// SQLite compares TEXT lexicographically.
func (q *Queries) SetSessionUnseenCompletedAt(ctx context.Context, arg SetSessionUnseenCompletedAtParams) error {
	_, err := q.db.ExecContext(ctx, setSessionUnseenCompletedAt, arg.UnseenCompletedAt, arg.ID)
	return err
}

const setWorktreeMerged = `-- name: SetWorktreeMerged :exec
UPDATE sessions SET worktree_merged = 1, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

func (q *Queries) SetWorktreeMerged(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setWorktreeMerged, id)
	return err
}

const unsetSessionArchived = `-- name: UnsetSessionArchived :exec
UPDATE sessions SET archived_at = NULL, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

func (q *Queries) UnsetSessionArchived(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, unsetSessionArchived, id)
	return err
}

const unsetWorktreeMerged = `-- name: UnsetWorktreeMerged :exec
UPDATE sessions SET worktree_merged = 0, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

func (q *Queries) UnsetWorktreeMerged(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, unsetWorktreeMerged, id)
	return err
}

const updateClaudeSessionID = `-- name: UpdateClaudeSessionID :exec
UPDATE sessions SET claude_session_id = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateClaudeSessionIDParams struct {
	ClaudeSessionID sql.NullString `json:"claude_session_id"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateClaudeSessionID(ctx context.Context, arg UpdateClaudeSessionIDParams) error {
	_, err := q.db.ExecContext(ctx, updateClaudeSessionID, arg.ClaudeSessionID, arg.ID)
	return err
}

const updateSessionAutoApproveMode = `-- name: UpdateSessionAutoApproveMode :exec
UPDATE sessions SET auto_approve_mode = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateSessionAutoApproveModeParams struct {
	AutoApproveMode string `json:"auto_approve_mode"`
	ID              string `json:"id"`
}

func (q *Queries) UpdateSessionAutoApproveMode(ctx context.Context, arg UpdateSessionAutoApproveModeParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionAutoApproveMode, arg.AutoApproveMode, arg.ID)
	return err
}

const updateSessionBehaviorPresets = `-- name: UpdateSessionBehaviorPresets :exec
UPDATE sessions SET behavior_presets = ? WHERE id = ?
`

type UpdateSessionBehaviorPresetsParams struct {
	BehaviorPresets string `json:"behavior_presets"`
	ID              string `json:"id"`
}

func (q *Queries) UpdateSessionBehaviorPresets(ctx context.Context, arg UpdateSessionBehaviorPresetsParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionBehaviorPresets, arg.BehaviorPresets, arg.ID)
	return err
}

const updateSessionLastQueryAt = `-- name: UpdateSessionLastQueryAt :exec
UPDATE sessions SET last_query_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

func (q *Queries) UpdateSessionLastQueryAt(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateSessionLastQueryAt, id)
	return err
}

const updateSessionModel = `-- name: UpdateSessionModel :exec
UPDATE sessions SET model = ?, resolved_model = '', updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateSessionModelParams struct {
	Model string `json:"model"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateSessionModel(ctx context.Context, arg UpdateSessionModelParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionModel, arg.Model, arg.ID)
	return err
}

const updateSessionName = `-- name: UpdateSessionName :exec
UPDATE sessions SET name = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateSessionNameParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateSessionName(ctx context.Context, arg UpdateSessionNameParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionName, arg.Name, arg.ID)
	return err
}

const updateSessionPRUrl = `-- name: UpdateSessionPRUrl :exec
UPDATE sessions SET pr_url = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateSessionPRUrlParams struct {
	PrUrl string `json:"pr_url"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateSessionPRUrl(ctx context.Context, arg UpdateSessionPRUrlParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionPRUrl, arg.PrUrl, arg.ID)
	return err
}

const updateSessionPermissionMode = `-- name: UpdateSessionPermissionMode :exec
UPDATE sessions SET permission_mode = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateSessionPermissionModeParams struct {
	PermissionMode string `json:"permission_mode"`
	ID             string `json:"id"`
}

func (q *Queries) UpdateSessionPermissionMode(ctx context.Context, arg UpdateSessionPermissionModeParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionPermissionMode, arg.PermissionMode, arg.ID)
	return err
}

const updateSessionPinned = `-- name: UpdateSessionPinned :one
UPDATE sessions SET pinned = ?, pin_order = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ? RETURNING id, project_id, name, work_dir, worktree_path, worktree_branch, state, created_at, updated_at, claude_session_id, worktree_base_sha, model, worktree_merged, permission_mode, auto_approve, pr_url, effort, max_budget, max_turns, last_query_at, archived_at, behavior_presets, channel_id, channel_role, auto_approve_mode, agent_profile_id, parent_session_id, provider, resolved_model, pinned, pin_order, unseen_completed_at
`

type UpdateSessionPinnedParams struct {
	Pinned   int64  `json:"pinned"`
	PinOrder int64  `json:"pin_order"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateSessionPinned(ctx context.Context, arg UpdateSessionPinnedParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, updateSessionPinned, arg.Pinned, arg.PinOrder, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.WorkDir,
		&i.WorktreePath,
		&i.WorktreeBranch,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaudeSessionID,
		&i.WorktreeBaseSha,
		&i.Model,
		&i.WorktreeMerged,
		&i.PermissionMode,
		&i.AutoApprove,
		&i.PrUrl,
		&i.Effort,
		&i.MaxBudget,
		&i.MaxTurns,
		&i.LastQueryAt,
		&i.ArchivedAt,
		&i.BehaviorPresets,
		&i.ChannelID,
		&i.ChannelRole,
		&i.AutoApproveMode,
		&i.AgentProfileID,
		&i.ParentSessionID,
		&i.Provider,
		&i.ResolvedModel,
		&i.Pinned,
		&i.PinOrder,
		&i.UnseenCompletedAt,
	)
	return i, err
}

const updateSessionResolvedModel = `-- name: UpdateSessionResolvedModel :exec
UPDATE sessions SET resolved_model = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateSessionResolvedModelParams struct {
	ResolvedModel string `json:"resolved_model"`
	ID            string `json:"id"`
}

func (q *Queries) UpdateSessionResolvedModel(ctx context.Context, arg UpdateSessionResolvedModelParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionResolvedModel, arg.ResolvedModel, arg.ID)
	return err
}

const updateSessionState = `-- name: UpdateSessionState :exec
UPDATE sessions SET state = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateSessionStateParams struct {
	State string `json:"state"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateSessionState(ctx context.Context, arg UpdateSessionStateParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionState, arg.State, arg.ID)
	return err
}

const updateSessionWorktree = `-- name: UpdateSessionWorktree :exec
UPDATE sessions
SET work_dir = ?, worktree_path = ?, worktree_branch = ?, worktree_base_sha = ?, worktree_merged = 0,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type UpdateSessionWorktreeParams struct {
	WorkDir         string         `json:"work_dir"`
	WorktreePath    sql.NullString `json:"worktree_path"`
	WorktreeBranch  sql.NullString `json:"worktree_branch"`
	WorktreeBaseSha sql.NullString `json:"worktree_base_sha"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateSessionWorktree(ctx context.Context, arg UpdateSessionWorktreeParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionWorktree,
		arg.WorkDir,
		arg.WorktreePath,
		arg.WorktreeBranch,
		arg.WorktreeBaseSha,
		arg.ID,
	)
	return err
}

const updateWorktreeBaseSHA = `-- name: UpdateWorktreeBaseSHA :exec
UPDATE sessions SET worktree_base_sha = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateWorktreeBaseSHAParams struct {
	WorktreeBaseSha sql.NullString `json:"worktree_base_sha"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateWorktreeBaseSHA(ctx context.Context, arg UpdateWorktreeBaseSHAParams) error {
	_, err := q.db.ExecContext(ctx, updateWorktreeBaseSHA, arg.WorktreeBaseSha, arg.ID)
	return err
}
