// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: steward.sql

package store

import (
	"context"
	"database/sql"
)

const listOpenStewardFindings = `-- name: ListOpenStewardFindings :many
SELECT kind, subject, severity, remedy, facts, opened_at FROM steward_findings
WHERE resolved_at = ''
ORDER BY opened_at, id
`

type ListOpenStewardFindingsRow struct {
	Kind     string `json:"kind"`
	Subject  string `json:"subject"`
	Severity string `json:"severity"`
	Remedy   string `json:"remedy"`
	Facts    string `json:"facts"`
	OpenedAt string `json:"opened_at"`
}

func (q *Queries) ListOpenStewardFindings(ctx context.Context) ([]ListOpenStewardFindingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOpenStewardFindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenStewardFindingsRow{}
	for rows.Next() {
		var i ListOpenStewardFindingsRow
		if err := rows.Scan(
			&i.Kind,
			&i.Subject,
			&i.Severity,
			&i.Remedy,
			&i.Facts,
			&i.OpenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeerCredentialIDs = `-- name: ListPeerCredentialIDs :many
SELECT id FROM auth_sessions
WHERE kind = 'peer' AND id IS NOT NULL AND expires_at > strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
ORDER BY id
`

// The public ids of every peer credential this server has minted: who a
// machine-wide event, a finding, is published to.
func (q *Queries) ListPeerCredentialIDs(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listPeerCredentialIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var id sql.NullString
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openStewardFinding = `-- name: OpenStewardFinding :exec
INSERT INTO steward_findings (kind, subject, severity, remedy, facts, opened_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT (kind, subject) WHERE resolved_at = '' DO NOTHING
`

type OpenStewardFindingParams struct {
	Kind     string `json:"kind"`
	Subject  string `json:"subject"`
	Severity string `json:"severity"`
	Remedy   string `json:"remedy"`
	Facts    string `json:"facts"`
	OpenedAt string `json:"opened_at"`
}

func (q *Queries) OpenStewardFinding(ctx context.Context, arg OpenStewardFindingParams) error {
	_, err := q.db.ExecContext(ctx, openStewardFinding,
		arg.Kind,
		arg.Subject,
		arg.Severity,
		arg.Remedy,
		arg.Facts,
		arg.OpenedAt,
	)
	return err
}

const pruneStewardFindings = `-- name: PruneStewardFindings :execrows
DELETE FROM steward_findings WHERE resolved_at != '' AND resolved_at < ?
`

func (q *Queries) PruneStewardFindings(ctx context.Context, resolvedAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneStewardFindings, resolvedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const refreshStewardFinding = `-- name: RefreshStewardFinding :exec
UPDATE steward_findings SET severity = ?1, remedy = ?2, facts = ?3
WHERE kind = ?4 AND subject = ?5 AND resolved_at = ''
`

type RefreshStewardFindingParams struct {
	Severity string `json:"severity"`
	Remedy   string `json:"remedy"`
	Facts    string `json:"facts"`
	Kind     string `json:"kind"`
	Subject  string `json:"subject"`
}

func (q *Queries) RefreshStewardFinding(ctx context.Context, arg RefreshStewardFindingParams) error {
	_, err := q.db.ExecContext(ctx, refreshStewardFinding,
		arg.Severity,
		arg.Remedy,
		arg.Facts,
		arg.Kind,
		arg.Subject,
	)
	return err
}

const resolveStewardFinding = `-- name: ResolveStewardFinding :exec
UPDATE steward_findings SET resolved_at = ?1
WHERE kind = ?2 AND subject = ?3 AND resolved_at = ''
`

type ResolveStewardFindingParams struct {
	ResolvedAt string `json:"resolved_at"`
	Kind       string `json:"kind"`
	Subject    string `json:"subject"`
}

func (q *Queries) ResolveStewardFinding(ctx context.Context, arg ResolveStewardFindingParams) error {
	_, err := q.db.ExecContext(ctx, resolveStewardFinding, arg.ResolvedAt, arg.Kind, arg.Subject)
	return err
}
