// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tags.sql

package store

import (
	"context"
)

const addTagToProject = `-- name: AddTagToProject :exec
INSERT OR IGNORE INTO project_tags (project_id, tag_id) VALUES (?, ?)
`

type AddTagToProjectParams struct {
	ProjectID string `json:"project_id"`
	TagID     string `json:"tag_id"`
}

func (q *Queries) AddTagToProject(ctx context.Context, arg AddTagToProjectParams) error {
	_, err := q.db.ExecContext(ctx, addTagToProject, arg.ProjectID, arg.TagID)
	return err
}

const clearProjectTags = `-- name: ClearProjectTags :exec
DELETE FROM project_tags WHERE project_id = ?
`

func (q *Queries) ClearProjectTags(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, clearProjectTags, projectID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (id, name, color) VALUES (?, ?, ?) RETURNING id, name, color, sort_order, created_at, updated_at
`

type CreateTagParams struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Color string `json:"color"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.ID, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, name, color, sort_order, created_at, updated_at FROM tags WHERE id = ?
`

func (q *Queries) GetTag(ctx context.Context, id string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllProjectTags = `-- name: ListAllProjectTags :many
SELECT project_id, tag_id FROM project_tags
`

func (q *Queries) ListAllProjectTags(ctx context.Context) ([]ProjectTag, error) {
	rows, err := q.db.QueryContext(ctx, listAllProjectTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectTag{}
	for rows.Next() {
		var i ProjectTag
		if err := rows.Scan(&i.ProjectID, &i.TagID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTags = `-- name: ListProjectTags :many
SELECT t.id, t.name, t.color, t.sort_order, t.created_at, t.updated_at FROM tags t
JOIN project_tags pt ON pt.tag_id = t.id
WHERE pt.project_id = ?
ORDER BY t.sort_order ASC, t.name ASC
`

func (q *Queries) ListProjectTags(ctx context.Context, projectID string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listProjectTags, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, color, sort_order, created_at, updated_at FROM tags ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromProject = `-- name: RemoveTagFromProject :exec
DELETE FROM project_tags WHERE project_id = ? AND tag_id = ?
`

type RemoveTagFromProjectParams struct {
	ProjectID string `json:"project_id"`
	TagID     string `json:"tag_id"`
}

func (q *Queries) RemoveTagFromProject(ctx context.Context, arg RemoveTagFromProjectParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromProject, arg.ProjectID, arg.TagID)
	return err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags SET name = ?, color = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ? RETURNING id, name, color, sort_order, created_at, updated_at
`

type UpdateTagParams struct {
	Name  string `json:"name"`
	Color string `json:"color"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, updateTag, arg.Name, arg.Color, arg.ID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
