// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: teams.sql

package store

import (
	"context"
	"database/sql"
)

const clearSessionTeam = `-- name: ClearSessionTeam :exec
UPDATE sessions SET team_id = NULL, team_role = '', updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

func (q *Queries) ClearSessionTeam(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearSessionTeam, id)
	return err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (id, name, project_id) VALUES (?, ?, ?) RETURNING id, name, project_id, created_at
`

type CreateTeamParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam, arg.ID, arg.Name, arg.ProjectID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = ?
`

func (q *Queries) DeleteTeam(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTeam, id)
	return err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, project_id, created_at FROM teams WHERE id = ?
`

func (q *Queries) GetTeam(ctx context.Context, id string) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentMessagesByTeam = `-- name: ListAgentMessagesByTeam :many
SELECT se.id, se.session_id, se.turn_index, se.seq, se.type, se.data, se.created_at FROM session_events se
JOIN sessions s ON se.session_id = s.id
WHERE s.team_id = ? AND se.type = 'agent_message'
ORDER BY se.created_at ASC
`

func (q *Queries) ListAgentMessagesByTeam(ctx context.Context, teamID sql.NullString) ([]SessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentMessagesByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionEvent{}
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TurnIndex,
			&i.Seq,
			&i.Type,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT id, project_id, name, work_dir, worktree_path, worktree_branch, state, created_at, updated_at, claude_session_id, worktree_base_sha, model, worktree_merged, permission_mode, auto_approve, pr_url, effort, max_budget, max_turns, last_query_at, completed_at, behavior_presets, team_id, team_role FROM sessions WHERE team_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListTeamMembers(ctx context.Context, teamID sql.NullString) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.WorkDir,
			&i.WorktreePath,
			&i.WorktreeBranch,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaudeSessionID,
			&i.WorktreeBaseSha,
			&i.Model,
			&i.WorktreeMerged,
			&i.PermissionMode,
			&i.AutoApprove,
			&i.PrUrl,
			&i.Effort,
			&i.MaxBudget,
			&i.MaxTurns,
			&i.LastQueryAt,
			&i.CompletedAt,
			&i.BehaviorPresets,
			&i.TeamID,
			&i.TeamRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByProject = `-- name: ListTeamsByProject :many
SELECT id, name, project_id, created_at FROM teams WHERE project_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListTeamsByProject(ctx context.Context, projectID string) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listTeamsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionTeam = `-- name: SetSessionTeam :exec
UPDATE sessions SET team_id = ?, team_role = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type SetSessionTeamParams struct {
	TeamID   sql.NullString `json:"team_id"`
	TeamRole string         `json:"team_role"`
	ID       string         `json:"id"`
}

func (q *Queries) SetSessionTeam(ctx context.Context, arg SetSessionTeamParams) error {
	_, err := q.db.ExecContext(ctx, setSessionTeam, arg.TeamID, arg.TeamRole, arg.ID)
	return err
}

const updateTeamName = `-- name: UpdateTeamName :exec
UPDATE teams SET name = ? WHERE id = ?
`

type UpdateTeamNameParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateTeamName(ctx context.Context, arg UpdateTeamNameParams) error {
	_, err := q.db.ExecContext(ctx, updateTeamName, arg.Name, arg.ID)
	return err
}
