// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: teams.sql

package store

import (
	"context"
)

const addTeamMember = `-- name: AddTeamMember :exec
INSERT INTO team_members (team_id, agent_profile_id, sort_order)
VALUES (?, ?, ?)
ON CONFLICT (team_id, agent_profile_id) DO UPDATE SET sort_order = excluded.sort_order
`

type AddTeamMemberParams struct {
	TeamID         string `json:"team_id"`
	AgentProfileID string `json:"agent_profile_id"`
	SortOrder      int64  `json:"sort_order"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error {
	_, err := q.db.ExecContext(ctx, addTeamMember, arg.TeamID, arg.AgentProfileID, arg.SortOrder)
	return err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (id, name, description) VALUES (?, ?, ?) RETURNING id, name, description, created_at, updated_at
`

type CreateTeamParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam, arg.ID, arg.Name, arg.Description)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = ?
`

func (q *Queries) DeleteTeam(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTeam, id)
	return err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, description, created_at, updated_at FROM teams WHERE id = ?
`

func (q *Queries) GetTeam(ctx context.Context, id string) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT ap.id, ap.name, ap.role, ap.description, ap.project_id, ap.avatar, ap.config, ap.created_at, ap.updated_at FROM agent_profiles ap
JOIN team_members tm ON tm.agent_profile_id = ap.id
WHERE tm.team_id = ?
ORDER BY tm.sort_order ASC, ap.name ASC
`

func (q *Queries) ListTeamMembers(ctx context.Context, teamID string) ([]AgentProfile, error) {
	rows, err := q.db.QueryContext(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentProfile{}
	for rows.Next() {
		var i AgentProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Description,
			&i.ProjectID,
			&i.Avatar,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT id, name, description, created_at, updated_at FROM teams ORDER BY name ASC
`

func (q *Queries) ListTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsForAgent = `-- name: ListTeamsForAgent :many
SELECT t.id, t.name, t.description, t.created_at, t.updated_at FROM teams t
JOIN team_members tm ON tm.team_id = t.id
WHERE tm.agent_profile_id = ?
ORDER BY t.name ASC
`

func (q *Queries) ListTeamsForAgent(ctx context.Context, agentProfileID string) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listTeamsForAgent, agentProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members WHERE team_id = ? AND agent_profile_id = ?
`

type RemoveTeamMemberParams struct {
	TeamID         string `json:"team_id"`
	AgentProfileID string `json:"agent_profile_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeTeamMember, arg.TeamID, arg.AgentProfileID)
	return err
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET name = ?, description = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
RETURNING id, name, description, created_at, updated_at
`

type UpdateTeamParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, updateTeam, arg.Name, arg.Description, arg.ID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
