// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: voice_settings.sql

package store

import (
	"context"
)

const getVoiceSettings = `-- name: GetVoiceSettings :one
SELECT voice_name, model, personality, verbosity, updated_at
FROM voice_settings WHERE id = 1
`

type GetVoiceSettingsRow struct {
	VoiceName   string `json:"voice_name"`
	Model       string `json:"model"`
	Personality string `json:"personality"`
	Verbosity   string `json:"verbosity"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) GetVoiceSettings(ctx context.Context) (GetVoiceSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getVoiceSettings)
	var i GetVoiceSettingsRow
	err := row.Scan(
		&i.VoiceName,
		&i.Model,
		&i.Personality,
		&i.Verbosity,
		&i.UpdatedAt,
	)
	return i, err
}

const setVoiceSettings = `-- name: SetVoiceSettings :exec
INSERT INTO voice_settings (id, voice_name, model, personality, verbosity, updated_at)
VALUES (1, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  voice_name = excluded.voice_name,
  model = excluded.model,
  personality = excluded.personality,
  verbosity = excluded.verbosity,
  updated_at = excluded.updated_at
`

type SetVoiceSettingsParams struct {
	VoiceName   string `json:"voice_name"`
	Model       string `json:"model"`
	Personality string `json:"personality"`
	Verbosity   string `json:"verbosity"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) SetVoiceSettings(ctx context.Context, arg SetVoiceSettingsParams) error {
	_, err := q.db.ExecContext(ctx, setVoiceSettings,
		arg.VoiceName,
		arg.Model,
		arg.Personality,
		arg.Verbosity,
		arg.UpdatedAt,
	)
	return err
}
