/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ProjectProjectIdRouteImport } from "./routes/project.$projectId"
import { Route as ProjectProjectIdSettingsRouteImport } from "./routes/project.$projectId_.settings"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: "/project/$projectId",
  path: "/project/$projectId",
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdSettingsRoute =
  ProjectProjectIdSettingsRouteImport.update({
    id: "/project/$projectId_/settings",
    path: "/project/$projectId/settings",
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/project/$projectId": typeof ProjectProjectIdRoute
  "/project/$projectId/settings": typeof ProjectProjectIdSettingsRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/project/$projectId": typeof ProjectProjectIdRoute
  "/project/$projectId/settings": typeof ProjectProjectIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/project/$projectId": typeof ProjectProjectIdRoute
  "/project/$projectId_/settings": typeof ProjectProjectIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/project/$projectId" | "/project/$projectId/settings"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/project/$projectId" | "/project/$projectId/settings"
  id: "__root__" | "/" | "/project/$projectId" | "/project/$projectId_/settings"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  ProjectProjectIdSettingsRoute: typeof ProjectProjectIdSettingsRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/project/$projectId": {
      id: "/project/$projectId"
      path: "/project/$projectId"
      fullPath: "/project/$projectId"
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/project/$projectId_/settings": {
      id: "/project/$projectId_/settings"
      path: "/project/$projectId/settings"
      fullPath: "/project/$projectId/settings"
      preLoaderRoute: typeof ProjectProjectIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  ProjectProjectIdSettingsRoute: ProjectProjectIdSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
