// Code generated by typegen. DO NOT EDIT.

import { z } from "zod";

export const WireContentBlockSchema = z.object({
  type: z.string(),
  text: z.string().optional(),
  mediaType: z.string().optional(),
  url: z.string().optional(),
});

export const QueryAttachmentSchema = z.object({
  name: z.string(),
  mimeType: z.string(),
  dataUrl: z.string(),
});

export const DiffStatSchema = z.object({
  path: z.string(),
  insertions: z.number(),
  deletions: z.number(),
  status: z.string(),
});

export const FileStatusSchema = z.object({
  path: z.string(),
  status: z.string(),
});

export const CommandFileSchema = z.object({
  name: z.string(),
  source: z.string(),
  description: z.string(),
});

export const WireTextEventSchema = z.object({
  type: z.literal("text"),
  content: z.string(),
});

export const WireThinkingEventSchema = z.object({
  type: z.literal("thinking"),
  content: z.string(),
});

export const WireToolUseEventSchema = z.object({
  type: z.literal("tool_use"),
  toolId: z.string(),
  toolName: z.string(),
  toolInput: z.unknown(),
  category: z.string(),
});

export const WireToolResultEventSchema = z.object({
  type: z.literal("tool_result"),
  toolId: z.string(),
  content: z.array(WireContentBlockSchema),
});

export const WireResultEventSchema = z.object({
  type: z.literal("result"),
  cost: z.number(),
  duration: z.number(),
  usage: z.unknown(),
  stopReason: z.string(),
  contextWindow: z.number().optional(),
  inputTokens: z.number().optional(),
  outputTokens: z.number().optional(),
});

export const WireErrorEventSchema = z.object({
  type: z.literal("error"),
  message: z.string(),
  fatal: z.boolean(),
  errorType: z.string().optional(),
  retryAfterSecs: z.number().optional(),
});

export const WireRateLimitEventSchema = z.object({
  type: z.literal("rate_limit"),
  status: z.string(),
  utilization: z.number(),
  resetsAt: z.number().optional(),
});

export const WireStreamEventSchema = z.object({
  type: z.literal("stream"),
  event: z.unknown(),
});

export const WireCompactStatusEventSchema = z.object({
  type: z.literal("compact_status"),
  status: z.string(),
});

export const WireCompactBoundaryEventSchema = z.object({
  type: z.literal("compact_boundary"),
  trigger: z.string(),
  preTokens: z.number(),
});

export const WireContextManagementEventSchema = z.object({
  type: z.literal("context_management"),
  raw: z.unknown(),
});

export const SessionInfoSchema = z.object({
  id: z.string(),
  projectId: z.string(),
  name: z.string(),
  state: z.string(),
  connected: z.boolean(),
  model: z.string(),
  permissionMode: z.string(),
  autoApprove: z.boolean(),
  effort: z.string().optional(),
  maxBudget: z.number().optional(),
  maxTurns: z.number().optional(),
  totalCost: z.number(),
  turnCount: z.number(),
  worktreePath: z.string().optional(),
  worktreeBranch: z.string().optional(),
  worktreeMerged: z.boolean().optional(),
  completedAt: z.string().optional(),
  hasDirtyWorktree: z.boolean().optional(),
  hasUncommitted: z.boolean().optional(),
  commitsAhead: z.number(),
  commitsBehind: z.number(),
  branchMissing: z.boolean().optional(),
  mergeStatus: z.string().optional(),
  mergeConflictFiles: z.array(z.string()).optional(),
  gitOperation: z.string().optional(),
  gitVersion: z.number(),
  prUrl: z.string().optional(),
  createdAt: z.string(),
  updatedAt: z.string(),
  lastQueryAt: z.string().optional(),
});

export const CreateSessionResultSchema = z.object({
  sessionId: z.string(),
  name: z.string(),
  state: z.string(),
  connected: z.boolean(),
  model: z.string(),
  permissionMode: z.string(),
  autoApprove: z.boolean(),
  effort: z.string().optional(),
  maxBudget: z.number().optional(),
  maxTurns: z.number().optional(),
  worktreePath: z.string().optional(),
  worktreeBranch: z.string().optional(),
  createdAt: z.string(),
});

export const ListSessionsResultSchema = z.object({
  sessions: z.array(SessionInfoSchema),
});

export const HistoryTurnSchema = z.object({
  prompt: z.string(),
  attachments: z.array(QueryAttachmentSchema).optional(),
  events: z.array(z.unknown()),
});

export const HistoryResultSchema = z.object({
  turns: z.array(HistoryTurnSchema),
});

export const GitSnapshotSchema = z.object({
  sessionId: z.string(),
  state: z.string(),
  connected: z.boolean(),
  hasDirtyWorktree: z.boolean(),
  hasUncommitted: z.boolean(),
  worktreeMerged: z.boolean(),
  completedAt: z.string().optional(),
  commitsAhead: z.number(),
  commitsBehind: z.number(),
  branchMissing: z.boolean(),
  mergeStatus: z.string().optional(),
  mergeConflictFiles: z.array(z.string()).optional(),
  gitOperation: z.string().optional(),
  version: z.number(),
});

export const MergeResultSchema = z.object({
  status: z.string(),
  commitHash: z.string().optional(),
  conflictFiles: z.array(z.string()).optional(),
  error: z.string().optional(),
});

export const CreatePRResultSchema = z.object({
  status: z.string(),
  url: z.string().optional(),
  error: z.string().optional(),
});

export const SessionCommitResultSchema = z.object({
  commitHash: z.string(),
});

export const RebaseResultSchema = z.object({
  status: z.string(),
  conflictFiles: z.array(z.string()).optional(),
  error: z.string().optional(),
});

export const UncommittedFilesResultSchema = z.object({
  files: z.array(FileStatusSchema),
});

export const CleanResultSchema = z.object({
  status: z.string(),
  error: z.string().optional(),
});

export const DiffResultSchema = z.object({
  hasDiff: z.boolean(),
  summary: z.string(),
  files: z.array(DiffStatSchema),
  diff: z.string(),
  truncated: z.boolean(),
});

export const CommitMessageResultSchema = z.object({
  title: z.string(),
  description: z.string(),
});

export const PRDescriptionResultSchema = z.object({
  title: z.string(),
  body: z.string(),
});

export const ProjectGitStatusSchema = z.object({
  projectId: z.string(),
  branch: z.string(),
  hasRemote: z.boolean(),
  aheadRemote: z.number(),
  behindRemote: z.number(),
  uncommittedCount: z.number(),
});

export const TrackedFilesResultSchema = z.object({
  files: z.array(z.string()),
});

export const CommandsResultSchema = z.object({
  commands: z.array(CommandFileSchema),
});

export const ProjectCommitResultSchema = z.object({
  commitHash: z.string(),
});

export const ProjectSchema = z.object({
  id: z.string(),
  name: z.string(),
  path: z.string(),
  default_model: z.string(),
  default_permission_mode: z.string(),
  default_system_prompt: z.string(),
  created_at: z.string(),
  updated_at: z.string(),
  slug: z.string(),
  sort_order: z.number(),
});

export const ProjectSubscribePayloadSchema = z.object({
  projectId: z.string(),
});

export const SessionCreatePayloadSchema = z.object({
  projectId: z.string(),
  name: z.string(),
  worktree: z.boolean(),
  branch: z.string(),
  model: z.string(),
  planMode: z.boolean(),
  autoApprove: z.boolean(),
  effort: z.string(),
  maxBudget: z.number(),
  maxTurns: z.number(),
});

export const SessionQueryPayloadSchema = z.object({
  sessionId: z.string(),
  prompt: z.string(),
  attachments: z.array(QueryAttachmentSchema).optional(),
});

export const SessionListPayloadSchema = z.object({
  projectId: z.string(),
});

export const SessionStopPayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionHistoryPayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionDiffPayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionInterruptPayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionMergePayloadSchema = z.object({
  sessionId: z.string(),
  cleanup: z.boolean(),
});

export const SessionCreatePRPayloadSchema = z.object({
  sessionId: z.string(),
  title: z.string(),
  body: z.string(),
});

export const SessionDeletePayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionDeleteBulkPayloadSchema = z.object({
  sessionIds: z.array(z.string()),
});

export const SessionDeleteBulkResultItemSchema = z.object({
  sessionId: z.string(),
  success: z.boolean(),
  error: z.string().optional(),
});

export const SessionDeleteBulkResultSchema = z.object({
  results: z.array(SessionDeleteBulkResultItemSchema),
});

export const SessionSetModelPayloadSchema = z.object({
  sessionId: z.string(),
  model: z.string(),
});

export const SessionSetPermissionPayloadSchema = z.object({
  sessionId: z.string(),
  mode: z.string(),
});

export const SessionResolveApprovalPayloadSchema = z.object({
  sessionId: z.string(),
  approvalId: z.string(),
  allow: z.boolean(),
  message: z.string(),
});

export const SessionSetAutoApprovePayloadSchema = z.object({
  sessionId: z.string(),
  enabled: z.boolean(),
});

export const SessionResolveQuestionPayloadSchema = z.object({
  sessionId: z.string(),
  questionId: z.string(),
  answers: z.record(z.string(), z.string()),
});

export const SessionRenamePayloadSchema = z.object({
  sessionId: z.string(),
  name: z.string(),
});

export const SessionCommitPayloadSchema = z.object({
  sessionId: z.string(),
  message: z.string(),
});

export const SessionRebasePayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionGeneratePRDescPayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionGenerateCommitMsgPayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionMarkDonePayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionCleanPayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionUncommittedFilesPayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionUncommittedDiffPayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionRefreshGitPayloadSchema = z.object({
  sessionId: z.string(),
});

export const ProjectGitStatusPayloadSchema = z.object({
  projectId: z.string(),
});

export const ProjectFetchPayloadSchema = z.object({
  projectId: z.string(),
});

export const ProjectPushPayloadSchema = z.object({
  projectId: z.string(),
});

export const ProjectCommitPayloadSchema = z.object({
  projectId: z.string(),
  message: z.string(),
});

export const ProjectTrackedFilesPayloadSchema = z.object({
  projectId: z.string(),
});

export const ProjectCommandsPayloadSchema = z.object({
  projectId: z.string(),
});

export const ProjectReorderPayloadSchema = z.object({
  projectIds: z.array(z.string()),
});

export const WireEventSchema = z.discriminatedUnion("type", [
  WireTextEventSchema,
  WireThinkingEventSchema,
  WireToolUseEventSchema,
  WireToolResultEventSchema,
  WireResultEventSchema,
  WireErrorEventSchema,
  WireRateLimitEventSchema,
  WireStreamEventSchema,
  WireCompactStatusEventSchema,
  WireCompactBoundaryEventSchema,
  WireContextManagementEventSchema,
]);
