// Code generated by typegen. DO NOT EDIT.

export interface WireContentBlock {
  type: string;
  text?: string;
  mediaType?: string;
  url?: string;
}

export interface QueryAttachment {
  name: string;
  mimeType: string;
  dataUrl: string;
}

export interface DiffStat {
  path: string;
  insertions: number;
  deletions: number;
  status: string;
}

export interface FileStatus {
  path: string;
  status: string;
}

export interface CommandFile {
  name: string;
  source: string;
  description: string;
}

export interface WireTextEvent {
  type: "text";
  content: string;
  parentToolUseId?: string;
}

export interface WireThinkingEvent {
  type: "thinking";
  content: string;
  parentToolUseId?: string;
}

export interface WireToolUseEvent {
  type: "tool_use";
  toolId: string;
  toolName: string;
  toolInput: unknown;
  category: string;
  parentToolUseId?: string;
}

export interface WireToolResultEvent {
  type: "tool_result";
  toolId: string;
  content: WireContentBlock[];
  parentToolUseId?: string;
}

export interface WireResultEvent {
  type: "result";
  cost: number;
  duration: number;
  usage: unknown;
  stopReason: string;
  contextWindow?: number;
  inputTokens?: number;
  outputTokens?: number;
}

export interface WireErrorEvent {
  type: "error";
  content: string;
  fatal: boolean;
  errorType?: string;
  retryAfterSecs?: number;
}

export interface WireRateLimitEvent {
  type: "rate_limit";
  status: string;
  utilization: number;
  resetsAt?: number;
  rateLimitType?: string;
}

export interface WireStreamEvent {
  type: "stream";
  event: unknown;
}

export interface WireCompactStatusEvent {
  type: "compact_status";
  status: string;
}

export interface WireCompactBoundaryEvent {
  type: "compact_boundary";
  trigger: string;
  preTokens: number;
}

export interface WireContextManagementEvent {
  type: "context_management";
  raw: unknown;
}

export interface WireUserMessageEvent {
  type: "user_message";
  content: string;
  attachments?: QueryAttachment[];
}

export interface WireQuestionOption {
  label: string;
  description?: string;
}

export interface WireQuestion {
  question: string;
  header?: string;
  options?: WireQuestionOption[];
  multiSelect?: boolean;
}

export interface WirePendingApproval {
  approvalId: string;
  toolName: string;
  input: unknown;
}

export interface WirePendingQuestion {
  questionId: string;
  questions: WireQuestion[];
}

export interface BehaviorPresets {
  autoCommit: boolean;
  suggestParallel: boolean;
  planFirst: boolean;
  terse: boolean;
  customInstructions?: string;
}

export interface PresetDefinition {
  key: string;
  title: string;
  description: string;
}

export interface SessionInfo {
  id: string;
  projectId: string;
  name: string;
  state: string;
  connected: boolean;
  model: string;
  permissionMode: string;
  autoApproveMode: string;
  effort?: string;
  maxBudget?: number;
  maxTurns?: number;
  totalCost: number;
  turnCount: number;
  worktreePath?: string;
  worktreeBranch?: string;
  worktreeMerged?: boolean;
  completedAt?: string;
  hasDirtyWorktree?: boolean;
  hasUncommitted?: boolean;
  commitsAhead: number;
  commitsBehind: number;
  branchMissing?: boolean;
  mergeStatus?: string;
  mergeConflictFiles?: string[];
  gitOperation?: string;
  gitVersion: number;
  prUrl?: string;
  behaviorPresets: BehaviorPresets;
  teamId?: string;
  teamRole?: string;
  pendingApproval?: WirePendingApproval;
  pendingQuestion?: WirePendingQuestion;
  createdAt: string;
  updatedAt: string;
  lastQueryAt?: string;
}

export interface CreateSessionResult {
  sessionId: string;
  name: string;
  state: string;
  connected: boolean;
  model: string;
  permissionMode: string;
  autoApproveMode: string;
  effort?: string;
  maxBudget?: number;
  maxTurns?: number;
  worktreePath?: string;
  worktreeBranch?: string;
  behaviorPresets: BehaviorPresets;
  createdAt: string;
}

export interface ListSessionsResult {
  sessions: SessionInfo[];
}

export interface HistoryTurn {
  prompt: string;
  attachments?: QueryAttachment[];
  events: unknown[];
}

export interface HistoryResult {
  turns: HistoryTurn[];
}

export interface GitSnapshot {
  sessionId: string;
  state: string;
  connected: boolean;
  hasDirtyWorktree: boolean;
  hasUncommitted: boolean;
  worktreeMerged: boolean;
  completedAt?: string;
  commitsAhead: number;
  commitsBehind: number;
  branchMissing: boolean;
  mergeStatus?: string;
  mergeConflictFiles?: string[];
  gitOperation?: string;
  version: number;
}

export interface MergeResult {
  status: string;
  commitHash?: string;
  conflictFiles?: string[];
  error?: string;
}

export interface CreatePRResult {
  status: string;
  url?: string;
  error?: string;
}

export interface SessionCommitResult {
  commitHash: string;
}

export interface RebaseResult {
  status: string;
  conflictFiles?: string[];
  error?: string;
}

export interface UncommittedFilesResult {
  files: FileStatus[];
}

export interface CleanResult {
  status: string;
  error?: string;
}

export interface DiffResult {
  hasDiff: boolean;
  summary: string;
  files: DiffStat[];
  diff: string;
  truncated: boolean;
}

export interface CommitMessageResult {
  title: string;
  description: string;
}

export interface PRDescriptionResult {
  title: string;
  body: string;
}

export interface ProjectGitStatus {
  projectId: string;
  branch: string;
  hasRemote: boolean;
  aheadRemote: number;
  behindRemote: number;
  uncommittedCount: number;
}

export interface TrackedFilesResult {
  files: string[];
}

export interface CommandsResult {
  commands: CommandFile[];
}

export interface ProjectCommitResult {
  commitHash: string;
}

export interface Project {
  id: string;
  name: string;
  path: string;
  default_model: string;
  default_permission_mode: string;
  default_system_prompt: string;
  created_at: string;
  updated_at: string;
  slug: string;
  sort_order: number;
  default_behavior_presets: string;
  favorite: number;
}

export interface Tag {
  id: string;
  name: string;
  color: string;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export interface ProjectTag {
  project_id: string;
  tag_id: string;
}

export interface ProjectSubscribePayload {
  projectId: string;
}

export interface SessionCreatePayload {
  projectId: string;
  name: string;
  worktree: boolean;
  branch: string;
  model: string;
  planMode: boolean;
  autoApproveMode: string;
  effort: string;
  maxBudget: number;
  maxTurns: number;
  behaviorPresets: BehaviorPresets;
}

export interface SessionQueryPayload {
  sessionId: string;
  prompt: string;
  attachments?: QueryAttachment[];
}

export interface SessionListPayload {
  projectId: string;
}

export interface SessionStopPayload {
  sessionId: string;
}

export interface SessionHistoryPayload {
  sessionId: string;
}

export interface SessionDiffPayload {
  sessionId: string;
}

export interface SessionInterruptPayload {
  sessionId: string;
}

export interface SessionMergePayload {
  sessionId: string;
  mode: string;
}

export interface SessionCreatePRPayload {
  sessionId: string;
  title: string;
  body: string;
}

export interface SessionDeletePayload {
  sessionId: string;
}

export interface SessionDeleteBulkPayload {
  sessionIds: string[];
}

export interface SessionDeleteBulkResultItem {
  sessionId: string;
  success: boolean;
  error?: string;
}

export interface SessionDeleteBulkResult {
  results: SessionDeleteBulkResultItem[];
}

export interface SessionSetModelPayload {
  sessionId: string;
  model: string;
}

export interface SessionSetPermissionPayload {
  sessionId: string;
  mode: string;
}

export interface SessionResolveApprovalPayload {
  sessionId: string;
  approvalId: string;
  allow: boolean;
  message: string;
}

export interface SessionSetAutoApprovePayload {
  sessionId: string;
  mode: string;
}

export interface SessionResolveQuestionPayload {
  sessionId: string;
  questionId: string;
  answers: Record<string, string>;
}

export interface SessionRenamePayload {
  sessionId: string;
  name: string;
}

export interface SessionCommitPayload {
  sessionId: string;
  message: string;
}

export interface SessionRebasePayload {
  sessionId: string;
}

export interface SessionGeneratePRDescPayload {
  sessionId: string;
}

export interface SessionGenerateCommitMsgPayload {
  sessionId: string;
}

export interface SessionMarkDonePayload {
  sessionId: string;
}

export interface SessionCleanPayload {
  sessionId: string;
}

export interface SessionUncommittedFilesPayload {
  sessionId: string;
}

export interface SessionUncommittedDiffPayload {
  sessionId: string;
}

export interface SessionRefreshGitPayload {
  sessionId: string;
}

export interface ProjectGitStatusPayload {
  projectId: string;
}

export interface ProjectFetchPayload {
  projectId: string;
}

export interface ProjectPushPayload {
  projectId: string;
}

export interface ProjectCommitPayload {
  projectId: string;
  message: string;
}

export interface ProjectTrackedFilesPayload {
  projectId: string;
}

export interface ProjectCommandsPayload {
  projectId: string;
}

export interface ProjectReorderPayload {
  projectIds: string[];
}

export interface ProjectSetFavoritePayload {
  projectId: string;
  favorite: boolean;
}

export interface ProjectSetTagsPayload {
  projectId: string;
  tagIds: string[];
}

export interface TagCreatePayload {
  name: string;
  color: string;
}

export interface TagUpdatePayload {
  id: string;
  name: string;
  color: string;
}

export interface TagDeletePayload {
  id: string;
}

export interface TagListResult {
  tags: Tag[];
  projectTags: ProjectTag[];
}

export type WireEvent =
  | WireTextEvent
  | WireThinkingEvent
  | WireToolUseEvent
  | WireToolResultEvent
  | WireResultEvent
  | WireErrorEvent
  | WireRateLimitEvent
  | WireStreamEvent
  | WireCompactStatusEvent
  | WireCompactBoundaryEvent
  | WireContextManagementEvent
  | WireUserMessageEvent;
