// Code generated by typegen. DO NOT EDIT.

import { z } from "zod";

export const WireContentBlockSchema = z.object({
  type: z.string(),
  text: z.string().optional(),
  mediaType: z.string().optional(),
  url: z.string().optional(),
});

export const QueryAttachmentSchema = z.object({
  name: z.string(),
  mimeType: z.string(),
  dataUrl: z.string(),
});

export const DiffStatSchema = z.object({
  path: z.string(),
  insertions: z.number(),
  deletions: z.number(),
  status: z.string(),
});

export const FileStatusSchema = z.object({
  path: z.string(),
  status: z.string(),
});

export const CommandFileSchema = z.object({
  name: z.string(),
  source: z.string(),
  description: z.string(),
});

export const WireTextEventSchema = z.object({
  type: z.literal("text"),
  content: z.string(),
  parentToolUseId: z.string().optional(),
});

export const WireThinkingEventSchema = z.object({
  type: z.literal("thinking"),
  content: z.string(),
  signature: z.string().optional(),
  parentToolUseId: z.string().optional(),
});

export const WireToolUseEventSchema = z.object({
  type: z.literal("tool_use"),
  toolId: z.string(),
  toolName: z.string(),
  toolInput: z.unknown(),
  category: z.string(),
  parentToolUseId: z.string().optional(),
});

export const WireToolResultEventSchema = z.object({
  type: z.literal("tool_result"),
  toolId: z.string(),
  content: z.array(WireContentBlockSchema),
  parentToolUseId: z.string().optional(),
});

export const WireResultEventSchema = z.object({
  type: z.literal("result"),
  cost: z.number(),
  duration: z.number(),
  usage: z.unknown(),
  stopReason: z.string(),
  contextWindow: z.number().optional(),
  inputTokens: z.number().optional(),
  outputTokens: z.number().optional(),
  timestamp: z.number(),
});

export const WireErrorEventSchema = z.object({
  type: z.literal("error"),
  content: z.string(),
  fatal: z.boolean(),
  errorType: z.string().optional(),
  retryAfterSecs: z.number().optional(),
});

export const WireRateLimitEventSchema = z.object({
  type: z.literal("rate_limit"),
  status: z.string(),
  utilization: z.number(),
  resetsAt: z.number().optional(),
  rateLimitType: z.string().optional(),
});

export const WireStreamEventSchema = z.object({
  type: z.literal("stream"),
  event: z.unknown(),
});

export const WireCompactStatusEventSchema = z.object({
  type: z.literal("compact_status"),
  status: z.string(),
});

export const WireCompactBoundaryEventSchema = z.object({
  type: z.literal("compact_boundary"),
  trigger: z.string(),
  preTokens: z.number(),
});

export const WireContextManagementEventSchema = z.object({
  type: z.literal("context_management"),
  raw: z.unknown(),
});

export const WireUserMessageEventSchema = z.object({
  type: z.literal("user_message"),
  content: z.string(),
  messageId: z.string().optional(),
  attachments: z.array(QueryAttachmentSchema).optional(),
});

export const WireQuestionOptionSchema = z.object({
  label: z.string(),
  description: z.string().optional(),
});

export const WireQuestionSchema = z.object({
  question: z.string(),
  header: z.string().optional(),
  options: z.array(WireQuestionOptionSchema).optional(),
  multiSelect: z.boolean().optional(),
});

export const WirePendingApprovalSchema = z.object({
  approvalId: z.string(),
  toolName: z.string(),
  input: z.unknown(),
});

export const WirePendingQuestionSchema = z.object({
  questionId: z.string(),
  questions: z.array(WireQuestionSchema),
});

export const BehaviorPresetsSchema = z.object({
  autoCommit: z.boolean(),
  suggestParallel: z.boolean(),
  planFirst: z.boolean(),
  terse: z.boolean(),
  customInstructions: z.string().optional(),
});

export const PresetDefinitionSchema = z.object({
  key: z.string(),
  title: z.string(),
  description: z.string(),
});

export const SessionInfoSchema = z.object({
  id: z.string(),
  projectId: z.string(),
  name: z.string(),
  state: z.string(),
  connected: z.boolean(),
  model: z.string(),
  permissionMode: z.string(),
  autoApproveMode: z.string(),
  effort: z.string().optional(),
  maxBudget: z.number().optional(),
  maxTurns: z.number().optional(),
  totalCost: z.number(),
  turnCount: z.number(),
  worktreePath: z.string().optional(),
  worktreeBranch: z.string().optional(),
  worktreeMerged: z.boolean().optional(),
  completedAt: z.string().optional(),
  hasDirtyWorktree: z.boolean().optional(),
  hasUncommitted: z.boolean().optional(),
  commitsAhead: z.number(),
  commitsBehind: z.number(),
  branchMissing: z.boolean().optional(),
  mergeStatus: z.string().optional(),
  mergeConflictFiles: z.array(z.string()).optional(),
  gitOperation: z.string().optional(),
  gitVersion: z.number(),
  prUrl: z.string().optional(),
  behaviorPresets: BehaviorPresetsSchema,
  channelIds: z.array(z.string()).optional(),
  channelRoles: z.record(z.string(), z.string()).optional(),
  icon: z.string().optional(),
  pendingApproval: WirePendingApprovalSchema.optional(),
  pendingQuestion: WirePendingQuestionSchema.optional(),
  agentProfileId: z.string().optional(),
  agentProfileName: z.string().optional(),
  agentProfileAvatar: z.string().optional(),
  parentSessionId: z.string().optional(),
  createdAt: z.string(),
  updatedAt: z.string(),
  lastQueryAt: z.string().optional(),
});

export const CreateSessionResultSchema = z.object({
  sessionId: z.string(),
  name: z.string(),
  state: z.string(),
  connected: z.boolean(),
  model: z.string(),
  permissionMode: z.string(),
  autoApproveMode: z.string(),
  effort: z.string().optional(),
  maxBudget: z.number().optional(),
  maxTurns: z.number().optional(),
  worktreePath: z.string().optional(),
  worktreeBranch: z.string().optional(),
  behaviorPresets: BehaviorPresetsSchema,
  agentProfileId: z.string().optional(),
  agentProfileName: z.string().optional(),
  agentProfileAvatar: z.string().optional(),
  createdAt: z.string(),
});

export const ListSessionsResultSchema = z.object({
  sessions: z.array(SessionInfoSchema),
});

export const HistoryTurnSchema = z.object({
  prompt: z.string(),
  attachments: z.array(QueryAttachmentSchema).optional(),
  events: z.array(z.unknown()),
});

export const HistoryResultSchema = z.object({
  turns: z.array(HistoryTurnSchema),
  hasMore: z.boolean(),
  totalTurns: z.number(),
});

export const GitSnapshotSchema = z.object({
  sessionId: z.string(),
  state: z.string(),
  connected: z.boolean(),
  hasDirtyWorktree: z.boolean(),
  hasUncommitted: z.boolean(),
  worktreeMerged: z.boolean(),
  completedAt: z.string().optional(),
  commitsAhead: z.number(),
  commitsBehind: z.number(),
  branchMissing: z.boolean(),
  mergeStatus: z.string().optional(),
  mergeConflictFiles: z.array(z.string()).optional(),
  gitOperation: z.string().optional(),
  version: z.number(),
});

export const MergeResultSchema = z.object({
  status: z.string(),
  commitHash: z.string().optional(),
  conflictFiles: z.array(z.string()).optional(),
  error: z.string().optional(),
});

export const CreatePRResultSchema = z.object({
  status: z.string(),
  url: z.string().optional(),
  error: z.string().optional(),
});

export const SessionCommitResultSchema = z.object({
  commitHash: z.string(),
});

export const RebaseResultSchema = z.object({
  status: z.string(),
  conflictFiles: z.array(z.string()).optional(),
  error: z.string().optional(),
});

export const UncommittedFilesResultSchema = z.object({
  files: z.array(FileStatusSchema),
});

export const CleanResultSchema = z.object({
  status: z.string(),
  error: z.string().optional(),
});

export const DiffResultSchema = z.object({
  hasDiff: z.boolean(),
  summary: z.string(),
  files: z.array(DiffStatSchema),
  diff: z.string(),
  truncated: z.boolean(),
});

export const CommitMessageResultSchema = z.object({
  title: z.string(),
  description: z.string(),
});

export const PRDescriptionResultSchema = z.object({
  title: z.string(),
  body: z.string(),
});

export const ProjectGitStatusSchema = z.object({
  projectId: z.string(),
  branch: z.string(),
  hasRemote: z.boolean(),
  aheadRemote: z.number(),
  behindRemote: z.number(),
  uncommittedCount: z.number(),
});

export const TrackedFilesResultSchema = z.object({
  files: z.array(z.string()),
});

export const CommandsResultSchema = z.object({
  commands: z.array(CommandFileSchema),
});

export const ProjectCommitResultSchema = z.object({
  commitHash: z.string(),
});

export const BranchListResultSchema = z.object({
  local: z.array(z.string()),
  remote: z.array(z.string()),
});

export const ProjectUncommittedFilesResultSchema = z.object({
  files: z.array(FileStatusSchema),
});

export const ProjectSchema = z.object({
  id: z.string(),
  name: z.string(),
  path: z.string(),
  default_model: z.string(),
  default_permission_mode: z.string(),
  default_system_prompt: z.string(),
  created_at: z.string(),
  updated_at: z.string(),
  slug: z.string(),
  sort_order: z.number(),
  default_behavior_presets: z.string(),
  favorite: z.number(),
  color: z.string(),
  icon: z.string(),
  folder: z.string(),
  max_sessions: z.number(),
});

export const PromptTemplateSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  content: z.string(),
  settings: z.string(),
  tags: z.string(),
  sort_order: z.number(),
  created_at: z.string(),
  updated_at: z.string(),
});

export const ProjectSubscribePayloadSchema = z.object({
  projectId: z.string(),
});

export const SessionCreatePayloadSchema = z.object({
  projectId: z.string(),
  name: z.string(),
  worktree: z.boolean(),
  branch: z.string(),
  model: z.string(),
  planMode: z.boolean(),
  autoApproveMode: z.string(),
  effort: z.string(),
  maxBudget: z.number(),
  maxTurns: z.number(),
  behaviorPresets: BehaviorPresetsSchema,
  agentProfileId: z.string(),
  idempotencyKey: z.string().optional(),
});

export const SessionQueryPayloadSchema = z.object({
  sessionId: z.string(),
  prompt: z.string(),
  attachments: z.array(QueryAttachmentSchema).optional(),
});

export const SessionListPayloadSchema = z.object({
  projectId: z.string(),
});

export const SessionStopPayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionHistoryPayloadSchema = z.object({
  sessionId: z.string(),
  limit: z.number().optional(),
});

export const SessionDiffPayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionInterruptPayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionMergePayloadSchema = z.object({
  sessionId: z.string(),
  mode: z.string(),
});

export const SessionCreatePRPayloadSchema = z.object({
  sessionId: z.string(),
  title: z.string(),
  body: z.string(),
});

export const SessionDeletePayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionDeleteBulkPayloadSchema = z.object({
  sessionIds: z.array(z.string()),
});

export const SessionDeleteBulkResultItemSchema = z.object({
  sessionId: z.string(),
  success: z.boolean(),
  error: z.string().optional(),
});

export const SessionDeleteBulkResultSchema = z.object({
  results: z.array(SessionDeleteBulkResultItemSchema),
});

export const SessionSetModelPayloadSchema = z.object({
  sessionId: z.string(),
  model: z.string(),
});

export const SessionSetPermissionPayloadSchema = z.object({
  sessionId: z.string(),
  mode: z.string(),
});

export const SessionResolveApprovalPayloadSchema = z.object({
  sessionId: z.string(),
  approvalId: z.string(),
  allow: z.boolean(),
  message: z.string(),
});

export const SessionSetAutoApprovePayloadSchema = z.object({
  sessionId: z.string(),
  mode: z.string(),
});

export const SessionResolveQuestionPayloadSchema = z.object({
  sessionId: z.string(),
  questionId: z.string(),
  answers: z.record(z.string(), z.string()),
});

export const SessionRenamePayloadSchema = z.object({
  sessionId: z.string(),
  name: z.string(),
});

export const SessionCommitPayloadSchema = z.object({
  sessionId: z.string(),
  message: z.string(),
});

export const SessionRebasePayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionGeneratePRDescPayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionGenerateCommitMsgPayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionMarkDonePayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionCleanPayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionUncommittedFilesPayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionUncommittedDiffPayloadSchema = z.object({
  sessionId: z.string(),
});

export const SessionRefreshGitPayloadSchema = z.object({
  sessionId: z.string(),
});

export const ProjectGitStatusPayloadSchema = z.object({
  projectId: z.string(),
});

export const ProjectFetchPayloadSchema = z.object({
  projectId: z.string(),
});

export const ProjectPushPayloadSchema = z.object({
  projectId: z.string(),
});

export const ProjectCommitPayloadSchema = z.object({
  projectId: z.string(),
  message: z.string(),
});

export const ProjectListBranchesPayloadSchema = z.object({
  projectId: z.string(),
});

export const ProjectCheckoutPayloadSchema = z.object({
  projectId: z.string(),
  branch: z.string(),
});

export const ProjectPullPayloadSchema = z.object({
  projectId: z.string(),
});

export const ProjectTrackedFilesPayloadSchema = z.object({
  projectId: z.string(),
});

export const ProjectCommandsPayloadSchema = z.object({
  projectId: z.string(),
});

export const ProjectReorderPayloadSchema = z.object({
  projectIds: z.array(z.string()),
});

export const ProjectSetFavoritePayloadSchema = z.object({
  projectId: z.string(),
  favorite: z.boolean(),
});

export const ProjectUncommittedFilesPayloadSchema = z.object({
  projectId: z.string(),
});

export const ProjectDiscardPayloadSchema = z.object({
  projectId: z.string(),
});

export const ProjectActivityPayloadSchema = z.object({
  projectId: z.string(),
});

export const ScreencastMetadataSchema = z.object({
  offsetTop: z.number(),
  pageScaleFactor: z.number(),
  deviceWidth: z.number(),
  deviceHeight: z.number(),
  scrollOffsetX: z.number(),
  scrollOffsetY: z.number(),
  timestamp: z.number(),
});

export const PushSessionEventSchema = z.object({
  sessionId: z.string(),
  event: z.unknown(),
});

export const PushSessionRenamedSchema = z.object({
  sessionId: z.string(),
  name: z.string(),
});

export const PushSessionDeletedSchema = z.object({
  sessionId: z.string(),
});

export const PushPRUpdatedSchema = z.object({
  sessionId: z.string(),
  prUrl: z.string(),
});

export const PushToolPermissionSchema = z.object({
  sessionId: z.string(),
  approvalId: z.string(),
  toolName: z.string(),
  input: z.unknown(),
});

export const PushApprovalResolvedSchema = z.object({
  sessionId: z.string(),
  approvalId: z.string(),
});

export const PushPermissionModeChangedSchema = z.object({
  sessionId: z.string(),
  permissionMode: z.string(),
});

export const PushUserQuestionSchema = z.object({
  sessionId: z.string(),
  questionId: z.string(),
  questions: z.array(WireQuestionSchema),
});

export const PushQuestionResolvedSchema = z.object({
  sessionId: z.string(),
  questionId: z.string(),
});

export const PushTurnStartedSchema = z.object({
  sessionId: z.string(),
  prompt: z.string(),
  attachments: z.array(QueryAttachmentSchema).optional(),
});

export const PushSessionPulseSchema = z.object({
  sessionId: z.string(),
  lastToolCategory: z.string().optional(),
  lastFilePath: z.string().optional(),
  toolCallCount: z.number(),
  commitCount: z.number(),
  errorCount: z.number(),
  turnStartedAt: z.number(),
  todoTotal: z.number(),
  todoCompleted: z.number(),
});

export const ChannelMemberSchema = z.object({
  sessionId: z.string(),
  name: z.string(),
  role: z.string(),
  state: z.string(),
  connected: z.boolean(),
  worktreePath: z.string().optional(),
});

export const ChannelInfoSchema = z.object({
  id: z.string(),
  projectId: z.string(),
  name: z.string(),
  members: z.array(ChannelMemberSchema),
  createdAt: z.string(),
});

export const PushChannelDeletedSchema = z.object({
  channelId: z.string(),
});

export const PushChannelMemberJoinedSchema = z.object({
  channelId: z.string(),
  member: ChannelMemberSchema,
  channel: ChannelInfoSchema.optional(),
});

export const PushChannelMemberLeftSchema = z.object({
  channelId: z.string(),
  sessionId: z.string(),
});

export const TeamBehaviorPresetsSchema = z.object({
  autoCommit: z.boolean(),
  suggestParallel: z.boolean(),
  planFirst: z.boolean(),
  terse: z.boolean(),
  customInstructions: z.string().optional(),
});

export const AgentProfileConfigSchema = z.object({
  model: z.string().optional(),
  permissionMode: z.string().optional(),
  autoApproveMode: z.string().optional(),
  effort: z.string().optional(),
  behaviorPresets: TeamBehaviorPresetsSchema,
  systemPromptAdditions: z.string().optional(),
  communicationMode: z.string().optional(),
  capabilities: z.array(z.string()).optional(),
});

export const AgentProfileInfoSchema = z.object({
  id: z.string(),
  name: z.string(),
  role: z.string(),
  description: z.string(),
  projectId: z.string(),
  avatar: z.string(),
  config: AgentProfileConfigSchema,
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const TeamInfoSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  members: z.array(AgentProfileInfoSchema),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const PushIDOnlySchema = z.object({
  id: z.string(),
});

export const PersonaInteractionInfoSchema = z.object({
  id: z.string(),
  profileId: z.string(),
  teamId: z.string(),
  askerType: z.string(),
  askerId: z.string(),
  question: z.string(),
  action: z.string(),
  confidence: z.number(),
  response: z.string(),
  redirectTo: z.string(),
  responseTimeMs: z.number(),
  createdAt: z.string(),
});

export const ActivityItemSchema = z.object({
  kind: z.string(),
  itemId: z.string(),
  sourceId: z.string(),
  sourceName: z.string(),
  content: z.string(),
  eventType: z.string(),
  category: z.string().optional(),
  filePath: z.string().optional(),
  createdAt: z.string(),
});

export const PushBrowserFrameSchema = z.object({
  sessionId: z.string(),
  data: z.string(),
  metadata: ScreencastMetadataSchema,
});

export const PushBrowserStoppedSchema = z.object({
  sessionId: z.string(),
  reason: z.string(),
});

export const WireEventSchema = z.discriminatedUnion("type", [
  WireTextEventSchema,
  WireThinkingEventSchema,
  WireToolUseEventSchema,
  WireToolResultEventSchema,
  WireResultEventSchema,
  WireErrorEventSchema,
  WireRateLimitEventSchema,
  WireStreamEventSchema,
  WireCompactStatusEventSchema,
  WireCompactBoundaryEventSchema,
  WireContextManagementEventSchema,
  WireUserMessageEventSchema,
]);

export const pushSchemaMap = {
  "session.event": PushSessionEventSchema,
  "session.state": GitSnapshotSchema,
  "session.created": SessionInfoSchema,
  "session.renamed": PushSessionRenamedSchema,
  "session.deleted": PushSessionDeletedSchema,
  "session.pr-updated": PushPRUpdatedSchema,
  "session.tool-permission": PushToolPermissionSchema,
  "session.user-question": PushUserQuestionSchema,
  "session.approval-auto-resolved": PushApprovalResolvedSchema,
  "session.approval-resolved": PushApprovalResolvedSchema,
  "session.question-resolved": PushQuestionResolvedSchema,
  "session.permission-mode-changed": PushPermissionModeChangedSchema,
  "session.turn-started": PushTurnStartedSchema,
  "session.pulse": PushSessionPulseSchema,
  "project.git-status": ProjectGitStatusSchema,
  "project.updated": ProjectSchema,
  "channel.created": ChannelInfoSchema,
  "channel.updated": ChannelInfoSchema,
  "channel.deleted": PushChannelDeletedSchema,
  "channel.dissolved": PushChannelDeletedSchema,
  "channel.member-joined": PushChannelMemberJoinedSchema,
  "channel.member-left": PushChannelMemberLeftSchema,
  "agent-profile.created": AgentProfileInfoSchema,
  "agent-profile.updated": AgentProfileInfoSchema,
  "agent-profile.deleted": PushIDOnlySchema,
  "team.created": TeamInfoSchema,
  "team.updated": TeamInfoSchema,
  "team.deleted": PushIDOnlySchema,
  "persona.interaction": PersonaInteractionInfoSchema,
  "project.activity-item": ActivityItemSchema,
  "browser.frame": PushBrowserFrameSchema,
  "browser.stopped": PushBrowserStoppedSchema,
} as const;
