/**
 * The icon catalog behind both icon pickers — projects and machines.
 *
 * Categories are lists of lucide ids, never imported components: the grid
 * renders them through `DynamicIcon`, so a few hundred featured icons cost
 * nothing in the main bundle and load only when a picker opens. Search still
 * reaches every lucide icon; these are the ones worth a glance.
 *
 * One catalog, two orders (`iconGroupsFor`): a machine picker leads with
 * devices and places, a project picker with dev tools. Everything else —
 * animals included — is offered to both, because a box named after a pet and
 * a repo named after a bird want the same glyph.
 */

export interface IconGroup {
  label: string;
  ids: string[];
}

export const ICON_GROUPS: IconGroup[] = [
  {
    label: "Devices",
    ids: [
      "laptop",
      "laptop-minimal",
      "monitor",
      "server",
      "cloud",
      "container",
      "cpu",
      "hard-drive",
      "smartphone",
      "tablet",
      "database",
      "terminal",
      "globe",
      "house",
      "building-2",
      "rocket",
      "box",
      "microchip",
      "memory-stick",
      "router",
      "wifi",
      "printer",
      "keyboard",
      "mouse",
      "gamepad-2",
      "tv",
      "speaker",
      "projector",
      "radio-tower",
      "satellite-dish",
      "network",
      "cable",
      "plug",
      "battery-full",
      "power",
      "server-cog",
      "cloud-cog",
      "usb",
      "watch",
      "hard-drive-download",
      "monitor-smartphone",
      "computer",
    ],
  },
  {
    label: "Places",
    ids: [
      "house",
      "home",
      "factory",
      "warehouse",
      "school",
      "hospital",
      "store",
      "hotel",
      "church",
      "castle",
      "tent",
      "building",
      "landmark",
      "tower-control",
      "mountain-snow",
      "tree-palm",
      "tent-tree",
      "caravan",
    ],
  },
  {
    label: "Dev",
    ids: [
      "code",
      "code-xml",
      "terminal",
      "cpu",
      "server",
      "database",
      "git-branch",
      "git-merge",
      "git-pull-request",
      "git-commit-horizontal",
      "bug",
      "file-code",
      "braces",
      "brackets",
      "binary",
      "regex",
      "variable",
      "function-square",
      "settings",
      "cog",
      "cloud",
      "container",
      "bot",
      "blocks",
      "boxes",
      "webhook",
      "workflow",
      "component",
      "layout-template",
      "app-window",
      "square-terminal",
    ],
  },
  {
    label: "General",
    ids: [
      "globe",
      "rocket",
      "zap",
      "package",
      "layers",
      "shield",
      "shield-check",
      "lock",
      "key",
      "wrench",
      "hammer",
      "lightbulb",
      "puzzle",
      "target",
      "flag",
      "bookmark",
      "tag",
      "bell",
      "archive",
      "inbox",
      "folder",
      "link",
      "magnet",
      "anchor",
    ],
  },
  {
    label: "Work",
    ids: [
      "layout-dashboard",
      "briefcase",
      "bar-chart-2",
      "chart-line",
      "chart-pie",
      "trending-up",
      "calendar",
      "clock",
      "users",
      "user",
      "mail",
      "message-square",
      "messages-square",
      "phone",
      "wallet",
      "credit-card",
      "receipt",
      "banknote",
      "coins",
      "piggy-bank",
      "shopping-cart",
      "shopping-bag",
      "store",
      "landmark",
      "scale",
      "gavel",
      "handshake",
      "presentation",
      "clipboard-list",
      "kanban",
      "notebook",
    ],
  },
  {
    label: "Media",
    ids: [
      "smartphone",
      "camera",
      "image",
      "headphones",
      "music",
      "music-2",
      "mic",
      "radio",
      "tv",
      "film",
      "clapperboard",
      "video",
      "paintbrush",
      "palette",
      "pen-tool",
      "brush",
      "pencil",
      "scissors",
      "type",
      "book",
      "library",
      "newspaper",
      "podcast",
      "disc-3",
      "guitar",
      "piano",
      "drum",
    ],
  },
  {
    label: "Animals",
    ids: [
      "cat",
      "dog",
      "bird",
      "fish",
      "rabbit",
      "squirrel",
      "turtle",
      "snail",
      "rat",
      "worm",
      "shrimp",
      "panda",
      "paw-print",
      "feather",
      "egg",
      "bone",
      "bug",
      "origami",
      "fish-symbol",
    ],
  },
  {
    label: "Nature",
    ids: [
      "tree-pine",
      "trees",
      "tree-deciduous",
      "tree-palm",
      "leaf",
      "leafy-green",
      "flower",
      "flower-2",
      "clover",
      "sprout",
      "shrub",
      "mountain",
      "mountain-snow",
      "sun",
      "sunrise",
      "moon",
      "moon-star",
      "star",
      "cloud-sun",
      "cloud-rain",
      "cloud-lightning",
      "rainbow",
      "snowflake",
      "flame",
      "droplet",
      "waves",
      "wind",
      "tornado",
      "shell",
      "earth",
    ],
  },
  {
    label: "Food",
    ids: [
      "coffee",
      "cup-soda",
      "milk",
      "pizza",
      "apple",
      "cherry",
      "grape",
      "carrot",
      "banana",
      "citrus",
      "salad",
      "sandwich",
      "soup",
      "croissant",
      "cookie",
      "cake-slice",
      "cake",
      "donut",
      "ice-cream-cone",
      "candy",
      "popcorn",
      "egg-fried",
      "beef",
      "drumstick",
      "ham",
      "fish",
      "beer",
      "wine",
      "martini",
      "hop",
      "wheat",
      "utensils",
      "chef-hat",
    ],
  },
  {
    label: "Travel",
    ids: [
      "plane",
      "car",
      "car-front",
      "bike",
      "bus",
      "train-front",
      "tram-front",
      "ship",
      "sailboat",
      "anchor",
      "map",
      "map-pin",
      "compass",
      "tent",
      "castle",
      "footprints",
      "luggage",
      "fuel",
      "rocket",
      "truck",
      "tractor",
      "scooter",
    ],
  },
  {
    label: "Sport & play",
    ids: [
      "trophy",
      "medal",
      "award",
      "dumbbell",
      "volleyball",
      "goal",
      "gamepad-2",
      "joystick",
      "dice-5",
      "dices",
      "crown",
      "gem",
      "sparkles",
      "ghost",
      "skull",
      "swords",
      "wand-sparkles",
      "party-popper",
      "gift",
      "balloon",
      "tickets",
      "chess-knight",
      "chess-queen",
      "spade",
      "club",
    ],
  },
  {
    label: "Science",
    ids: [
      "atom",
      "brain",
      "dna",
      "flask-conical",
      "flask-round",
      "test-tube",
      "microscope",
      "telescope",
      "orbit",
      "satellite",
      "graduation-cap",
      "book-open",
      "calculator",
      "sigma",
      "infinity",
      "pi",
      "radiation",
      "magnet",
    ],
  },
  {
    label: "Health",
    ids: [
      "heart-pulse",
      "activity",
      "pill",
      "stethoscope",
      "syringe",
      "hospital",
      "cross",
      "bandage",
      "apple",
      "accessibility",
      "baby",
      "smile",
    ],
  },
  {
    label: "Symbols",
    ids: [
      "heart",
      "star",
      "diamond",
      "circle",
      "square",
      "triangle",
      "hexagon",
      "octagon",
      "pentagon",
      "asterisk",
      "hash",
      "at-sign",
      "infinity",
      "sparkle",
      "smile",
      "laugh",
      "frown",
      "ghost",
      "skull",
      "flag",
      "flame",
      "zap",
      "snowflake",
    ],
  },
];

const PROJECT_LEAD = ["Dev", "General", "Work"];
const MACHINE_LEAD = ["Devices", "Places"];

/**
 * The catalog in the order a picker shows it: the leading categories first,
 * the rest in catalog order. An id appears once, in the first group that
 * lists it, so a grid never offers the same glyph twice.
 */
export function iconGroupsFor(kind: "project" | "machine"): IconGroup[] {
  const lead = kind === "machine" ? MACHINE_LEAD : PROJECT_LEAD;
  const ordered = [
    ...lead.flatMap((label) => ICON_GROUPS.filter((g) => g.label === label)),
    ...ICON_GROUPS.filter((g) => !lead.includes(g.label)),
  ];
  const seen = new Set<string>();
  return ordered.map((group) => ({
    label: group.label,
    ids: group.ids.filter((id) => {
      if (seen.has(id)) return false;
      seen.add(id);
      return true;
    }),
  }));
}
