// Runtime validation layer for push events.
// Types and schemas are generated by typegen — see generated-types.ts / generated-schemas.ts.

import { pushSchemaMap } from "~/lib/generated-schemas";
import type { PushEventMap, PushEventType } from "~/lib/generated-types";

export type { PushEventMap, PushEventType };

/**
 * Validate a push event payload. Returns the parsed data on success,
 * or undefined on failure (logs a warning).
 */
export function validatePushPayload<K extends PushEventType>(
  type: K,
  payload: unknown,
): PushEventMap[K] | undefined {
  const schema = pushSchemaMap[type];
  if (!schema) return payload as PushEventMap[K];
  const result = schema.safeParse(payload);
  if (!result.success) {
    console.warn(`[WS] Invalid ${type} payload:`, result.error.issues);
    return undefined;
  }
  return result.data as PushEventMap[K];
}

/** Check whether a string is a known push event type. */
export function isKnownPushEvent(type: string): type is PushEventType {
  return type in pushSchemaMap;
}
